// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: Qot_GetSearchNews.proto

package qotgetsearchnews

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewsSubType int32

const (
	NewsSubType_NewsSubType_ALL    NewsSubType = 0 //全部
	NewsSubType_NewsSubType_NEWS   NewsSubType = 1 //新闻
	NewsSubType_NewsSubType_NOTICE NewsSubType = 2 //公告
	NewsSubType_NewsSubType_RATING NewsSubType = 3 //评级
)

// Enum value maps for NewsSubType.
var (
	NewsSubType_name = map[int32]string{
		0: "NewsSubType_ALL",
		1: "NewsSubType_NEWS",
		2: "NewsSubType_NOTICE",
		3: "NewsSubType_RATING",
	}
	NewsSubType_value = map[string]int32{
		"NewsSubType_ALL":    0,
		"NewsSubType_NEWS":   1,
		"NewsSubType_NOTICE": 2,
		"NewsSubType_RATING": 3,
	}
)

func (x NewsSubType) Enum() *NewsSubType {
	p := new(NewsSubType)
	*p = x
	return p
}

func (x NewsSubType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NewsSubType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetSearchNews_proto_enumTypes[0].Descriptor()
}

func (NewsSubType) Type() protoreflect.EnumType {
	return &file_Qot_GetSearchNews_proto_enumTypes[0]
}

func (x NewsSubType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *NewsSubType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = NewsSubType(num)
	return nil
}

// Deprecated: Use NewsSubType.Descriptor instead.
func (NewsSubType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetSearchNews_proto_rawDescGZIP(), []int{0}
}

type SearchNews struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Title             *string                `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`                                                  //标题（含关键词）
	NewsSubType       *int32                 `protobuf:"varint,2,opt,name=news_sub_type,json=newsSubType" json:"news_sub_type,omitempty"`                //Qot_GetSearchNews.NewsSubType，资讯子类型
	Source            *string                `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`                                                //来源，如 富途资讯 / MT Newswires / Benzinga
	PublishTime       *string                `protobuf:"bytes,4,opt,name=publish_time,json=publishTime" json:"publish_time,omitempty"`                   //发布时间戳字符串
	ViewCount         *int64                 `protobuf:"varint,5,opt,name=view_count,json=viewCount" json:"view_count,omitempty"`                        //浏览量
	RelatedSecurities []string               `protobuf:"bytes,6,rep,name=related_securities,json=relatedSecurities" json:"related_securities,omitempty"` //关联标的列表，如 LITE.US，用于跳转
	Url               *string                `protobuf:"bytes,7,opt,name=url" json:"url,omitempty"`                                                      //详情页深链 / H5 链接
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchNews) Reset() {
	*x = SearchNews{}
	mi := &file_Qot_GetSearchNews_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNews) ProtoMessage() {}

func (x *SearchNews) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetSearchNews_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNews.ProtoReflect.Descriptor instead.
func (*SearchNews) Descriptor() ([]byte, []int) {
	return file_Qot_GetSearchNews_proto_rawDescGZIP(), []int{0}
}

func (x *SearchNews) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *SearchNews) GetNewsSubType() int32 {
	if x != nil && x.NewsSubType != nil {
		return *x.NewsSubType
	}
	return 0
}

func (x *SearchNews) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *SearchNews) GetPublishTime() string {
	if x != nil && x.PublishTime != nil {
		return *x.PublishTime
	}
	return ""
}

func (x *SearchNews) GetViewCount() int64 {
	if x != nil && x.ViewCount != nil {
		return *x.ViewCount
	}
	return 0
}

func (x *SearchNews) GetRelatedSecurities() []string {
	if x != nil {
		return x.RelatedSecurities
	}
	return nil
}

func (x *SearchNews) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       *string                `protobuf:"bytes,1,req,name=keyword" json:"keyword,omitempty"`                               //搜索词，如 lite
	MaxCount      *int32                 `protobuf:"varint,2,opt,name=max_count,json=maxCount" json:"max_count,omitempty"`            //资讯条数上限，默认 10
	NewsSubType   *int32                 `protobuf:"varint,3,opt,name=news_sub_type,json=newsSubType" json:"news_sub_type,omitempty"` //Qot_GetSearchNews.NewsSubType，资讯子类型，默认 NewsSubType_ALL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetSearchNews_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetSearchNews_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetSearchNews_proto_rawDescGZIP(), []int{1}
}

func (x *C2S) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *C2S) GetMaxCount() int32 {
	if x != nil && x.MaxCount != nil {
		return *x.MaxCount
	}
	return 0
}

func (x *C2S) GetNewsSubType() int32 {
	if x != nil && x.NewsSubType != nil {
		return *x.NewsSubType
	}
	return 0
}

type S2C struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SearchNewsList []*SearchNews          `protobuf:"bytes,1,rep,name=search_news_list,json=searchNewsList" json:"search_news_list,omitempty"` //搜索资讯列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetSearchNews_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetSearchNews_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetSearchNews_proto_rawDescGZIP(), []int{2}
}

func (x *S2C) GetSearchNewsList() []*SearchNews {
	if x != nil {
		return x.SearchNewsList
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetSearchNews_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetSearchNews_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetSearchNews_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType，返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetSearchNews_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetSearchNews_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetSearchNews_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetSearchNews_proto protoreflect.FileDescriptor

const file_Qot_GetSearchNews_proto_rawDesc = "" +
	"\n" +
	"\x17Qot_GetSearchNews.proto\x12\x11Qot_GetSearchNews\"\xe1\x01\n" +
	"\n" +
	"SearchNews\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\"\n" +
	"\rnews_sub_type\x18\x02 \x01(\x05R\vnewsSubType\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12!\n" +
	"\fpublish_time\x18\x04 \x01(\tR\vpublishTime\x12\x1d\n" +
	"\n" +
	"view_count\x18\x05 \x01(\x03R\tviewCount\x12-\n" +
	"\x12related_securities\x18\x06 \x03(\tR\x11relatedSecurities\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\"`\n" +
	"\x03C2S\x12\x18\n" +
	"\akeyword\x18\x01 \x02(\tR\akeyword\x12\x1b\n" +
	"\tmax_count\x18\x02 \x01(\x05R\bmaxCount\x12\"\n" +
	"\rnews_sub_type\x18\x03 \x01(\x05R\vnewsSubType\"N\n" +
	"\x03S2C\x12G\n" +
	"\x10search_news_list\x18\x01 \x03(\v2\x1d.Qot_GetSearchNews.SearchNewsR\x0esearchNewsList\"3\n" +
	"\aRequest\x12(\n" +
	"\x03c2s\x18\x01 \x02(\v2\x16.Qot_GetSearchNews.C2SR\x03c2s\"\x86\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12(\n" +
	"\x03s2c\x18\x04 \x01(\v2\x16.Qot_GetSearchNews.S2CR\x03s2c*h\n" +
	"\vNewsSubType\x12\x13\n" +
	"\x0fNewsSubType_ALL\x10\x00\x12\x14\n" +
	"\x10NewsSubType_NEWS\x10\x01\x12\x16\n" +
	"\x12NewsSubType_NOTICE\x10\x02\x12\x16\n" +
	"\x12NewsSubType_RATING\x10\x03BN\n" +
	"\x13com.futu.openapi.pbZ7github.com/shing1211/futuapi4go/pkg/pb/qotgetsearchnews"

var (
	file_Qot_GetSearchNews_proto_rawDescOnce sync.Once
	file_Qot_GetSearchNews_proto_rawDescData []byte
)

func file_Qot_GetSearchNews_proto_rawDescGZIP() []byte {
	file_Qot_GetSearchNews_proto_rawDescOnce.Do(func() {
		file_Qot_GetSearchNews_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetSearchNews_proto_rawDesc), len(file_Qot_GetSearchNews_proto_rawDesc)))
	})
	return file_Qot_GetSearchNews_proto_rawDescData
}

var file_Qot_GetSearchNews_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Qot_GetSearchNews_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetSearchNews_proto_goTypes = []any{
	(NewsSubType)(0),   // 0: Qot_GetSearchNews.NewsSubType
	(*SearchNews)(nil), // 1: Qot_GetSearchNews.SearchNews
	(*C2S)(nil),        // 2: Qot_GetSearchNews.C2S
	(*S2C)(nil),        // 3: Qot_GetSearchNews.S2C
	(*Request)(nil),    // 4: Qot_GetSearchNews.Request
	(*Response)(nil),   // 5: Qot_GetSearchNews.Response
}
var file_Qot_GetSearchNews_proto_depIdxs = []int32{
	1, // 0: Qot_GetSearchNews.S2C.search_news_list:type_name -> Qot_GetSearchNews.SearchNews
	2, // 1: Qot_GetSearchNews.Request.c2s:type_name -> Qot_GetSearchNews.C2S
	3, // 2: Qot_GetSearchNews.Response.s2c:type_name -> Qot_GetSearchNews.S2C
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Qot_GetSearchNews_proto_init() }
func file_Qot_GetSearchNews_proto_init() {
	if File_Qot_GetSearchNews_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetSearchNews_proto_rawDesc), len(file_Qot_GetSearchNews_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetSearchNews_proto_goTypes,
		DependencyIndexes: file_Qot_GetSearchNews_proto_depIdxs,
		EnumInfos:         file_Qot_GetSearchNews_proto_enumTypes,
		MessageInfos:      file_Qot_GetSearchNews_proto_msgTypes,
	}.Build()
	File_Qot_GetSearchNews_proto = out.File
	file_Qot_GetSearchNews_proto_goTypes = nil
	file_Qot_GetSearchNews_proto_depIdxs = nil
}
