// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: Qot_GetCapitalFlow.proto

package qotgetcapitalflow

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/shing1211/futuapi4go/pkg/pb/common"
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *qotcommon.Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`      //股票
	PeriodType    *int32                 `protobuf:"varint,2,opt,name=periodType" json:"periodType,omitempty"` // Qot_Common.PeriodType 周期类型
	BeginTime     *string                `protobuf:"bytes,3,opt,name=beginTime" json:"beginTime,omitempty"`    // 开始时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
	EndTime       *string                `protobuf:"bytes,4,opt,name=endTime" json:"endTime,omitempty"`        // 结束时间（格式：yyyy-MM-dd），仅周期类型不为实时有效
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetCapitalFlow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCapitalFlow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetCapitalFlow_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *C2S) GetPeriodType() int32 {
	if x != nil && x.PeriodType != nil {
		return *x.PeriodType
	}
	return 0
}

func (x *C2S) GetBeginTime() string {
	if x != nil && x.BeginTime != nil {
		return *x.BeginTime
	}
	return ""
}

func (x *C2S) GetEndTime() string {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return ""
}

type CapitalFlowItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InFlow        *float64               `protobuf:"fixed64,1,req,name=inFlow" json:"inFlow,omitempty"`           // 整体净流入
	Time          *string                `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`                 //开始时间字符串,以分钟为单位
	Timestamp     *float64               `protobuf:"fixed64,3,opt,name=timestamp" json:"timestamp,omitempty"`     //开始时间戳
	MainInFlow    *float64               `protobuf:"fixed64,4,opt,name=mainInFlow" json:"mainInFlow,omitempty"`   // 主力大单净流入，仅周期类型不为实时有效
	SuperInFlow   *float64               `protobuf:"fixed64,5,opt,name=superInFlow" json:"superInFlow,omitempty"` // 特大单净流入
	BigInFlow     *float64               `protobuf:"fixed64,6,opt,name=bigInFlow" json:"bigInFlow,omitempty"`     // 大单净流入
	MidInFlow     *float64               `protobuf:"fixed64,7,opt,name=midInFlow" json:"midInFlow,omitempty"`     // 中单净流入
	SmlInFlow     *float64               `protobuf:"fixed64,8,opt,name=smlInFlow" json:"smlInFlow,omitempty"`     // 小单净流入
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapitalFlowItem) Reset() {
	*x = CapitalFlowItem{}
	mi := &file_Qot_GetCapitalFlow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapitalFlowItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapitalFlowItem) ProtoMessage() {}

func (x *CapitalFlowItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCapitalFlow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapitalFlowItem.ProtoReflect.Descriptor instead.
func (*CapitalFlowItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetCapitalFlow_proto_rawDescGZIP(), []int{1}
}

func (x *CapitalFlowItem) GetInFlow() float64 {
	if x != nil && x.InFlow != nil {
		return *x.InFlow
	}
	return 0
}

func (x *CapitalFlowItem) GetTime() string {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return ""
}

func (x *CapitalFlowItem) GetTimestamp() float64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *CapitalFlowItem) GetMainInFlow() float64 {
	if x != nil && x.MainInFlow != nil {
		return *x.MainInFlow
	}
	return 0
}

func (x *CapitalFlowItem) GetSuperInFlow() float64 {
	if x != nil && x.SuperInFlow != nil {
		return *x.SuperInFlow
	}
	return 0
}

func (x *CapitalFlowItem) GetBigInFlow() float64 {
	if x != nil && x.BigInFlow != nil {
		return *x.BigInFlow
	}
	return 0
}

func (x *CapitalFlowItem) GetMidInFlow() float64 {
	if x != nil && x.MidInFlow != nil {
		return *x.MidInFlow
	}
	return 0
}

func (x *CapitalFlowItem) GetSmlInFlow() float64 {
	if x != nil && x.SmlInFlow != nil {
		return *x.SmlInFlow
	}
	return 0
}

type S2C struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FlowItemList       []*CapitalFlowItem     `protobuf:"bytes,1,rep,name=flowItemList" json:"flowItemList,omitempty"`               //资金流向
	LastValidTime      *string                `protobuf:"bytes,2,opt,name=lastValidTime" json:"lastValidTime,omitempty"`             //数据最后有效时间字符串
	LastValidTimestamp *float64               `protobuf:"fixed64,3,opt,name=lastValidTimestamp" json:"lastValidTimestamp,omitempty"` //数据最后有效时间戳
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetCapitalFlow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCapitalFlow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetCapitalFlow_proto_rawDescGZIP(), []int{2}
}

func (x *S2C) GetFlowItemList() []*CapitalFlowItem {
	if x != nil {
		return x.FlowItemList
	}
	return nil
}

func (x *S2C) GetLastValidTime() string {
	if x != nil && x.LastValidTime != nil {
		return *x.LastValidTime
	}
	return ""
}

func (x *S2C) GetLastValidTimestamp() float64 {
	if x != nil && x.LastValidTimestamp != nil {
		return *x.LastValidTimestamp
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetCapitalFlow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCapitalFlow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetCapitalFlow_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetCapitalFlow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetCapitalFlow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetCapitalFlow_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetCapitalFlow_proto protoreflect.FileDescriptor

const file_Qot_GetCapitalFlow_proto_rawDesc = "" +
	"\n" +
	"\x18Qot_GetCapitalFlow.proto\x12\x12Qot_GetCapitalFlow\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"\x8f\x01\n" +
	"\x03C2S\x120\n" +
	"\bsecurity\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\bsecurity\x12\x1e\n" +
	"\n" +
	"periodType\x18\x02 \x01(\x05R\n" +
	"periodType\x12\x1c\n" +
	"\tbeginTime\x18\x03 \x01(\tR\tbeginTime\x12\x18\n" +
	"\aendTime\x18\x04 \x01(\tR\aendTime\"\xf7\x01\n" +
	"\x0fCapitalFlowItem\x12\x16\n" +
	"\x06inFlow\x18\x01 \x02(\x01R\x06inFlow\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x01R\ttimestamp\x12\x1e\n" +
	"\n" +
	"mainInFlow\x18\x04 \x01(\x01R\n" +
	"mainInFlow\x12 \n" +
	"\vsuperInFlow\x18\x05 \x01(\x01R\vsuperInFlow\x12\x1c\n" +
	"\tbigInFlow\x18\x06 \x01(\x01R\tbigInFlow\x12\x1c\n" +
	"\tmidInFlow\x18\a \x01(\x01R\tmidInFlow\x12\x1c\n" +
	"\tsmlInFlow\x18\b \x01(\x01R\tsmlInFlow\"\xa4\x01\n" +
	"\x03S2C\x12G\n" +
	"\fflowItemList\x18\x01 \x03(\v2#.Qot_GetCapitalFlow.CapitalFlowItemR\fflowItemList\x12$\n" +
	"\rlastValidTime\x18\x02 \x01(\tR\rlastValidTime\x12.\n" +
	"\x12lastValidTimestamp\x18\x03 \x01(\x01R\x12lastValidTimestamp\"4\n" +
	"\aRequest\x12)\n" +
	"\x03c2s\x18\x01 \x02(\v2\x17.Qot_GetCapitalFlow.C2SR\x03c2s\"\x87\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12)\n" +
	"\x03s2c\x18\x04 \x01(\v2\x17.Qot_GetCapitalFlow.S2CR\x03s2cBN\n" +
	"\x13com.futu.openapi.pbZ7github.com/shing1211/futuapi4go/pkg/pb/qotgetcapitalflow"

var (
	file_Qot_GetCapitalFlow_proto_rawDescOnce sync.Once
	file_Qot_GetCapitalFlow_proto_rawDescData []byte
)

func file_Qot_GetCapitalFlow_proto_rawDescGZIP() []byte {
	file_Qot_GetCapitalFlow_proto_rawDescOnce.Do(func() {
		file_Qot_GetCapitalFlow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetCapitalFlow_proto_rawDesc), len(file_Qot_GetCapitalFlow_proto_rawDesc)))
	})
	return file_Qot_GetCapitalFlow_proto_rawDescData
}

var file_Qot_GetCapitalFlow_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetCapitalFlow_proto_goTypes = []any{
	(*C2S)(nil),                // 0: Qot_GetCapitalFlow.C2S
	(*CapitalFlowItem)(nil),    // 1: Qot_GetCapitalFlow.CapitalFlowItem
	(*S2C)(nil),                // 2: Qot_GetCapitalFlow.S2C
	(*Request)(nil),            // 3: Qot_GetCapitalFlow.Request
	(*Response)(nil),           // 4: Qot_GetCapitalFlow.Response
	(*qotcommon.Security)(nil), // 5: Qot_Common.Security
}
var file_Qot_GetCapitalFlow_proto_depIdxs = []int32{
	5, // 0: Qot_GetCapitalFlow.C2S.security:type_name -> Qot_Common.Security
	1, // 1: Qot_GetCapitalFlow.S2C.flowItemList:type_name -> Qot_GetCapitalFlow.CapitalFlowItem
	0, // 2: Qot_GetCapitalFlow.Request.c2s:type_name -> Qot_GetCapitalFlow.C2S
	2, // 3: Qot_GetCapitalFlow.Response.s2c:type_name -> Qot_GetCapitalFlow.S2C
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Qot_GetCapitalFlow_proto_init() }
func file_Qot_GetCapitalFlow_proto_init() {
	if File_Qot_GetCapitalFlow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetCapitalFlow_proto_rawDesc), len(file_Qot_GetCapitalFlow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetCapitalFlow_proto_goTypes,
		DependencyIndexes: file_Qot_GetCapitalFlow_proto_depIdxs,
		MessageInfos:      file_Qot_GetCapitalFlow_proto_msgTypes,
	}.Build()
	File_Qot_GetCapitalFlow_proto = out.File
	file_Qot_GetCapitalFlow_proto_goTypes = nil
	file_Qot_GetCapitalFlow_proto_depIdxs = nil
}
