// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: Qot_GetSubInfo.proto

package qotgetsubinfo

import (
	_ "gitee.com/shing1211/futuapi4go/pkg/pb/common"
	qotcommon "gitee.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReqAllConn  *bool                  `protobuf:"varint,1,opt,name=isReqAllConn" json:"isReqAllConn,omitempty"` //是否返回所有连接的订阅状态,不传或者传false只返回当前连接数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetSubInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetSubInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetSubInfo_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetIsReqAllConn() bool {
	if x != nil && x.IsReqAllConn != nil {
		return *x.IsReqAllConn
	}
	return false
}

type S2C struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ConnSubInfoList []*qotcommon.ConnSubInfo `protobuf:"bytes,1,rep,name=connSubInfoList" json:"connSubInfoList,omitempty"` //订阅订阅信息
	TotalUsedQuota  *int32                   `protobuf:"varint,2,req,name=totalUsedQuota" json:"totalUsedQuota,omitempty"`  //FutuOpenD已使用的订阅额度
	RemainQuota     *int32                   `protobuf:"varint,3,req,name=remainQuota" json:"remainQuota,omitempty"`        //FutuOpenD剩余订阅额度
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetSubInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetSubInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetSubInfo_proto_rawDescGZIP(), []int{1}
}

func (x *S2C) GetConnSubInfoList() []*qotcommon.ConnSubInfo {
	if x != nil {
		return x.ConnSubInfoList
	}
	return nil
}

func (x *S2C) GetTotalUsedQuota() int32 {
	if x != nil && x.TotalUsedQuota != nil {
		return *x.TotalUsedQuota
	}
	return 0
}

func (x *S2C) GetRemainQuota() int32 {
	if x != nil && x.RemainQuota != nil {
		return *x.RemainQuota
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetSubInfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetSubInfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetSubInfo_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetSubInfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetSubInfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetSubInfo_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetSubInfo_proto protoreflect.FileDescriptor

const file_Qot_GetSubInfo_proto_rawDesc = "" +
	"\n" +
	"\x14Qot_GetSubInfo.proto\x12\x0eQot_GetSubInfo\x1a\fCommon.proto\x1a\x10Qot_Common.proto\")\n" +
	"\x03C2S\x12\"\n" +
	"\fisReqAllConn\x18\x01 \x01(\bR\fisReqAllConn\"\x92\x01\n" +
	"\x03S2C\x12A\n" +
	"\x0fconnSubInfoList\x18\x01 \x03(\v2\x17.Qot_Common.ConnSubInfoR\x0fconnSubInfoList\x12&\n" +
	"\x0etotalUsedQuota\x18\x02 \x02(\x05R\x0etotalUsedQuota\x12 \n" +
	"\vremainQuota\x18\x03 \x02(\x05R\vremainQuota\"0\n" +
	"\aRequest\x12%\n" +
	"\x03c2s\x18\x01 \x02(\v2\x13.Qot_GetSubInfo.C2SR\x03c2s\"\x83\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12%\n" +
	"\x03s2c\x18\x04 \x01(\v2\x13.Qot_GetSubInfo.S2CR\x03s2cBJ\n" +
	"\x13com.futu.openapi.pbZ3gitee.com/shing1211/futuapi4go/pkg/pb/qotgetsubinfo"

var (
	file_Qot_GetSubInfo_proto_rawDescOnce sync.Once
	file_Qot_GetSubInfo_proto_rawDescData []byte
)

func file_Qot_GetSubInfo_proto_rawDescGZIP() []byte {
	file_Qot_GetSubInfo_proto_rawDescOnce.Do(func() {
		file_Qot_GetSubInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetSubInfo_proto_rawDesc), len(file_Qot_GetSubInfo_proto_rawDesc)))
	})
	return file_Qot_GetSubInfo_proto_rawDescData
}

var file_Qot_GetSubInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Qot_GetSubInfo_proto_goTypes = []any{
	(*C2S)(nil),                   // 0: Qot_GetSubInfo.C2S
	(*S2C)(nil),                   // 1: Qot_GetSubInfo.S2C
	(*Request)(nil),               // 2: Qot_GetSubInfo.Request
	(*Response)(nil),              // 3: Qot_GetSubInfo.Response
	(*qotcommon.ConnSubInfo)(nil), // 4: Qot_Common.ConnSubInfo
}
var file_Qot_GetSubInfo_proto_depIdxs = []int32{
	4, // 0: Qot_GetSubInfo.S2C.connSubInfoList:type_name -> Qot_Common.ConnSubInfo
	0, // 1: Qot_GetSubInfo.Request.c2s:type_name -> Qot_GetSubInfo.C2S
	1, // 2: Qot_GetSubInfo.Response.s2c:type_name -> Qot_GetSubInfo.S2C
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Qot_GetSubInfo_proto_init() }
func file_Qot_GetSubInfo_proto_init() {
	if File_Qot_GetSubInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetSubInfo_proto_rawDesc), len(file_Qot_GetSubInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetSubInfo_proto_goTypes,
		DependencyIndexes: file_Qot_GetSubInfo_proto_depIdxs,
		MessageInfos:      file_Qot_GetSubInfo_proto_msgTypes,
	}.Build()
	File_Qot_GetSubInfo_proto = out.File
	file_Qot_GetSubInfo_proto_goTypes = nil
	file_Qot_GetSubInfo_proto_depIdxs = nil
}
