// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: Qot_SetPriceReminder.proto

package qotsetpricereminder

import (
	_ "gitee.com/shing1211/futuapi4go/pkg/pb/common"
	qotcommon "gitee.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetPriceReminderOp int32

const (
	SetPriceReminderOp_SetPriceReminderOp_Unknown SetPriceReminderOp = 0
	SetPriceReminderOp_SetPriceReminderOp_Add     SetPriceReminderOp = 1 //新增
	SetPriceReminderOp_SetPriceReminderOp_Del     SetPriceReminderOp = 2 //删除
	SetPriceReminderOp_SetPriceReminderOp_Enable  SetPriceReminderOp = 3 //启用
	SetPriceReminderOp_SetPriceReminderOp_Disable SetPriceReminderOp = 4 //禁用
	SetPriceReminderOp_SetPriceReminderOp_Modify  SetPriceReminderOp = 5 //修改
	SetPriceReminderOp_SetPriceReminderOp_DelAll  SetPriceReminderOp = 6 //删除该支股票下所有到价提醒
)

// Enum value maps for SetPriceReminderOp.
var (
	SetPriceReminderOp_name = map[int32]string{
		0: "SetPriceReminderOp_Unknown",
		1: "SetPriceReminderOp_Add",
		2: "SetPriceReminderOp_Del",
		3: "SetPriceReminderOp_Enable",
		4: "SetPriceReminderOp_Disable",
		5: "SetPriceReminderOp_Modify",
		6: "SetPriceReminderOp_DelAll",
	}
	SetPriceReminderOp_value = map[string]int32{
		"SetPriceReminderOp_Unknown": 0,
		"SetPriceReminderOp_Add":     1,
		"SetPriceReminderOp_Del":     2,
		"SetPriceReminderOp_Enable":  3,
		"SetPriceReminderOp_Disable": 4,
		"SetPriceReminderOp_Modify":  5,
		"SetPriceReminderOp_DelAll":  6,
	}
)

func (x SetPriceReminderOp) Enum() *SetPriceReminderOp {
	p := new(SetPriceReminderOp)
	*p = x
	return p
}

func (x SetPriceReminderOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetPriceReminderOp) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_SetPriceReminder_proto_enumTypes[0].Descriptor()
}

func (SetPriceReminderOp) Type() protoreflect.EnumType {
	return &file_Qot_SetPriceReminder_proto_enumTypes[0]
}

func (x SetPriceReminderOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SetPriceReminderOp) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SetPriceReminderOp(num)
	return nil
}

// Deprecated: Use SetPriceReminderOp.Descriptor instead.
func (SetPriceReminderOp) EnumDescriptor() ([]byte, []int) {
	return file_Qot_SetPriceReminder_proto_rawDescGZIP(), []int{0}
}

type C2S struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Security            *qotcommon.Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`                        // 股票
	Op                  *int32                 `protobuf:"varint,2,req,name=op" json:"op,omitempty"`                                   // SetPriceReminderOp，操作类型
	Key                 *int64                 `protobuf:"varint,3,opt,name=key" json:"key,omitempty"`                                 // 到价提醒的标识，GetPriceReminder协议可获得，用于指定要操作的到价提醒项，对于新增的情况不需要填
	Type                *int32                 `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`                               // Qot_Common::PriceReminderType，提醒类型，删除、启用、禁用的情况下会忽略该字段
	Freq                *int32                 `protobuf:"varint,7,opt,name=freq" json:"freq,omitempty"`                               // Qot_Common::PriceReminderFreq，提醒频率类型，删除、启用、禁用的情况下会忽略该字段
	Value               *float64               `protobuf:"fixed64,5,opt,name=value" json:"value,omitempty"`                            // 提醒值，删除、启用、禁用的情况下会忽略该字段（精确到小数点后 3 位，超出部分会被舍弃）
	Note                *string                `protobuf:"bytes,6,opt,name=note" json:"note,omitempty"`                                // 用户设置到价提醒时的标注，仅支持 20 个以内的中文字符，删除、启用、禁用的情况下会忽略该字段
	ReminderSessionList []int32                `protobuf:"varint,8,rep,name=reminderSessionList" json:"reminderSessionList,omitempty"` // 到价提醒的时段列表，删除、启用、禁用的情况下会忽略该入参,枚举参考Qot_Common::PriceReminderMarketStatus
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_SetPriceReminder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_SetPriceReminder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_SetPriceReminder_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *C2S) GetOp() int32 {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return 0
}

func (x *C2S) GetKey() int64 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *C2S) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *C2S) GetFreq() int32 {
	if x != nil && x.Freq != nil {
		return *x.Freq
	}
	return 0
}

func (x *C2S) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *C2S) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *C2S) GetReminderSessionList() []int32 {
	if x != nil {
		return x.ReminderSessionList
	}
	return nil
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *int64                 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"` //设置成功的情况下返回对应的key，不成功返回0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_SetPriceReminder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_SetPriceReminder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_SetPriceReminder_proto_rawDescGZIP(), []int{1}
}

func (x *S2C) GetKey() int64 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_SetPriceReminder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_SetPriceReminder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_SetPriceReminder_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType，返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_SetPriceReminder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_SetPriceReminder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_SetPriceReminder_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_SetPriceReminder_proto protoreflect.FileDescriptor

const file_Qot_SetPriceReminder_proto_rawDesc = "" +
	"\n" +
	"\x1aQot_SetPriceReminder.proto\x12\x14Qot_SetPriceReminder\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"\xdd\x01\n" +
	"\x03C2S\x120\n" +
	"\bsecurity\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\bsecurity\x12\x0e\n" +
	"\x02op\x18\x02 \x02(\x05R\x02op\x12\x10\n" +
	"\x03key\x18\x03 \x01(\x03R\x03key\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x12\n" +
	"\x04freq\x18\a \x01(\x05R\x04freq\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x120\n" +
	"\x13reminderSessionList\x18\b \x03(\x05R\x13reminderSessionList\"\x17\n" +
	"\x03S2C\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\"6\n" +
	"\aRequest\x12+\n" +
	"\x03c2s\x18\x01 \x02(\v2\x19.Qot_SetPriceReminder.C2SR\x03c2s\"\x89\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12+\n" +
	"\x03s2c\x18\x04 \x01(\v2\x19.Qot_SetPriceReminder.S2CR\x03s2c*\xe9\x01\n" +
	"\x12SetPriceReminderOp\x12\x1e\n" +
	"\x1aSetPriceReminderOp_Unknown\x10\x00\x12\x1a\n" +
	"\x16SetPriceReminderOp_Add\x10\x01\x12\x1a\n" +
	"\x16SetPriceReminderOp_Del\x10\x02\x12\x1d\n" +
	"\x19SetPriceReminderOp_Enable\x10\x03\x12\x1e\n" +
	"\x1aSetPriceReminderOp_Disable\x10\x04\x12\x1d\n" +
	"\x19SetPriceReminderOp_Modify\x10\x05\x12\x1d\n" +
	"\x19SetPriceReminderOp_DelAll\x10\x06BP\n" +
	"\x13com.futu.openapi.pbZ9gitee.com/shing1211/futuapi4go/pkg/pb/qotsetpricereminder"

var (
	file_Qot_SetPriceReminder_proto_rawDescOnce sync.Once
	file_Qot_SetPriceReminder_proto_rawDescData []byte
)

func file_Qot_SetPriceReminder_proto_rawDescGZIP() []byte {
	file_Qot_SetPriceReminder_proto_rawDescOnce.Do(func() {
		file_Qot_SetPriceReminder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_SetPriceReminder_proto_rawDesc), len(file_Qot_SetPriceReminder_proto_rawDesc)))
	})
	return file_Qot_SetPriceReminder_proto_rawDescData
}

var file_Qot_SetPriceReminder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Qot_SetPriceReminder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Qot_SetPriceReminder_proto_goTypes = []any{
	(SetPriceReminderOp)(0),    // 0: Qot_SetPriceReminder.SetPriceReminderOp
	(*C2S)(nil),                // 1: Qot_SetPriceReminder.C2S
	(*S2C)(nil),                // 2: Qot_SetPriceReminder.S2C
	(*Request)(nil),            // 3: Qot_SetPriceReminder.Request
	(*Response)(nil),           // 4: Qot_SetPriceReminder.Response
	(*qotcommon.Security)(nil), // 5: Qot_Common.Security
}
var file_Qot_SetPriceReminder_proto_depIdxs = []int32{
	5, // 0: Qot_SetPriceReminder.C2S.security:type_name -> Qot_Common.Security
	1, // 1: Qot_SetPriceReminder.Request.c2s:type_name -> Qot_SetPriceReminder.C2S
	2, // 2: Qot_SetPriceReminder.Response.s2c:type_name -> Qot_SetPriceReminder.S2C
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Qot_SetPriceReminder_proto_init() }
func file_Qot_SetPriceReminder_proto_init() {
	if File_Qot_SetPriceReminder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_SetPriceReminder_proto_rawDesc), len(file_Qot_SetPriceReminder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_SetPriceReminder_proto_goTypes,
		DependencyIndexes: file_Qot_SetPriceReminder_proto_depIdxs,
		EnumInfos:         file_Qot_SetPriceReminder_proto_enumTypes,
		MessageInfos:      file_Qot_SetPriceReminder_proto_msgTypes,
	}.Build()
	File_Qot_SetPriceReminder_proto = out.File
	file_Qot_SetPriceReminder_proto_goTypes = nil
	file_Qot_SetPriceReminder_proto_depIdxs = nil
}
