// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: Qot_GetInstitutionHoldingList.proto

package qotgetinstitutionholdinglist

import (
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 持仓变动类型
type HoldingChangeType int32

const (
	HoldingChangeType_HoldingChangeType_Unknown  HoldingChangeType = 0
	HoldingChangeType_HoldingChangeType_New      HoldingChangeType = 1 // 建仓
	HoldingChangeType_HoldingChangeType_SoldOut  HoldingChangeType = 2 // 清仓
	HoldingChangeType_HoldingChangeType_Increase HoldingChangeType = 3 // 增仓
	HoldingChangeType_HoldingChangeType_Decrease HoldingChangeType = 4 // 减仓
)

// Enum value maps for HoldingChangeType.
var (
	HoldingChangeType_name = map[int32]string{
		0: "HoldingChangeType_Unknown",
		1: "HoldingChangeType_New",
		2: "HoldingChangeType_SoldOut",
		3: "HoldingChangeType_Increase",
		4: "HoldingChangeType_Decrease",
	}
	HoldingChangeType_value = map[string]int32{
		"HoldingChangeType_Unknown":  0,
		"HoldingChangeType_New":      1,
		"HoldingChangeType_SoldOut":  2,
		"HoldingChangeType_Increase": 3,
		"HoldingChangeType_Decrease": 4,
	}
)

func (x HoldingChangeType) Enum() *HoldingChangeType {
	p := new(HoldingChangeType)
	*p = x
	return p
}

func (x HoldingChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HoldingChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetInstitutionHoldingList_proto_enumTypes[0].Descriptor()
}

func (HoldingChangeType) Type() protoreflect.EnumType {
	return &file_Qot_GetInstitutionHoldingList_proto_enumTypes[0]
}

func (x HoldingChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HoldingChangeType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HoldingChangeType(num)
	return nil
}

// Deprecated: Use HoldingChangeType.Descriptor instead.
func (HoldingChangeType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionHoldingList_proto_rawDescGZIP(), []int{0}
}

// 排序字段
type SortField int32

const (
	SortField_SortField_Unknown        SortField = 0 // 默认(持仓市值)
	SortField_SortField_HoldingValue   SortField = 1 // 持仓市值
	SortField_SortField_HoldingPct     SortField = 2 // 持股比例(占股票总市值)
	SortField_SortField_LastHoldingPct SortField = 3 // 上期持股比例
	SortField_SortField_ChangeShares   SortField = 4 // 变动股数
	SortField_SortField_ChangePct      SortField = 5 // 变动比例
	SortField_SortField_PortfolioPct   SortField = 6 // 占机构总仓位比例
	SortField_SortField_Industry       SortField = 7 // 行业
	SortField_SortField_HoldingDate    SortField = 8 // 持仓时间
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0: "SortField_Unknown",
		1: "SortField_HoldingValue",
		2: "SortField_HoldingPct",
		3: "SortField_LastHoldingPct",
		4: "SortField_ChangeShares",
		5: "SortField_ChangePct",
		6: "SortField_PortfolioPct",
		7: "SortField_Industry",
		8: "SortField_HoldingDate",
	}
	SortField_value = map[string]int32{
		"SortField_Unknown":        0,
		"SortField_HoldingValue":   1,
		"SortField_HoldingPct":     2,
		"SortField_LastHoldingPct": 3,
		"SortField_ChangeShares":   4,
		"SortField_ChangePct":      5,
		"SortField_PortfolioPct":   6,
		"SortField_Industry":       7,
		"SortField_HoldingDate":    8,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetInstitutionHoldingList_proto_enumTypes[1].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_Qot_GetInstitutionHoldingList_proto_enumTypes[1]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SortField) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SortField(num)
	return nil
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionHoldingList_proto_rawDescGZIP(), []int{1}
}

// 排序方向
type SortDir int32

const (
	SortDir_SortDir_Descending SortDir = 0 // 降序(默认)
	SortDir_SortDir_Ascending  SortDir = 1 // 升序
)

// Enum value maps for SortDir.
var (
	SortDir_name = map[int32]string{
		0: "SortDir_Descending",
		1: "SortDir_Ascending",
	}
	SortDir_value = map[string]int32{
		"SortDir_Descending": 0,
		"SortDir_Ascending":  1,
	}
)

func (x SortDir) Enum() *SortDir {
	p := new(SortDir)
	*p = x
	return p
}

func (x SortDir) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDir) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetInstitutionHoldingList_proto_enumTypes[2].Descriptor()
}

func (SortDir) Type() protoreflect.EnumType {
	return &file_Qot_GetInstitutionHoldingList_proto_enumTypes[2]
}

func (x SortDir) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SortDir) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SortDir(num)
	return nil
}

// Deprecated: Use SortDir.Descriptor instead.
func (SortDir) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionHoldingList_proto_rawDescGZIP(), []int{2}
}

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *int32                 `protobuf:"varint,1,req,name=market" json:"market,omitempty"`               // Qot_Common.QotMarket
	InstitutionId *int32                 `protobuf:"varint,2,req,name=institutionId" json:"institutionId,omitempty"` // 机构ID
	ChangeType    *int32                 `protobuf:"varint,3,opt,name=changeType" json:"changeType,omitempty"`       // HoldingChangeType, 按变动类型筛选(不传=全部)
	SortField     *int32                 `protobuf:"varint,4,opt,name=sortField" json:"sortField,omitempty"`         // SortField
	SortDir       *int32                 `protobuf:"varint,5,opt,name=sortDir" json:"sortDir,omitempty"`             // SortDir
	Count         *int32                 `protobuf:"varint,6,opt,name=count" json:"count,omitempty"`                 // 条数 [1,200], 默认20
	Page          *string                `protobuf:"bytes,7,opt,name=page" json:"page,omitempty"`                    // 翻页游标, 首次不传
	Keyword       *string                `protobuf:"bytes,8,opt,name=keyword" json:"keyword,omitempty"`              // 搜索关键词(股票名/代码)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetInstitutionHoldingList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetInstitutionHoldingList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionHoldingList_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetMarket() int32 {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return 0
}

func (x *C2S) GetInstitutionId() int32 {
	if x != nil && x.InstitutionId != nil {
		return *x.InstitutionId
	}
	return 0
}

func (x *C2S) GetChangeType() int32 {
	if x != nil && x.ChangeType != nil {
		return *x.ChangeType
	}
	return 0
}

func (x *C2S) GetSortField() int32 {
	if x != nil && x.SortField != nil {
		return *x.SortField
	}
	return 0
}

func (x *C2S) GetSortDir() int32 {
	if x != nil && x.SortDir != nil {
		return *x.SortDir
	}
	return 0
}

func (x *C2S) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *C2S) GetPage() string {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return ""
}

func (x *C2S) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

// 持股列表数据项
type HoldingListItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Security       *qotcommon.Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`               // 股票
	Name           *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`                       // 名称
	IndustryName   *string                `protobuf:"bytes,3,opt,name=industryName" json:"industryName,omitempty"`       // 所属行业
	HoldingValue   *float64               `protobuf:"fixed64,4,opt,name=holdingValue" json:"holdingValue,omitempty"`     // 持股市值
	HoldingPct     *float64               `protobuf:"fixed64,5,opt,name=holdingPct" json:"holdingPct,omitempty"`         // 持股比例-占股票总市值(%)
	LastHoldingPct *float64               `protobuf:"fixed64,6,opt,name=lastHoldingPct" json:"lastHoldingPct,omitempty"` // 上期持股比例(%)
	ChangeShares   *int64                 `protobuf:"varint,7,opt,name=changeShares" json:"changeShares,omitempty"`      // 变动股数
	PortfolioPct   *float64               `protobuf:"fixed64,8,opt,name=portfolioPct" json:"portfolioPct,omitempty"`     // 占机构总仓位比例(%)
	ChangePct      *float64               `protobuf:"fixed64,9,opt,name=changePct" json:"changePct,omitempty"`           // 变动比例(%)
	HoldingDate    *string                `protobuf:"bytes,10,opt,name=holdingDate" json:"holdingDate,omitempty"`        // 持仓时间(yyyy-MM-dd)
	Source         *string                `protobuf:"bytes,11,opt,name=source" json:"source,omitempty"`                  // 披露来源
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HoldingListItem) Reset() {
	*x = HoldingListItem{}
	mi := &file_Qot_GetInstitutionHoldingList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingListItem) ProtoMessage() {}

func (x *HoldingListItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetInstitutionHoldingList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingListItem.ProtoReflect.Descriptor instead.
func (*HoldingListItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionHoldingList_proto_rawDescGZIP(), []int{1}
}

func (x *HoldingListItem) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *HoldingListItem) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *HoldingListItem) GetIndustryName() string {
	if x != nil && x.IndustryName != nil {
		return *x.IndustryName
	}
	return ""
}

func (x *HoldingListItem) GetHoldingValue() float64 {
	if x != nil && x.HoldingValue != nil {
		return *x.HoldingValue
	}
	return 0
}

func (x *HoldingListItem) GetHoldingPct() float64 {
	if x != nil && x.HoldingPct != nil {
		return *x.HoldingPct
	}
	return 0
}

func (x *HoldingListItem) GetLastHoldingPct() float64 {
	if x != nil && x.LastHoldingPct != nil {
		return *x.LastHoldingPct
	}
	return 0
}

func (x *HoldingListItem) GetChangeShares() int64 {
	if x != nil && x.ChangeShares != nil {
		return *x.ChangeShares
	}
	return 0
}

func (x *HoldingListItem) GetPortfolioPct() float64 {
	if x != nil && x.PortfolioPct != nil {
		return *x.PortfolioPct
	}
	return 0
}

func (x *HoldingListItem) GetChangePct() float64 {
	if x != nil && x.ChangePct != nil {
		return *x.ChangePct
	}
	return 0
}

func (x *HoldingListItem) GetHoldingDate() string {
	if x != nil && x.HoldingDate != nil {
		return *x.HoldingDate
	}
	return ""
}

func (x *HoldingListItem) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataList      []*HoldingListItem     `protobuf:"bytes,1,rep,name=dataList" json:"dataList,omitempty"`  // 数据列表
	AllCount      *int32                 `protobuf:"varint,2,opt,name=allCount" json:"allCount,omitempty"` // 总数
	NextPage      *string                `protobuf:"bytes,3,opt,name=nextPage" json:"nextPage,omitempty"`  // 下一页游标, 空=无更多
	Currency      *string                `protobuf:"bytes,4,opt,name=currency" json:"currency,omitempty"`  // 币种
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetInstitutionHoldingList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetInstitutionHoldingList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionHoldingList_proto_rawDescGZIP(), []int{2}
}

func (x *S2C) GetDataList() []*HoldingListItem {
	if x != nil {
		return x.DataList
	}
	return nil
}

func (x *S2C) GetAllCount() int32 {
	if x != nil && x.AllCount != nil {
		return *x.AllCount
	}
	return 0
}

func (x *S2C) GetNextPage() string {
	if x != nil && x.NextPage != nil {
		return *x.NextPage
	}
	return ""
}

func (x *S2C) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetInstitutionHoldingList_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetInstitutionHoldingList_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionHoldingList_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` // RetType, 返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetInstitutionHoldingList_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetInstitutionHoldingList_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionHoldingList_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetInstitutionHoldingList_proto protoreflect.FileDescriptor

const file_Qot_GetInstitutionHoldingList_proto_rawDesc = "" +
	"\n" +
	"#Qot_GetInstitutionHoldingList.proto\x12\x1dQot_GetInstitutionHoldingList\x1a\x10Qot_Common.proto\"\xdf\x01\n" +
	"\x03C2S\x12\x16\n" +
	"\x06market\x18\x01 \x02(\x05R\x06market\x12$\n" +
	"\rinstitutionId\x18\x02 \x02(\x05R\rinstitutionId\x12\x1e\n" +
	"\n" +
	"changeType\x18\x03 \x01(\x05R\n" +
	"changeType\x12\x1c\n" +
	"\tsortField\x18\x04 \x01(\x05R\tsortField\x12\x18\n" +
	"\asortDir\x18\x05 \x01(\x05R\asortDir\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x12\x12\n" +
	"\x04page\x18\a \x01(\tR\x04page\x12\x18\n" +
	"\akeyword\x18\b \x01(\tR\akeyword\"\x87\x03\n" +
	"\x0fHoldingListItem\x120\n" +
	"\bsecurity\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\findustryName\x18\x03 \x01(\tR\findustryName\x12\"\n" +
	"\fholdingValue\x18\x04 \x01(\x01R\fholdingValue\x12\x1e\n" +
	"\n" +
	"holdingPct\x18\x05 \x01(\x01R\n" +
	"holdingPct\x12&\n" +
	"\x0elastHoldingPct\x18\x06 \x01(\x01R\x0elastHoldingPct\x12\"\n" +
	"\fchangeShares\x18\a \x01(\x03R\fchangeShares\x12\"\n" +
	"\fportfolioPct\x18\b \x01(\x01R\fportfolioPct\x12\x1c\n" +
	"\tchangePct\x18\t \x01(\x01R\tchangePct\x12 \n" +
	"\vholdingDate\x18\n" +
	" \x01(\tR\vholdingDate\x12\x16\n" +
	"\x06source\x18\v \x01(\tR\x06source\"\xa5\x01\n" +
	"\x03S2C\x12J\n" +
	"\bdataList\x18\x01 \x03(\v2..Qot_GetInstitutionHoldingList.HoldingListItemR\bdataList\x12\x1a\n" +
	"\ballCount\x18\x02 \x01(\x05R\ballCount\x12\x1a\n" +
	"\bnextPage\x18\x03 \x01(\tR\bnextPage\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"?\n" +
	"\aRequest\x124\n" +
	"\x03c2s\x18\x01 \x02(\v2\".Qot_GetInstitutionHoldingList.C2SR\x03c2s\"\x92\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x124\n" +
	"\x03s2c\x18\x04 \x01(\v2\".Qot_GetInstitutionHoldingList.S2CR\x03s2c*\xac\x01\n" +
	"\x11HoldingChangeType\x12\x1d\n" +
	"\x19HoldingChangeType_Unknown\x10\x00\x12\x19\n" +
	"\x15HoldingChangeType_New\x10\x01\x12\x1d\n" +
	"\x19HoldingChangeType_SoldOut\x10\x02\x12\x1e\n" +
	"\x1aHoldingChangeType_Increase\x10\x03\x12\x1e\n" +
	"\x1aHoldingChangeType_Decrease\x10\x04*\xfa\x01\n" +
	"\tSortField\x12\x15\n" +
	"\x11SortField_Unknown\x10\x00\x12\x1a\n" +
	"\x16SortField_HoldingValue\x10\x01\x12\x18\n" +
	"\x14SortField_HoldingPct\x10\x02\x12\x1c\n" +
	"\x18SortField_LastHoldingPct\x10\x03\x12\x1a\n" +
	"\x16SortField_ChangeShares\x10\x04\x12\x17\n" +
	"\x13SortField_ChangePct\x10\x05\x12\x1a\n" +
	"\x16SortField_PortfolioPct\x10\x06\x12\x16\n" +
	"\x12SortField_Industry\x10\a\x12\x19\n" +
	"\x15SortField_HoldingDate\x10\b*8\n" +
	"\aSortDir\x12\x16\n" +
	"\x12SortDir_Descending\x10\x00\x12\x15\n" +
	"\x11SortDir_Ascending\x10\x01BZ\n" +
	"\x13com.futu.openapi.pbZCgithub.com/shing1211/futuapi4go/pkg/pb/qotgetinstitutionholdinglist"

var (
	file_Qot_GetInstitutionHoldingList_proto_rawDescOnce sync.Once
	file_Qot_GetInstitutionHoldingList_proto_rawDescData []byte
)

func file_Qot_GetInstitutionHoldingList_proto_rawDescGZIP() []byte {
	file_Qot_GetInstitutionHoldingList_proto_rawDescOnce.Do(func() {
		file_Qot_GetInstitutionHoldingList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetInstitutionHoldingList_proto_rawDesc), len(file_Qot_GetInstitutionHoldingList_proto_rawDesc)))
	})
	return file_Qot_GetInstitutionHoldingList_proto_rawDescData
}

var file_Qot_GetInstitutionHoldingList_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Qot_GetInstitutionHoldingList_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetInstitutionHoldingList_proto_goTypes = []any{
	(HoldingChangeType)(0),     // 0: Qot_GetInstitutionHoldingList.HoldingChangeType
	(SortField)(0),             // 1: Qot_GetInstitutionHoldingList.SortField
	(SortDir)(0),               // 2: Qot_GetInstitutionHoldingList.SortDir
	(*C2S)(nil),                // 3: Qot_GetInstitutionHoldingList.C2S
	(*HoldingListItem)(nil),    // 4: Qot_GetInstitutionHoldingList.HoldingListItem
	(*S2C)(nil),                // 5: Qot_GetInstitutionHoldingList.S2C
	(*Request)(nil),            // 6: Qot_GetInstitutionHoldingList.Request
	(*Response)(nil),           // 7: Qot_GetInstitutionHoldingList.Response
	(*qotcommon.Security)(nil), // 8: Qot_Common.Security
}
var file_Qot_GetInstitutionHoldingList_proto_depIdxs = []int32{
	8, // 0: Qot_GetInstitutionHoldingList.HoldingListItem.security:type_name -> Qot_Common.Security
	4, // 1: Qot_GetInstitutionHoldingList.S2C.dataList:type_name -> Qot_GetInstitutionHoldingList.HoldingListItem
	3, // 2: Qot_GetInstitutionHoldingList.Request.c2s:type_name -> Qot_GetInstitutionHoldingList.C2S
	5, // 3: Qot_GetInstitutionHoldingList.Response.s2c:type_name -> Qot_GetInstitutionHoldingList.S2C
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Qot_GetInstitutionHoldingList_proto_init() }
func file_Qot_GetInstitutionHoldingList_proto_init() {
	if File_Qot_GetInstitutionHoldingList_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetInstitutionHoldingList_proto_rawDesc), len(file_Qot_GetInstitutionHoldingList_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetInstitutionHoldingList_proto_goTypes,
		DependencyIndexes: file_Qot_GetInstitutionHoldingList_proto_depIdxs,
		EnumInfos:         file_Qot_GetInstitutionHoldingList_proto_enumTypes,
		MessageInfos:      file_Qot_GetInstitutionHoldingList_proto_msgTypes,
	}.Build()
	File_Qot_GetInstitutionHoldingList_proto = out.File
	file_Qot_GetInstitutionHoldingList_proto_goTypes = nil
	file_Qot_GetInstitutionHoldingList_proto_depIdxs = nil
}
