// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: Qot_UpdateEventContractKline.proto

package qotupdateeventcontractkline

import (
	qotgeteventcontractkline "github.com/shing1211/futuapi4go/pkg/pb/qotgeteventcontractkline"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type S2C struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	KlineList     []*qotgeteventcontractkline.KlineItem `protobuf:"bytes,1,rep,name=klineList" json:"klineList,omitempty"` // K线列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_UpdateEventContractKline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_UpdateEventContractKline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_UpdateEventContractKline_proto_rawDescGZIP(), []int{0}
}

func (x *S2C) GetKlineList() []*qotgeteventcontractkline.KlineItem {
	if x != nil {
		return x.KlineList
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_UpdateEventContractKline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_UpdateEventContractKline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_UpdateEventContractKline_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_UpdateEventContractKline_proto protoreflect.FileDescriptor

const file_Qot_UpdateEventContractKline_proto_rawDesc = "" +
	"\n" +
	"\"Qot_UpdateEventContractKline.proto\x12\x1cQot_UpdateEventContractKline\x1a\x1fQot_GetEventContractKline.proto\"I\n" +
	"\x03S2C\x12B\n" +
	"\tklineList\x18\x01 \x03(\v2$.Qot_GetEventContractKline.KlineItemR\tklineList\"\x91\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x123\n" +
	"\x03s2c\x18\x04 \x01(\v2!.Qot_UpdateEventContractKline.S2CR\x03s2cBY\n" +
	"\x13com.futu.openapi.pbZBgithub.com/shing1211/futuapi4go/pkg/pb/qotupdateeventcontractkline"

var (
	file_Qot_UpdateEventContractKline_proto_rawDescOnce sync.Once
	file_Qot_UpdateEventContractKline_proto_rawDescData []byte
)

func file_Qot_UpdateEventContractKline_proto_rawDescGZIP() []byte {
	file_Qot_UpdateEventContractKline_proto_rawDescOnce.Do(func() {
		file_Qot_UpdateEventContractKline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_UpdateEventContractKline_proto_rawDesc), len(file_Qot_UpdateEventContractKline_proto_rawDesc)))
	})
	return file_Qot_UpdateEventContractKline_proto_rawDescData
}

var file_Qot_UpdateEventContractKline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Qot_UpdateEventContractKline_proto_goTypes = []any{
	(*S2C)(nil),      // 0: Qot_UpdateEventContractKline.S2C
	(*Response)(nil), // 1: Qot_UpdateEventContractKline.Response
	(*qotgeteventcontractkline.KlineItem)(nil), // 2: Qot_GetEventContractKline.KlineItem
}
var file_Qot_UpdateEventContractKline_proto_depIdxs = []int32{
	2, // 0: Qot_UpdateEventContractKline.S2C.klineList:type_name -> Qot_GetEventContractKline.KlineItem
	0, // 1: Qot_UpdateEventContractKline.Response.s2c:type_name -> Qot_UpdateEventContractKline.S2C
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Qot_UpdateEventContractKline_proto_init() }
func file_Qot_UpdateEventContractKline_proto_init() {
	if File_Qot_UpdateEventContractKline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_UpdateEventContractKline_proto_rawDesc), len(file_Qot_UpdateEventContractKline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_UpdateEventContractKline_proto_goTypes,
		DependencyIndexes: file_Qot_UpdateEventContractKline_proto_depIdxs,
		MessageInfos:      file_Qot_UpdateEventContractKline_proto_msgTypes,
	}.Build()
	File_Qot_UpdateEventContractKline_proto = out.File
	file_Qot_UpdateEventContractKline_proto_goTypes = nil
	file_Qot_UpdateEventContractKline_proto_depIdxs = nil
}
