// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: GetGlobalState.proto

package getglobalstate

import (
	common "github.com/shing1211/futuapi4go/pkg/pb/common"
	_ "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *uint64                `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"` //历史原因，目前已废弃，填0即可
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_GetGlobalState_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_GetGlobalState_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_GetGlobalState_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetUserID() uint64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

type S2C struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MarketHK       *int32                 `protobuf:"varint,1,req,name=marketHK" json:"marketHK,omitempty"`              //Qot_Common.QotMarketState,港股主板市场状态
	MarketUS       *int32                 `protobuf:"varint,2,req,name=marketUS" json:"marketUS,omitempty"`              //Qot_Common.QotMarketState,美股Nasdaq市场状态
	MarketSH       *int32                 `protobuf:"varint,3,req,name=marketSH" json:"marketSH,omitempty"`              //Qot_Common.QotMarketState,沪市状态
	MarketSZ       *int32                 `protobuf:"varint,4,req,name=marketSZ" json:"marketSZ,omitempty"`              //Qot_Common.QotMarketState,深市状态
	MarketHKFuture *int32                 `protobuf:"varint,5,req,name=marketHKFuture" json:"marketHKFuture,omitempty"`  //Qot_Common.QotMarketState,港股期货市场状态
	MarketUSFuture *int32                 `protobuf:"varint,15,opt,name=marketUSFuture" json:"marketUSFuture,omitempty"` //Qot_Common.QotMarketState,美国期货市场状态
	MarketSGFuture *int32                 `protobuf:"varint,17,opt,name=marketSGFuture" json:"marketSGFuture,omitempty"` //Qot_Common.QotMarketState,新加坡期货市场状态
	MarketJPFuture *int32                 `protobuf:"varint,18,opt,name=marketJPFuture" json:"marketJPFuture,omitempty"` //Qot_Common.QotMarketState,日本期货市场状态
	QotLogined     *bool                  `protobuf:"varint,6,req,name=qotLogined" json:"qotLogined,omitempty"`          //是否登陆行情服务器
	TrdLogined     *bool                  `protobuf:"varint,7,req,name=trdLogined" json:"trdLogined,omitempty"`          //是否登陆交易服务器
	ServerVer      *int32                 `protobuf:"varint,8,req,name=serverVer" json:"serverVer,omitempty"`            //版本号
	ServerBuildNo  *int32                 `protobuf:"varint,9,req,name=serverBuildNo" json:"serverBuildNo,omitempty"`    //buildNo
	Time           *int64                 `protobuf:"varint,10,req,name=time" json:"time,omitempty"`                     //当前服务器时间
	LocalTime      *float64               `protobuf:"fixed64,11,opt,name=localTime" json:"localTime,omitempty"`          //当前本地时间
	ProgramStatus  *common.ProgramStatus  `protobuf:"bytes,12,opt,name=programStatus" json:"programStatus,omitempty"`    //当前程序状态
	QotSvrIpAddr   *string                `protobuf:"bytes,13,opt,name=qotSvrIpAddr" json:"qotSvrIpAddr,omitempty"`
	TrdSvrIpAddr   *string                `protobuf:"bytes,14,opt,name=trdSvrIpAddr" json:"trdSvrIpAddr,omitempty"`
	ConnID         *uint64                `protobuf:"varint,16,opt,name=connID" json:"connID,omitempty"` //此连接的连接ID，连接的唯一标识
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_GetGlobalState_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_GetGlobalState_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_GetGlobalState_proto_rawDescGZIP(), []int{1}
}

func (x *S2C) GetMarketHK() int32 {
	if x != nil && x.MarketHK != nil {
		return *x.MarketHK
	}
	return 0
}

func (x *S2C) GetMarketUS() int32 {
	if x != nil && x.MarketUS != nil {
		return *x.MarketUS
	}
	return 0
}

func (x *S2C) GetMarketSH() int32 {
	if x != nil && x.MarketSH != nil {
		return *x.MarketSH
	}
	return 0
}

func (x *S2C) GetMarketSZ() int32 {
	if x != nil && x.MarketSZ != nil {
		return *x.MarketSZ
	}
	return 0
}

func (x *S2C) GetMarketHKFuture() int32 {
	if x != nil && x.MarketHKFuture != nil {
		return *x.MarketHKFuture
	}
	return 0
}

func (x *S2C) GetMarketUSFuture() int32 {
	if x != nil && x.MarketUSFuture != nil {
		return *x.MarketUSFuture
	}
	return 0
}

func (x *S2C) GetMarketSGFuture() int32 {
	if x != nil && x.MarketSGFuture != nil {
		return *x.MarketSGFuture
	}
	return 0
}

func (x *S2C) GetMarketJPFuture() int32 {
	if x != nil && x.MarketJPFuture != nil {
		return *x.MarketJPFuture
	}
	return 0
}

func (x *S2C) GetQotLogined() bool {
	if x != nil && x.QotLogined != nil {
		return *x.QotLogined
	}
	return false
}

func (x *S2C) GetTrdLogined() bool {
	if x != nil && x.TrdLogined != nil {
		return *x.TrdLogined
	}
	return false
}

func (x *S2C) GetServerVer() int32 {
	if x != nil && x.ServerVer != nil {
		return *x.ServerVer
	}
	return 0
}

func (x *S2C) GetServerBuildNo() int32 {
	if x != nil && x.ServerBuildNo != nil {
		return *x.ServerBuildNo
	}
	return 0
}

func (x *S2C) GetTime() int64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *S2C) GetLocalTime() float64 {
	if x != nil && x.LocalTime != nil {
		return *x.LocalTime
	}
	return 0
}

func (x *S2C) GetProgramStatus() *common.ProgramStatus {
	if x != nil {
		return x.ProgramStatus
	}
	return nil
}

func (x *S2C) GetQotSvrIpAddr() string {
	if x != nil && x.QotSvrIpAddr != nil {
		return *x.QotSvrIpAddr
	}
	return ""
}

func (x *S2C) GetTrdSvrIpAddr() string {
	if x != nil && x.TrdSvrIpAddr != nil {
		return *x.TrdSvrIpAddr
	}
	return ""
}

func (x *S2C) GetConnID() uint64 {
	if x != nil && x.ConnID != nil {
		return *x.ConnID
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_GetGlobalState_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_GetGlobalState_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_GetGlobalState_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_GetGlobalState_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_GetGlobalState_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_GetGlobalState_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_GetGlobalState_proto protoreflect.FileDescriptor

const file_GetGlobalState_proto_rawDesc = "" +
	"\n" +
	"\x14GetGlobalState.proto\x12\x0eGetGlobalState\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"\x1d\n" +
	"\x03C2S\x12\x16\n" +
	"\x06userID\x18\x01 \x02(\x04R\x06userID\"\xe8\x04\n" +
	"\x03S2C\x12\x1a\n" +
	"\bmarketHK\x18\x01 \x02(\x05R\bmarketHK\x12\x1a\n" +
	"\bmarketUS\x18\x02 \x02(\x05R\bmarketUS\x12\x1a\n" +
	"\bmarketSH\x18\x03 \x02(\x05R\bmarketSH\x12\x1a\n" +
	"\bmarketSZ\x18\x04 \x02(\x05R\bmarketSZ\x12&\n" +
	"\x0emarketHKFuture\x18\x05 \x02(\x05R\x0emarketHKFuture\x12&\n" +
	"\x0emarketUSFuture\x18\x0f \x01(\x05R\x0emarketUSFuture\x12&\n" +
	"\x0emarketSGFuture\x18\x11 \x01(\x05R\x0emarketSGFuture\x12&\n" +
	"\x0emarketJPFuture\x18\x12 \x01(\x05R\x0emarketJPFuture\x12\x1e\n" +
	"\n" +
	"qotLogined\x18\x06 \x02(\bR\n" +
	"qotLogined\x12\x1e\n" +
	"\n" +
	"trdLogined\x18\a \x02(\bR\n" +
	"trdLogined\x12\x1c\n" +
	"\tserverVer\x18\b \x02(\x05R\tserverVer\x12$\n" +
	"\rserverBuildNo\x18\t \x02(\x05R\rserverBuildNo\x12\x12\n" +
	"\x04time\x18\n" +
	" \x02(\x03R\x04time\x12\x1c\n" +
	"\tlocalTime\x18\v \x01(\x01R\tlocalTime\x12;\n" +
	"\rprogramStatus\x18\f \x01(\v2\x15.Common.ProgramStatusR\rprogramStatus\x12\"\n" +
	"\fqotSvrIpAddr\x18\r \x01(\tR\fqotSvrIpAddr\x12\"\n" +
	"\ftrdSvrIpAddr\x18\x0e \x01(\tR\ftrdSvrIpAddr\x12\x16\n" +
	"\x06connID\x18\x10 \x01(\x04R\x06connID\"0\n" +
	"\aRequest\x12%\n" +
	"\x03c2s\x18\x01 \x02(\v2\x13.GetGlobalState.C2SR\x03c2s\"\x83\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12%\n" +
	"\x03s2c\x18\x04 \x01(\v2\x13.GetGlobalState.S2CR\x03s2cBL\n" +
	"\x13com.futu.openapi.pbZ5github.com/shing1211/futuapi4go/pkg/pb/getglobalstate"

var (
	file_GetGlobalState_proto_rawDescOnce sync.Once
	file_GetGlobalState_proto_rawDescData []byte
)

func file_GetGlobalState_proto_rawDescGZIP() []byte {
	file_GetGlobalState_proto_rawDescOnce.Do(func() {
		file_GetGlobalState_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetGlobalState_proto_rawDesc), len(file_GetGlobalState_proto_rawDesc)))
	})
	return file_GetGlobalState_proto_rawDescData
}

var file_GetGlobalState_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_GetGlobalState_proto_goTypes = []any{
	(*C2S)(nil),                  // 0: GetGlobalState.C2S
	(*S2C)(nil),                  // 1: GetGlobalState.S2C
	(*Request)(nil),              // 2: GetGlobalState.Request
	(*Response)(nil),             // 3: GetGlobalState.Response
	(*common.ProgramStatus)(nil), // 4: Common.ProgramStatus
}
var file_GetGlobalState_proto_depIdxs = []int32{
	4, // 0: GetGlobalState.S2C.programStatus:type_name -> Common.ProgramStatus
	0, // 1: GetGlobalState.Request.c2s:type_name -> GetGlobalState.C2S
	1, // 2: GetGlobalState.Response.s2c:type_name -> GetGlobalState.S2C
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GetGlobalState_proto_init() }
func file_GetGlobalState_proto_init() {
	if File_GetGlobalState_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetGlobalState_proto_rawDesc), len(file_GetGlobalState_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetGlobalState_proto_goTypes,
		DependencyIndexes: file_GetGlobalState_proto_depIdxs,
		MessageInfos:      file_GetGlobalState_proto_msgTypes,
	}.Build()
	File_GetGlobalState_proto = out.File
	file_GetGlobalState_proto_goTypes = nil
	file_GetGlobalState_proto_depIdxs = nil
}
