// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: Qot_RegQotPush.proto

package qotregqotpush

import (
	_ "github.com/shing1211/futuapi4go/pkg/pb/common"
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecurityList  []*qotcommon.Security  `protobuf:"bytes,1,rep,name=securityList" json:"securityList,omitempty"`    //股票
	SubTypeList   []int32                `protobuf:"varint,2,rep,name=subTypeList" json:"subTypeList,omitempty"`     //Qot_Common.SubType,要注册到该连接的订阅类型
	RehabTypeList []int32                `protobuf:"varint,3,rep,name=rehabTypeList" json:"rehabTypeList,omitempty"` //Qot_Common.RehabType,复权类型,注册K线类型才生效,其他订阅类型忽略该参数,注册K线时该参数不指定默认前复权
	IsRegOrUnReg  *bool                  `protobuf:"varint,4,req,name=isRegOrUnReg" json:"isRegOrUnReg,omitempty"`   //注册或取消
	IsFirstPush   *bool                  `protobuf:"varint,5,opt,name=isFirstPush" json:"isFirstPush,omitempty"`     //注册后如果本地已有数据是否首推一次已存在数据,该参数不指定则默认true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_RegQotPush_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_RegQotPush_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_RegQotPush_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetSecurityList() []*qotcommon.Security {
	if x != nil {
		return x.SecurityList
	}
	return nil
}

func (x *C2S) GetSubTypeList() []int32 {
	if x != nil {
		return x.SubTypeList
	}
	return nil
}

func (x *C2S) GetRehabTypeList() []int32 {
	if x != nil {
		return x.RehabTypeList
	}
	return nil
}

func (x *C2S) GetIsRegOrUnReg() bool {
	if x != nil && x.IsRegOrUnReg != nil {
		return *x.IsRegOrUnReg
	}
	return false
}

func (x *C2S) GetIsFirstPush() bool {
	if x != nil && x.IsFirstPush != nil {
		return *x.IsFirstPush
	}
	return false
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_RegQotPush_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_RegQotPush_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_RegQotPush_proto_rawDescGZIP(), []int{1}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_RegQotPush_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_RegQotPush_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_RegQotPush_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_RegQotPush_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_RegQotPush_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_RegQotPush_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_RegQotPush_proto protoreflect.FileDescriptor

const file_Qot_RegQotPush_proto_rawDesc = "" +
	"\n" +
	"\x14Qot_RegQotPush.proto\x12\x0eQot_RegQotPush\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"\xcd\x01\n" +
	"\x03C2S\x128\n" +
	"\fsecurityList\x18\x01 \x03(\v2\x14.Qot_Common.SecurityR\fsecurityList\x12 \n" +
	"\vsubTypeList\x18\x02 \x03(\x05R\vsubTypeList\x12$\n" +
	"\rrehabTypeList\x18\x03 \x03(\x05R\rrehabTypeList\x12\"\n" +
	"\fisRegOrUnReg\x18\x04 \x02(\bR\fisRegOrUnReg\x12 \n" +
	"\visFirstPush\x18\x05 \x01(\bR\visFirstPush\"\x05\n" +
	"\x03S2C\"0\n" +
	"\aRequest\x12%\n" +
	"\x03c2s\x18\x01 \x02(\v2\x13.Qot_RegQotPush.C2SR\x03c2s\"\x83\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12%\n" +
	"\x03s2c\x18\x04 \x01(\v2\x13.Qot_RegQotPush.S2CR\x03s2cBJ\n" +
	"\x13com.futu.openapi.pbZ3github.com/shing1211/futuapi4go/pkg/pb/qotregqotpush"

var (
	file_Qot_RegQotPush_proto_rawDescOnce sync.Once
	file_Qot_RegQotPush_proto_rawDescData []byte
)

func file_Qot_RegQotPush_proto_rawDescGZIP() []byte {
	file_Qot_RegQotPush_proto_rawDescOnce.Do(func() {
		file_Qot_RegQotPush_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_RegQotPush_proto_rawDesc), len(file_Qot_RegQotPush_proto_rawDesc)))
	})
	return file_Qot_RegQotPush_proto_rawDescData
}

var file_Qot_RegQotPush_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Qot_RegQotPush_proto_goTypes = []any{
	(*C2S)(nil),                // 0: Qot_RegQotPush.C2S
	(*S2C)(nil),                // 1: Qot_RegQotPush.S2C
	(*Request)(nil),            // 2: Qot_RegQotPush.Request
	(*Response)(nil),           // 3: Qot_RegQotPush.Response
	(*qotcommon.Security)(nil), // 4: Qot_Common.Security
}
var file_Qot_RegQotPush_proto_depIdxs = []int32{
	4, // 0: Qot_RegQotPush.C2S.securityList:type_name -> Qot_Common.Security
	0, // 1: Qot_RegQotPush.Request.c2s:type_name -> Qot_RegQotPush.C2S
	1, // 2: Qot_RegQotPush.Response.s2c:type_name -> Qot_RegQotPush.S2C
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Qot_RegQotPush_proto_init() }
func file_Qot_RegQotPush_proto_init() {
	if File_Qot_RegQotPush_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_RegQotPush_proto_rawDesc), len(file_Qot_RegQotPush_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_RegQotPush_proto_goTypes,
		DependencyIndexes: file_Qot_RegQotPush_proto_depIdxs,
		MessageInfos:      file_Qot_RegQotPush_proto_msgTypes,
	}.Build()
	File_Qot_RegQotPush_proto = out.File
	file_Qot_RegQotPush_proto_goTypes = nil
	file_Qot_RegQotPush_proto_depIdxs = nil
}
