// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: Qot_GetFinancialsStatements.proto

package qotgetfinancialsstatements

import (
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 财报字段结构信息
type FinancialFieldInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldId       *int64                 `protobuf:"varint,1,opt,name=fieldId" json:"fieldId,omitempty"`        // 财务字段 ID
	DisplayName   *string                `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty"` // 字段展示名（当前语言，如"营业收入"）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinancialFieldInfo) Reset() {
	*x = FinancialFieldInfo{}
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialFieldInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialFieldInfo) ProtoMessage() {}

func (x *FinancialFieldInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialFieldInfo.ProtoReflect.Descriptor instead.
func (*FinancialFieldInfo) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsStatements_proto_rawDescGZIP(), []int{0}
}

func (x *FinancialFieldInfo) GetFieldId() int64 {
	if x != nil && x.FieldId != nil {
		return *x.FieldId
	}
	return 0
}

func (x *FinancialFieldInfo) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

// 单条财务数据项
type FinancialItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldId       *int64                 `protobuf:"varint,1,opt,name=fieldId" json:"fieldId,omitempty"` // 财务字段 ID，与 structureList 中 fieldId 对应
	Data          *float64               `protobuf:"fixed64,2,opt,name=data" json:"data,omitempty"`      // 财务数据
	Yoy           *float64               `protobuf:"fixed64,3,opt,name=yoy" json:"yoy,omitempty"`        // 同比（%）
	Qoq           *float64               `protobuf:"fixed64,4,opt,name=qoq" json:"qoq,omitempty"`        // 环比（%）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinancialItem) Reset() {
	*x = FinancialItem{}
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialItem) ProtoMessage() {}

func (x *FinancialItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialItem.ProtoReflect.Descriptor instead.
func (*FinancialItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsStatements_proto_rawDescGZIP(), []int{1}
}

func (x *FinancialItem) GetFieldId() int64 {
	if x != nil && x.FieldId != nil {
		return *x.FieldId
	}
	return 0
}

func (x *FinancialItem) GetData() float64 {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return 0
}

func (x *FinancialItem) GetYoy() float64 {
	if x != nil && x.Yoy != nil {
		return *x.Yoy
	}
	return 0
}

func (x *FinancialItem) GetQoq() float64 {
	if x != nil && x.Qoq != nil {
		return *x.Qoq
	}
	return 0
}

// 财务报表
type FinancialReport struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DateTime            *int64                 `protobuf:"varint,1,opt,name=dateTime" json:"dateTime,omitempty"`                                   // 财报截止日时间戳（秒）
	DateTimeStr         *string                `protobuf:"bytes,2,opt,name=dateTimeStr" json:"dateTimeStr,omitempty"`                              // 财报截止日时间字符串，格式 YYYY-MM-DD，对应市场时区
	FiscalYear          *int32                 `protobuf:"varint,3,opt,name=fiscalYear" json:"fiscalYear,omitempty"`                               // 财务年度，如 2024；0 表示无数据
	FinancialType       *qotcommon.F10Type     `protobuf:"varint,4,opt,name=financialType,enum=Qot_Common.F10Type" json:"financialType,omitempty"` // 财报类型，详见 Qot_Common.F10Type 定义；0 表示未知，下次请求可原样传入
	PeriodText          *string                `protobuf:"bytes,5,opt,name=periodText" json:"periodText,omitempty"`                                // 财报周期，如 "2024/Q3"、"2024/FY"
	ItemList            []*FinancialItem       `protobuf:"bytes,6,rep,name=itemList" json:"itemList,omitempty"`                                    // 财务数据项列表
	CurrencyInfo        *string                `protobuf:"bytes,7,opt,name=currencyInfo" json:"currencyInfo,omitempty"`                            // 货币单位（展示型），如 "人民币"、"美元"
	AccountingStandards *string                `protobuf:"bytes,8,opt,name=accountingStandards" json:"accountingStandards,omitempty"`              // 会计准则，如 "国际会计准则"
	AuditorReport       *string                `protobuf:"bytes,9,opt,name=auditorReport" json:"auditorReport,omitempty"`                          // 审计意见，如 "无保留意见"
	CurrencyCode        *string                `protobuf:"bytes,10,opt,name=currencyCode" json:"currencyCode,omitempty"`                           // 币种代码（ISO 4217），如 "CNY"、"USD"
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FinancialReport) Reset() {
	*x = FinancialReport{}
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialReport) ProtoMessage() {}

func (x *FinancialReport) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialReport.ProtoReflect.Descriptor instead.
func (*FinancialReport) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsStatements_proto_rawDescGZIP(), []int{2}
}

func (x *FinancialReport) GetDateTime() int64 {
	if x != nil && x.DateTime != nil {
		return *x.DateTime
	}
	return 0
}

func (x *FinancialReport) GetDateTimeStr() string {
	if x != nil && x.DateTimeStr != nil {
		return *x.DateTimeStr
	}
	return ""
}

func (x *FinancialReport) GetFiscalYear() int32 {
	if x != nil && x.FiscalYear != nil {
		return *x.FiscalYear
	}
	return 0
}

func (x *FinancialReport) GetFinancialType() qotcommon.F10Type {
	if x != nil && x.FinancialType != nil {
		return *x.FinancialType
	}
	return qotcommon.F10Type(0)
}

func (x *FinancialReport) GetPeriodText() string {
	if x != nil && x.PeriodText != nil {
		return *x.PeriodText
	}
	return ""
}

func (x *FinancialReport) GetItemList() []*FinancialItem {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *FinancialReport) GetCurrencyInfo() string {
	if x != nil && x.CurrencyInfo != nil {
		return *x.CurrencyInfo
	}
	return ""
}

func (x *FinancialReport) GetAccountingStandards() string {
	if x != nil && x.AccountingStandards != nil {
		return *x.AccountingStandards
	}
	return ""
}

func (x *FinancialReport) GetAuditorReport() string {
	if x != nil && x.AuditorReport != nil {
		return *x.AuditorReport
	}
	return ""
}

func (x *FinancialReport) GetCurrencyCode() string {
	if x != nil && x.CurrencyCode != nil {
		return *x.CurrencyCode
	}
	return ""
}

type C2S struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Security      *qotcommon.Security                `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`                                                    // 股票
	StatementType *qotcommon.FinancialStatementsType `protobuf:"varint,2,opt,name=statementType,enum=Qot_Common.FinancialStatementsType" json:"statementType,omitempty"` // 财务报表类型（详见 Qot_Common.FinancialStatementsType 定义），默认利润表（Income=1）
	FinancialType *qotcommon.F10Type                 `protobuf:"varint,3,opt,name=financialType,enum=Qot_Common.F10Type" json:"financialType,omitempty"`                 // 财报类型，详见 Qot_Common.F10Type 定义，支持 0-7, 9-11，默认 10(QuarterlyAnnual)
	CurrencyCode  *string                            `protobuf:"bytes,4,opt,name=currencyCode" json:"currencyCode,omitempty"`                                            // 币种代码（ISO 4217），如 CNY、USD、HKD、SGD、JPY、CAD、AUD；不填返回原始货币数据
	NextKey       *string                            `protobuf:"bytes,5,opt,name=nextKey" json:"nextKey,omitempty"`                                                      // 分页标识，首次不填，续拉时填上次返回的 nextKey；"-1" 表示无更多数据
	Num           *int32                             `protobuf:"varint,6,opt,name=num" json:"num,omitempty"`                                                             // 每页返回数量，默认 10，范围 1~50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsStatements_proto_rawDescGZIP(), []int{3}
}

func (x *C2S) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *C2S) GetStatementType() qotcommon.FinancialStatementsType {
	if x != nil && x.StatementType != nil {
		return *x.StatementType
	}
	return qotcommon.FinancialStatementsType(0)
}

func (x *C2S) GetFinancialType() qotcommon.F10Type {
	if x != nil && x.FinancialType != nil {
		return *x.FinancialType
	}
	return qotcommon.F10Type(0)
}

func (x *C2S) GetCurrencyCode() string {
	if x != nil && x.CurrencyCode != nil {
		return *x.CurrencyCode
	}
	return ""
}

func (x *C2S) GetNextKey() string {
	if x != nil && x.NextKey != nil {
		return *x.NextKey
	}
	return ""
}

func (x *C2S) GetNum() int32 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return 0
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StructureList []*FinancialFieldInfo  `protobuf:"bytes,1,rep,name=structureList" json:"structureList,omitempty"` // 字段结构列表，仅收集返回数据中有的字段
	ReportList    []*FinancialReport     `protobuf:"bytes,2,rep,name=reportList" json:"reportList,omitempty"`       // 财报数据列表，按时间顺序
	NextKey       *string                `protobuf:"bytes,3,opt,name=nextKey" json:"nextKey,omitempty"`             // 分页标识，"-1" 表示无更多数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsStatements_proto_rawDescGZIP(), []int{4}
}

func (x *S2C) GetStructureList() []*FinancialFieldInfo {
	if x != nil {
		return x.StructureList
	}
	return nil
}

func (x *S2C) GetReportList() []*FinancialReport {
	if x != nil {
		return x.ReportList
	}
	return nil
}

func (x *S2C) GetNextKey() string {
	if x != nil && x.NextKey != nil {
		return *x.NextKey
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsStatements_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` // RetType，返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsStatements_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsStatements_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetFinancialsStatements_proto protoreflect.FileDescriptor

const file_Qot_GetFinancialsStatements_proto_rawDesc = "" +
	"\n" +
	"!Qot_GetFinancialsStatements.proto\x12\x1bQot_GetFinancialsStatements\x1a\x10Qot_Common.proto\"P\n" +
	"\x12FinancialFieldInfo\x12\x18\n" +
	"\afieldId\x18\x01 \x01(\x03R\afieldId\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\"a\n" +
	"\rFinancialItem\x12\x18\n" +
	"\afieldId\x18\x01 \x01(\x03R\afieldId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\x01R\x04data\x12\x10\n" +
	"\x03yoy\x18\x03 \x01(\x01R\x03yoy\x12\x10\n" +
	"\x03qoq\x18\x04 \x01(\x01R\x03qoq\"\xb2\x03\n" +
	"\x0fFinancialReport\x12\x1a\n" +
	"\bdateTime\x18\x01 \x01(\x03R\bdateTime\x12 \n" +
	"\vdateTimeStr\x18\x02 \x01(\tR\vdateTimeStr\x12\x1e\n" +
	"\n" +
	"fiscalYear\x18\x03 \x01(\x05R\n" +
	"fiscalYear\x129\n" +
	"\rfinancialType\x18\x04 \x01(\x0e2\x13.Qot_Common.F10TypeR\rfinancialType\x12\x1e\n" +
	"\n" +
	"periodText\x18\x05 \x01(\tR\n" +
	"periodText\x12F\n" +
	"\bitemList\x18\x06 \x03(\v2*.Qot_GetFinancialsStatements.FinancialItemR\bitemList\x12\"\n" +
	"\fcurrencyInfo\x18\a \x01(\tR\fcurrencyInfo\x120\n" +
	"\x13accountingStandards\x18\b \x01(\tR\x13accountingStandards\x12$\n" +
	"\rauditorReport\x18\t \x01(\tR\rauditorReport\x12\"\n" +
	"\fcurrencyCode\x18\n" +
	" \x01(\tR\fcurrencyCode\"\x8d\x02\n" +
	"\x03C2S\x120\n" +
	"\bsecurity\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\bsecurity\x12I\n" +
	"\rstatementType\x18\x02 \x01(\x0e2#.Qot_Common.FinancialStatementsTypeR\rstatementType\x129\n" +
	"\rfinancialType\x18\x03 \x01(\x0e2\x13.Qot_Common.F10TypeR\rfinancialType\x12\"\n" +
	"\fcurrencyCode\x18\x04 \x01(\tR\fcurrencyCode\x12\x18\n" +
	"\anextKey\x18\x05 \x01(\tR\anextKey\x12\x10\n" +
	"\x03num\x18\x06 \x01(\x05R\x03num\"\xc4\x01\n" +
	"\x03S2C\x12U\n" +
	"\rstructureList\x18\x01 \x03(\v2/.Qot_GetFinancialsStatements.FinancialFieldInfoR\rstructureList\x12L\n" +
	"\n" +
	"reportList\x18\x02 \x03(\v2,.Qot_GetFinancialsStatements.FinancialReportR\n" +
	"reportList\x12\x18\n" +
	"\anextKey\x18\x03 \x01(\tR\anextKey\"=\n" +
	"\aRequest\x122\n" +
	"\x03c2s\x18\x01 \x02(\v2 .Qot_GetFinancialsStatements.C2SR\x03c2s\"\x90\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x122\n" +
	"\x03s2c\x18\x04 \x01(\v2 .Qot_GetFinancialsStatements.S2CR\x03s2cBX\n" +
	"\x13com.futu.openapi.pbZAgithub.com/shing1211/futuapi4go/pkg/pb/qotgetfinancialsstatements"

var (
	file_Qot_GetFinancialsStatements_proto_rawDescOnce sync.Once
	file_Qot_GetFinancialsStatements_proto_rawDescData []byte
)

func file_Qot_GetFinancialsStatements_proto_rawDescGZIP() []byte {
	file_Qot_GetFinancialsStatements_proto_rawDescOnce.Do(func() {
		file_Qot_GetFinancialsStatements_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetFinancialsStatements_proto_rawDesc), len(file_Qot_GetFinancialsStatements_proto_rawDesc)))
	})
	return file_Qot_GetFinancialsStatements_proto_rawDescData
}

var file_Qot_GetFinancialsStatements_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_Qot_GetFinancialsStatements_proto_goTypes = []any{
	(*FinancialFieldInfo)(nil),             // 0: Qot_GetFinancialsStatements.FinancialFieldInfo
	(*FinancialItem)(nil),                  // 1: Qot_GetFinancialsStatements.FinancialItem
	(*FinancialReport)(nil),                // 2: Qot_GetFinancialsStatements.FinancialReport
	(*C2S)(nil),                            // 3: Qot_GetFinancialsStatements.C2S
	(*S2C)(nil),                            // 4: Qot_GetFinancialsStatements.S2C
	(*Request)(nil),                        // 5: Qot_GetFinancialsStatements.Request
	(*Response)(nil),                       // 6: Qot_GetFinancialsStatements.Response
	(qotcommon.F10Type)(0),                 // 7: Qot_Common.F10Type
	(*qotcommon.Security)(nil),             // 8: Qot_Common.Security
	(qotcommon.FinancialStatementsType)(0), // 9: Qot_Common.FinancialStatementsType
}
var file_Qot_GetFinancialsStatements_proto_depIdxs = []int32{
	7, // 0: Qot_GetFinancialsStatements.FinancialReport.financialType:type_name -> Qot_Common.F10Type
	1, // 1: Qot_GetFinancialsStatements.FinancialReport.itemList:type_name -> Qot_GetFinancialsStatements.FinancialItem
	8, // 2: Qot_GetFinancialsStatements.C2S.security:type_name -> Qot_Common.Security
	9, // 3: Qot_GetFinancialsStatements.C2S.statementType:type_name -> Qot_Common.FinancialStatementsType
	7, // 4: Qot_GetFinancialsStatements.C2S.financialType:type_name -> Qot_Common.F10Type
	0, // 5: Qot_GetFinancialsStatements.S2C.structureList:type_name -> Qot_GetFinancialsStatements.FinancialFieldInfo
	2, // 6: Qot_GetFinancialsStatements.S2C.reportList:type_name -> Qot_GetFinancialsStatements.FinancialReport
	3, // 7: Qot_GetFinancialsStatements.Request.c2s:type_name -> Qot_GetFinancialsStatements.C2S
	4, // 8: Qot_GetFinancialsStatements.Response.s2c:type_name -> Qot_GetFinancialsStatements.S2C
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_Qot_GetFinancialsStatements_proto_init() }
func file_Qot_GetFinancialsStatements_proto_init() {
	if File_Qot_GetFinancialsStatements_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetFinancialsStatements_proto_rawDesc), len(file_Qot_GetFinancialsStatements_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetFinancialsStatements_proto_goTypes,
		DependencyIndexes: file_Qot_GetFinancialsStatements_proto_depIdxs,
		MessageInfos:      file_Qot_GetFinancialsStatements_proto_msgTypes,
	}.Build()
	File_Qot_GetFinancialsStatements_proto = out.File
	file_Qot_GetFinancialsStatements_proto_goTypes = nil
	file_Qot_GetFinancialsStatements_proto_depIdxs = nil
}
