// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: Qot_GetInstitutionList.proto

package qotgetinstitutionlist

import (
	_ "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 排序字段
type SortField int32

const (
	SortField_SortField_Unknown             SortField = 0 // 默认(持仓市值)
	SortField_SortField_PositionValue       SortField = 1 // 持仓市值
	SortField_SortField_PositionValueChange SortField = 2 // 增减仓
	SortField_SortField_PositionCount       SortField = 3 // 持仓股数
	SortField_SortField_PositionCountChange SortField = 4 // 持仓股数变化
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0: "SortField_Unknown",
		1: "SortField_PositionValue",
		2: "SortField_PositionValueChange",
		3: "SortField_PositionCount",
		4: "SortField_PositionCountChange",
	}
	SortField_value = map[string]int32{
		"SortField_Unknown":             0,
		"SortField_PositionValue":       1,
		"SortField_PositionValueChange": 2,
		"SortField_PositionCount":       3,
		"SortField_PositionCountChange": 4,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetInstitutionList_proto_enumTypes[0].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_Qot_GetInstitutionList_proto_enumTypes[0]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SortField) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SortField(num)
	return nil
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionList_proto_rawDescGZIP(), []int{0}
}

// 排序方向
type SortDir int32

const (
	SortDir_SortDir_Descending SortDir = 0 // 降序(默认)
	SortDir_SortDir_Ascending  SortDir = 1 // 升序
)

// Enum value maps for SortDir.
var (
	SortDir_name = map[int32]string{
		0: "SortDir_Descending",
		1: "SortDir_Ascending",
	}
	SortDir_value = map[string]int32{
		"SortDir_Descending": 0,
		"SortDir_Ascending":  1,
	}
)

func (x SortDir) Enum() *SortDir {
	p := new(SortDir)
	*p = x
	return p
}

func (x SortDir) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDir) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetInstitutionList_proto_enumTypes[1].Descriptor()
}

func (SortDir) Type() protoreflect.EnumType {
	return &file_Qot_GetInstitutionList_proto_enumTypes[1]
}

func (x SortDir) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SortDir) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SortDir(num)
	return nil
}

// Deprecated: Use SortDir.Descriptor instead.
func (SortDir) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionList_proto_rawDescGZIP(), []int{1}
}

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *int32                 `protobuf:"varint,1,req,name=market" json:"market,omitempty"`       // Qot_Common.QotMarket
	SortField     *int32                 `protobuf:"varint,2,opt,name=sortField" json:"sortField,omitempty"` // SortField, 默认持仓市值
	SortDir       *int32                 `protobuf:"varint,3,opt,name=sortDir" json:"sortDir,omitempty"`     // SortDir, 默认降序
	Count         *int32                 `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`         // 条数 [1,200], 默认20
	Page          *string                `protobuf:"bytes,5,opt,name=page" json:"page,omitempty"`            // 翻页游标, 首次不传, 续页传S2C返回的nextPage
	NamePart      *string                `protobuf:"bytes,6,opt,name=namePart" json:"namePart,omitempty"`    // 机构名模糊搜索
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetInstitutionList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetInstitutionList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionList_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetMarket() int32 {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return 0
}

func (x *C2S) GetSortField() int32 {
	if x != nil && x.SortField != nil {
		return *x.SortField
	}
	return 0
}

func (x *C2S) GetSortDir() int32 {
	if x != nil && x.SortDir != nil {
		return *x.SortDir
	}
	return 0
}

func (x *C2S) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *C2S) GetPage() string {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return ""
}

func (x *C2S) GetNamePart() string {
	if x != nil && x.NamePart != nil {
		return *x.NamePart
	}
	return ""
}

// 机构列表数据项
type InstitutionListItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InstitutionId       *int32                 `protobuf:"varint,1,req,name=institutionId" json:"institutionId,omitempty"`              // 机构ID
	InstitutionName     *string                `protobuf:"bytes,2,opt,name=institutionName" json:"institutionName,omitempty"`           // 机构名称
	PositionValue       *float64               `protobuf:"fixed64,3,opt,name=positionValue" json:"positionValue,omitempty"`             // 持仓市值
	PositionValueChange *float64               `protobuf:"fixed64,4,opt,name=positionValueChange" json:"positionValueChange,omitempty"` // 持仓市值变化
	PositionCount       *int32                 `protobuf:"varint,5,opt,name=positionCount" json:"positionCount,omitempty"`              // 持仓股票数
	PositionCountChange *int32                 `protobuf:"varint,6,opt,name=positionCountChange" json:"positionCountChange,omitempty"`  // 持仓股票数变化
	DisclosureDate      *string                `protobuf:"bytes,7,opt,name=disclosureDate" json:"disclosureDate,omitempty"`             // 披露日期(yyyy-MM-dd)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InstitutionListItem) Reset() {
	*x = InstitutionListItem{}
	mi := &file_Qot_GetInstitutionList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstitutionListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstitutionListItem) ProtoMessage() {}

func (x *InstitutionListItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetInstitutionList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstitutionListItem.ProtoReflect.Descriptor instead.
func (*InstitutionListItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionList_proto_rawDescGZIP(), []int{1}
}

func (x *InstitutionListItem) GetInstitutionId() int32 {
	if x != nil && x.InstitutionId != nil {
		return *x.InstitutionId
	}
	return 0
}

func (x *InstitutionListItem) GetInstitutionName() string {
	if x != nil && x.InstitutionName != nil {
		return *x.InstitutionName
	}
	return ""
}

func (x *InstitutionListItem) GetPositionValue() float64 {
	if x != nil && x.PositionValue != nil {
		return *x.PositionValue
	}
	return 0
}

func (x *InstitutionListItem) GetPositionValueChange() float64 {
	if x != nil && x.PositionValueChange != nil {
		return *x.PositionValueChange
	}
	return 0
}

func (x *InstitutionListItem) GetPositionCount() int32 {
	if x != nil && x.PositionCount != nil {
		return *x.PositionCount
	}
	return 0
}

func (x *InstitutionListItem) GetPositionCountChange() int32 {
	if x != nil && x.PositionCountChange != nil {
		return *x.PositionCountChange
	}
	return 0
}

func (x *InstitutionListItem) GetDisclosureDate() string {
	if x != nil && x.DisclosureDate != nil {
		return *x.DisclosureDate
	}
	return ""
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataList      []*InstitutionListItem `protobuf:"bytes,1,rep,name=dataList" json:"dataList,omitempty"`  // 数据列表
	AllCount      *int32                 `protobuf:"varint,2,opt,name=allCount" json:"allCount,omitempty"` // 总数
	NextPage      *string                `protobuf:"bytes,3,opt,name=nextPage" json:"nextPage,omitempty"`  // 下一页游标, 空=无更多
	Currency      *string                `protobuf:"bytes,4,opt,name=currency" json:"currency,omitempty"`  // 币种
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetInstitutionList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetInstitutionList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionList_proto_rawDescGZIP(), []int{2}
}

func (x *S2C) GetDataList() []*InstitutionListItem {
	if x != nil {
		return x.DataList
	}
	return nil
}

func (x *S2C) GetAllCount() int32 {
	if x != nil && x.AllCount != nil {
		return *x.AllCount
	}
	return 0
}

func (x *S2C) GetNextPage() string {
	if x != nil && x.NextPage != nil {
		return *x.NextPage
	}
	return ""
}

func (x *S2C) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetInstitutionList_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetInstitutionList_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionList_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` // RetType, 返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetInstitutionList_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetInstitutionList_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetInstitutionList_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetInstitutionList_proto protoreflect.FileDescriptor

const file_Qot_GetInstitutionList_proto_rawDesc = "" +
	"\n" +
	"\x1cQot_GetInstitutionList.proto\x12\x16Qot_GetInstitutionList\x1a\x10Qot_Common.proto\"\x9b\x01\n" +
	"\x03C2S\x12\x16\n" +
	"\x06market\x18\x01 \x02(\x05R\x06market\x12\x1c\n" +
	"\tsortField\x18\x02 \x01(\x05R\tsortField\x12\x18\n" +
	"\asortDir\x18\x03 \x01(\x05R\asortDir\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x12\n" +
	"\x04page\x18\x05 \x01(\tR\x04page\x12\x1a\n" +
	"\bnamePart\x18\x06 \x01(\tR\bnamePart\"\xbd\x02\n" +
	"\x13InstitutionListItem\x12$\n" +
	"\rinstitutionId\x18\x01 \x02(\x05R\rinstitutionId\x12(\n" +
	"\x0finstitutionName\x18\x02 \x01(\tR\x0finstitutionName\x12$\n" +
	"\rpositionValue\x18\x03 \x01(\x01R\rpositionValue\x120\n" +
	"\x13positionValueChange\x18\x04 \x01(\x01R\x13positionValueChange\x12$\n" +
	"\rpositionCount\x18\x05 \x01(\x05R\rpositionCount\x120\n" +
	"\x13positionCountChange\x18\x06 \x01(\x05R\x13positionCountChange\x12&\n" +
	"\x0edisclosureDate\x18\a \x01(\tR\x0edisclosureDate\"\xa2\x01\n" +
	"\x03S2C\x12G\n" +
	"\bdataList\x18\x01 \x03(\v2+.Qot_GetInstitutionList.InstitutionListItemR\bdataList\x12\x1a\n" +
	"\ballCount\x18\x02 \x01(\x05R\ballCount\x12\x1a\n" +
	"\bnextPage\x18\x03 \x01(\tR\bnextPage\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"8\n" +
	"\aRequest\x12-\n" +
	"\x03c2s\x18\x01 \x02(\v2\x1b.Qot_GetInstitutionList.C2SR\x03c2s\"\x8b\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12-\n" +
	"\x03s2c\x18\x04 \x01(\v2\x1b.Qot_GetInstitutionList.S2CR\x03s2c*\xa2\x01\n" +
	"\tSortField\x12\x15\n" +
	"\x11SortField_Unknown\x10\x00\x12\x1b\n" +
	"\x17SortField_PositionValue\x10\x01\x12!\n" +
	"\x1dSortField_PositionValueChange\x10\x02\x12\x1b\n" +
	"\x17SortField_PositionCount\x10\x03\x12!\n" +
	"\x1dSortField_PositionCountChange\x10\x04*8\n" +
	"\aSortDir\x12\x16\n" +
	"\x12SortDir_Descending\x10\x00\x12\x15\n" +
	"\x11SortDir_Ascending\x10\x01BS\n" +
	"\x13com.futu.openapi.pbZ<github.com/shing1211/futuapi4go/pkg/pb/qotgetinstitutionlist"

var (
	file_Qot_GetInstitutionList_proto_rawDescOnce sync.Once
	file_Qot_GetInstitutionList_proto_rawDescData []byte
)

func file_Qot_GetInstitutionList_proto_rawDescGZIP() []byte {
	file_Qot_GetInstitutionList_proto_rawDescOnce.Do(func() {
		file_Qot_GetInstitutionList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetInstitutionList_proto_rawDesc), len(file_Qot_GetInstitutionList_proto_rawDesc)))
	})
	return file_Qot_GetInstitutionList_proto_rawDescData
}

var file_Qot_GetInstitutionList_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Qot_GetInstitutionList_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetInstitutionList_proto_goTypes = []any{
	(SortField)(0),              // 0: Qot_GetInstitutionList.SortField
	(SortDir)(0),                // 1: Qot_GetInstitutionList.SortDir
	(*C2S)(nil),                 // 2: Qot_GetInstitutionList.C2S
	(*InstitutionListItem)(nil), // 3: Qot_GetInstitutionList.InstitutionListItem
	(*S2C)(nil),                 // 4: Qot_GetInstitutionList.S2C
	(*Request)(nil),             // 5: Qot_GetInstitutionList.Request
	(*Response)(nil),            // 6: Qot_GetInstitutionList.Response
}
var file_Qot_GetInstitutionList_proto_depIdxs = []int32{
	3, // 0: Qot_GetInstitutionList.S2C.dataList:type_name -> Qot_GetInstitutionList.InstitutionListItem
	2, // 1: Qot_GetInstitutionList.Request.c2s:type_name -> Qot_GetInstitutionList.C2S
	4, // 2: Qot_GetInstitutionList.Response.s2c:type_name -> Qot_GetInstitutionList.S2C
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Qot_GetInstitutionList_proto_init() }
func file_Qot_GetInstitutionList_proto_init() {
	if File_Qot_GetInstitutionList_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetInstitutionList_proto_rawDesc), len(file_Qot_GetInstitutionList_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetInstitutionList_proto_goTypes,
		DependencyIndexes: file_Qot_GetInstitutionList_proto_depIdxs,
		EnumInfos:         file_Qot_GetInstitutionList_proto_enumTypes,
		MessageInfos:      file_Qot_GetInstitutionList_proto_msgTypes,
	}.Build()
	File_Qot_GetInstitutionList_proto = out.File
	file_Qot_GetInstitutionList_proto_goTypes = nil
	file_Qot_GetInstitutionList_proto_depIdxs = nil
}
