// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: Qot_GetEventContractMilestoneList.proto

package qotgeteventcontractmilestonelist

import (
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 里程碑项
type MilestoneItem struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	MilestoneSecurity    *qotcommon.Security         `protobuf:"bytes,1,req,name=milestoneSecurity" json:"milestoneSecurity,omitempty"`         // 里程碑标的
	Title                *string                     `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`                                 // 里程碑名称（多语言）
	Category             *string                     `protobuf:"bytes,3,opt,name=category" json:"category,omitempty"`                           // 一级分类标识
	Type                 *qotcommon.EC_MilestoneType `protobuf:"varint,4,opt,name=type,enum=Qot_Common.EC_MilestoneType" json:"type,omitempty"` // 里程碑类型
	StartDate            *string                     `protobuf:"bytes,5,opt,name=startDate" json:"startDate,omitempty"`                         // 开始时间（UTC ISO8601，形如 2025-09-26T18:30:00Z）
	EndDate              *string                     `protobuf:"bytes,6,opt,name=endDate" json:"endDate,omitempty"`                             // 结束时间（UTC ISO8601，形如 2025-09-26T18:30:00Z）
	PrimaryEventSecurity *qotcommon.Security         `protobuf:"bytes,7,opt,name=primaryEventSecurity" json:"primaryEventSecurity,omitempty"`   // 主事件标的
	RelatedEventList     []*qotcommon.Security       `protobuf:"bytes,8,rep,name=relatedEventList" json:"relatedEventList,omitempty"`           // 关联事件标的列表
	NotificationMessage  *string                     `protobuf:"bytes,9,opt,name=notificationMessage" json:"notificationMessage,omitempty"`     // 通知消息（多语言）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MilestoneItem) Reset() {
	*x = MilestoneItem{}
	mi := &file_Qot_GetEventContractMilestoneList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MilestoneItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestoneItem) ProtoMessage() {}

func (x *MilestoneItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEventContractMilestoneList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestoneItem.ProtoReflect.Descriptor instead.
func (*MilestoneItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetEventContractMilestoneList_proto_rawDescGZIP(), []int{0}
}

func (x *MilestoneItem) GetMilestoneSecurity() *qotcommon.Security {
	if x != nil {
		return x.MilestoneSecurity
	}
	return nil
}

func (x *MilestoneItem) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *MilestoneItem) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *MilestoneItem) GetType() qotcommon.EC_MilestoneType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return qotcommon.EC_MilestoneType(0)
}

func (x *MilestoneItem) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *MilestoneItem) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *MilestoneItem) GetPrimaryEventSecurity() *qotcommon.Security {
	if x != nil {
		return x.PrimaryEventSecurity
	}
	return nil
}

func (x *MilestoneItem) GetRelatedEventList() []*qotcommon.Security {
	if x != nil {
		return x.RelatedEventList
	}
	return nil
}

func (x *MilestoneItem) GetNotificationMessage() string {
	if x != nil && x.NotificationMessage != nil {
		return *x.NotificationMessage
	}
	return ""
}

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *string                `protobuf:"bytes,1,opt,name=category" json:"category,omitempty"`         // 一级分类 ("SPORTS")
	Competition   *string                `protobuf:"bytes,2,opt,name=competition" json:"competition,omitempty"`   // 赛事标识
	RelatedEvent  *qotcommon.Security    `protobuf:"bytes,3,opt,name=relatedEvent" json:"relatedEvent,omitempty"` // 关联事件标的，本地过滤
	NextPage      *string                `protobuf:"bytes,4,opt,name=nextPage" json:"nextPage,omitempty"`         // 翻页标记（首页不填）
	Count         *int32                 `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`              // 单页最大返回数（默认200）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetEventContractMilestoneList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEventContractMilestoneList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetEventContractMilestoneList_proto_rawDescGZIP(), []int{1}
}

func (x *C2S) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *C2S) GetCompetition() string {
	if x != nil && x.Competition != nil {
		return *x.Competition
	}
	return ""
}

func (x *C2S) GetRelatedEvent() *qotcommon.Security {
	if x != nil {
		return x.RelatedEvent
	}
	return nil
}

func (x *C2S) GetNextPage() string {
	if x != nil && x.NextPage != nil {
		return *x.NextPage
	}
	return ""
}

func (x *C2S) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MilestoneList []*MilestoneItem       `protobuf:"bytes,1,rep,name=milestoneList" json:"milestoneList,omitempty"`
	NextPage      *string                `protobuf:"bytes,2,opt,name=nextPage" json:"nextPage,omitempty"` // 为空表示没有下一页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetEventContractMilestoneList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEventContractMilestoneList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetEventContractMilestoneList_proto_rawDescGZIP(), []int{2}
}

func (x *S2C) GetMilestoneList() []*MilestoneItem {
	if x != nil {
		return x.MilestoneList
	}
	return nil
}

func (x *S2C) GetNextPage() string {
	if x != nil && x.NextPage != nil {
		return *x.NextPage
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetEventContractMilestoneList_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEventContractMilestoneList_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetEventContractMilestoneList_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetEventContractMilestoneList_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEventContractMilestoneList_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetEventContractMilestoneList_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetEventContractMilestoneList_proto protoreflect.FileDescriptor

const file_Qot_GetEventContractMilestoneList_proto_rawDesc = "" +
	"\n" +
	"'Qot_GetEventContractMilestoneList.proto\x12!Qot_GetEventContractMilestoneList\x1a\x10Qot_Common.proto\"\xad\x03\n" +
	"\rMilestoneItem\x12B\n" +
	"\x11milestoneSecurity\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\x11milestoneSecurity\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x120\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1c.Qot_Common.EC_MilestoneTypeR\x04type\x12\x1c\n" +
	"\tstartDate\x18\x05 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x06 \x01(\tR\aendDate\x12H\n" +
	"\x14primaryEventSecurity\x18\a \x01(\v2\x14.Qot_Common.SecurityR\x14primaryEventSecurity\x12@\n" +
	"\x10relatedEventList\x18\b \x03(\v2\x14.Qot_Common.SecurityR\x10relatedEventList\x120\n" +
	"\x13notificationMessage\x18\t \x01(\tR\x13notificationMessage\"\xaf\x01\n" +
	"\x03C2S\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12 \n" +
	"\vcompetition\x18\x02 \x01(\tR\vcompetition\x128\n" +
	"\frelatedEvent\x18\x03 \x01(\v2\x14.Qot_Common.SecurityR\frelatedEvent\x12\x1a\n" +
	"\bnextPage\x18\x04 \x01(\tR\bnextPage\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"y\n" +
	"\x03S2C\x12V\n" +
	"\rmilestoneList\x18\x01 \x03(\v20.Qot_GetEventContractMilestoneList.MilestoneItemR\rmilestoneList\x12\x1a\n" +
	"\bnextPage\x18\x02 \x01(\tR\bnextPage\"C\n" +
	"\aRequest\x128\n" +
	"\x03c2s\x18\x01 \x02(\v2&.Qot_GetEventContractMilestoneList.C2SR\x03c2s\"\x96\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x128\n" +
	"\x03s2c\x18\x04 \x01(\v2&.Qot_GetEventContractMilestoneList.S2CR\x03s2cB^\n" +
	"\x13com.futu.openapi.pbZGgithub.com/shing1211/futuapi4go/pkg/pb/qotgeteventcontractmilestonelist"

var (
	file_Qot_GetEventContractMilestoneList_proto_rawDescOnce sync.Once
	file_Qot_GetEventContractMilestoneList_proto_rawDescData []byte
)

func file_Qot_GetEventContractMilestoneList_proto_rawDescGZIP() []byte {
	file_Qot_GetEventContractMilestoneList_proto_rawDescOnce.Do(func() {
		file_Qot_GetEventContractMilestoneList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetEventContractMilestoneList_proto_rawDesc), len(file_Qot_GetEventContractMilestoneList_proto_rawDesc)))
	})
	return file_Qot_GetEventContractMilestoneList_proto_rawDescData
}

var file_Qot_GetEventContractMilestoneList_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetEventContractMilestoneList_proto_goTypes = []any{
	(*MilestoneItem)(nil),           // 0: Qot_GetEventContractMilestoneList.MilestoneItem
	(*C2S)(nil),                     // 1: Qot_GetEventContractMilestoneList.C2S
	(*S2C)(nil),                     // 2: Qot_GetEventContractMilestoneList.S2C
	(*Request)(nil),                 // 3: Qot_GetEventContractMilestoneList.Request
	(*Response)(nil),                // 4: Qot_GetEventContractMilestoneList.Response
	(*qotcommon.Security)(nil),      // 5: Qot_Common.Security
	(qotcommon.EC_MilestoneType)(0), // 6: Qot_Common.EC_MilestoneType
}
var file_Qot_GetEventContractMilestoneList_proto_depIdxs = []int32{
	5, // 0: Qot_GetEventContractMilestoneList.MilestoneItem.milestoneSecurity:type_name -> Qot_Common.Security
	6, // 1: Qot_GetEventContractMilestoneList.MilestoneItem.type:type_name -> Qot_Common.EC_MilestoneType
	5, // 2: Qot_GetEventContractMilestoneList.MilestoneItem.primaryEventSecurity:type_name -> Qot_Common.Security
	5, // 3: Qot_GetEventContractMilestoneList.MilestoneItem.relatedEventList:type_name -> Qot_Common.Security
	5, // 4: Qot_GetEventContractMilestoneList.C2S.relatedEvent:type_name -> Qot_Common.Security
	0, // 5: Qot_GetEventContractMilestoneList.S2C.milestoneList:type_name -> Qot_GetEventContractMilestoneList.MilestoneItem
	1, // 6: Qot_GetEventContractMilestoneList.Request.c2s:type_name -> Qot_GetEventContractMilestoneList.C2S
	2, // 7: Qot_GetEventContractMilestoneList.Response.s2c:type_name -> Qot_GetEventContractMilestoneList.S2C
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_Qot_GetEventContractMilestoneList_proto_init() }
func file_Qot_GetEventContractMilestoneList_proto_init() {
	if File_Qot_GetEventContractMilestoneList_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetEventContractMilestoneList_proto_rawDesc), len(file_Qot_GetEventContractMilestoneList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetEventContractMilestoneList_proto_goTypes,
		DependencyIndexes: file_Qot_GetEventContractMilestoneList_proto_depIdxs,
		MessageInfos:      file_Qot_GetEventContractMilestoneList_proto_msgTypes,
	}.Build()
	File_Qot_GetEventContractMilestoneList_proto = out.File
	file_Qot_GetEventContractMilestoneList_proto_goTypes = nil
	file_Qot_GetEventContractMilestoneList_proto_depIdxs = nil
}
