// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: Qot_GetOptionSellerScreener.proto

package qotgetoptionsellerscreener

import (
	_ "github.com/shing1211/futuapi4go/pkg/pb/common"
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	qotoptioncommon "github.com/shing1211/futuapi4go/pkg/pb/qotoptioncommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 卖方策略合约项
type SellerItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Option           *qotcommon.Security    `protobuf:"bytes,1,req,name=option" json:"option,omitempty"`                        // 期权合约
	Name             *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`                            // 期权名称
	OptionType       *int32                 `protobuf:"varint,3,opt,name=optionType" json:"optionType,omitempty"`               // Qot_Common.OptionType (CALL/PUT)
	StrikePrice      *float64               `protobuf:"fixed64,4,opt,name=strikePrice" json:"strikePrice,omitempty"`            // 行权价
	StrikeTime       *string                `protobuf:"bytes,5,opt,name=strikeTime" json:"strikeTime,omitempty"`                // 到期日("yyyy-MM-dd")
	StrikeTimestamp  *float64               `protobuf:"fixed64,6,opt,name=strikeTimestamp" json:"strikeTimestamp,omitempty"`    // 到期日时间戳(秒)
	LeftDays         *int32                 `protobuf:"varint,7,opt,name=leftDays" json:"leftDays,omitempty"`                   // 距到期天数
	OptionPrice      *float64               `protobuf:"fixed64,8,opt,name=optionPrice" json:"optionPrice,omitempty"`            // 期权价格
	StockPrice       *float64               `protobuf:"fixed64,9,opt,name=stockPrice" json:"stockPrice,omitempty"`              // 标的当前价
	Premium          *float64               `protobuf:"fixed64,10,opt,name=premium" json:"premium,omitempty"`                   // 权利金(=期权价x合约乘数)
	OtmDegree        *float64               `protobuf:"fixed64,11,opt,name=otmDegree" json:"otmDegree,omitempty"`               // 价外程度(%)
	Iv               *float64               `protobuf:"fixed64,12,opt,name=iv" json:"iv,omitempty"`                             // 隐含波动率(%)
	IntervalReturn   *float64               `protobuf:"fixed64,13,opt,name=intervalReturn" json:"intervalReturn,omitempty"`     // 区间收益率(%)
	AnnualizedReturn *float64               `protobuf:"fixed64,14,opt,name=annualizedReturn" json:"annualizedReturn,omitempty"` // 年化收益率(%)
	ItmProbability   *float64               `protobuf:"fixed64,15,opt,name=itmProbability" json:"itmProbability,omitempty"`     // 行权概率(%)
	// Covered Call 专属
	StrikedIntervalReturn   *float64 `protobuf:"fixed64,16,opt,name=strikedIntervalReturn" json:"strikedIntervalReturn,omitempty"`     // 被行权区间收益率(%)
	StrikedAnnualizedReturn *float64 `protobuf:"fixed64,17,opt,name=strikedAnnualizedReturn" json:"strikedAnnualizedReturn,omitempty"` // 被行权年化收益率(%)
	// 标的信息
	Owner         *qotcommon.Security `protobuf:"bytes,18,opt,name=owner" json:"owner,omitempty"` // 标的证券
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellerItem) Reset() {
	*x = SellerItem{}
	mi := &file_Qot_GetOptionSellerScreener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerItem) ProtoMessage() {}

func (x *SellerItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionSellerScreener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerItem.ProtoReflect.Descriptor instead.
func (*SellerItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionSellerScreener_proto_rawDescGZIP(), []int{0}
}

func (x *SellerItem) GetOption() *qotcommon.Security {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *SellerItem) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SellerItem) GetOptionType() int32 {
	if x != nil && x.OptionType != nil {
		return *x.OptionType
	}
	return 0
}

func (x *SellerItem) GetStrikePrice() float64 {
	if x != nil && x.StrikePrice != nil {
		return *x.StrikePrice
	}
	return 0
}

func (x *SellerItem) GetStrikeTime() string {
	if x != nil && x.StrikeTime != nil {
		return *x.StrikeTime
	}
	return ""
}

func (x *SellerItem) GetStrikeTimestamp() float64 {
	if x != nil && x.StrikeTimestamp != nil {
		return *x.StrikeTimestamp
	}
	return 0
}

func (x *SellerItem) GetLeftDays() int32 {
	if x != nil && x.LeftDays != nil {
		return *x.LeftDays
	}
	return 0
}

func (x *SellerItem) GetOptionPrice() float64 {
	if x != nil && x.OptionPrice != nil {
		return *x.OptionPrice
	}
	return 0
}

func (x *SellerItem) GetStockPrice() float64 {
	if x != nil && x.StockPrice != nil {
		return *x.StockPrice
	}
	return 0
}

func (x *SellerItem) GetPremium() float64 {
	if x != nil && x.Premium != nil {
		return *x.Premium
	}
	return 0
}

func (x *SellerItem) GetOtmDegree() float64 {
	if x != nil && x.OtmDegree != nil {
		return *x.OtmDegree
	}
	return 0
}

func (x *SellerItem) GetIv() float64 {
	if x != nil && x.Iv != nil {
		return *x.Iv
	}
	return 0
}

func (x *SellerItem) GetIntervalReturn() float64 {
	if x != nil && x.IntervalReturn != nil {
		return *x.IntervalReturn
	}
	return 0
}

func (x *SellerItem) GetAnnualizedReturn() float64 {
	if x != nil && x.AnnualizedReturn != nil {
		return *x.AnnualizedReturn
	}
	return 0
}

func (x *SellerItem) GetItmProbability() float64 {
	if x != nil && x.ItmProbability != nil {
		return *x.ItmProbability
	}
	return 0
}

func (x *SellerItem) GetStrikedIntervalReturn() float64 {
	if x != nil && x.StrikedIntervalReturn != nil {
		return *x.StrikedIntervalReturn
	}
	return 0
}

func (x *SellerItem) GetStrikedAnnualizedReturn() float64 {
	if x != nil && x.StrikedAnnualizedReturn != nil {
		return *x.StrikedAnnualizedReturn
	}
	return 0
}

func (x *SellerItem) GetOwner() *qotcommon.Security {
	if x != nil {
		return x.Owner
	}
	return nil
}

type C2S struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	OptionMarket  *int32                             `protobuf:"varint,1,req,name=optionMarket" json:"optionMarket,omitempty"` // Qot_OptionCommon.OptionMarket (仅支持US_Security/HK_Security)
	SellerType    *int32                             `protobuf:"varint,2,req,name=sellerType" json:"sellerType,omitempty"`     // Qot_OptionCommon.SellerType (必填)
	SortType      *int32                             `protobuf:"varint,3,opt,name=sortType" json:"sortType,omitempty"`         // Qot_OptionCommon.SellerSortType (默认 AnnualizedReturn)
	IsAsc         *bool                              `protobuf:"varint,4,opt,name=isAsc" json:"isAsc,omitempty"`               // 默认 false(降序)
	FilterList    []*qotoptioncommon.SellerIndicator `protobuf:"bytes,5,rep,name=filterList" json:"filterList,omitempty"`      // 筛选条件(AND关系)，部分字段有默认值，详见SellerIndicatorType注释
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetOptionSellerScreener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionSellerScreener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionSellerScreener_proto_rawDescGZIP(), []int{1}
}

func (x *C2S) GetOptionMarket() int32 {
	if x != nil && x.OptionMarket != nil {
		return *x.OptionMarket
	}
	return 0
}

func (x *C2S) GetSellerType() int32 {
	if x != nil && x.SellerType != nil {
		return *x.SellerType
	}
	return 0
}

func (x *C2S) GetSortType() int32 {
	if x != nil && x.SortType != nil {
		return *x.SortType
	}
	return 0
}

func (x *C2S) GetIsAsc() bool {
	if x != nil && x.IsAsc != nil {
		return *x.IsAsc
	}
	return false
}

func (x *C2S) GetFilterList() []*qotoptioncommon.SellerIndicator {
	if x != nil {
		return x.FilterList
	}
	return nil
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemList      []*SellerItem          `protobuf:"bytes,1,rep,name=itemList" json:"itemList,omitempty"` // 合约列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetOptionSellerScreener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionSellerScreener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionSellerScreener_proto_rawDescGZIP(), []int{2}
}

func (x *S2C) GetItemList() []*SellerItem {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetOptionSellerScreener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionSellerScreener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionSellerScreener_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType，返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetOptionSellerScreener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionSellerScreener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionSellerScreener_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetOptionSellerScreener_proto protoreflect.FileDescriptor

const file_Qot_GetOptionSellerScreener_proto_rawDesc = "" +
	"\n" +
	"!Qot_GetOptionSellerScreener.proto\x12\x1bQot_GetOptionSellerScreener\x1a\fCommon.proto\x1a\x10Qot_Common.proto\x1a\x16Qot_OptionCommon.proto\"\x98\x05\n" +
	"\n" +
	"SellerItem\x12,\n" +
	"\x06option\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\x06option\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"optionType\x18\x03 \x01(\x05R\n" +
	"optionType\x12 \n" +
	"\vstrikePrice\x18\x04 \x01(\x01R\vstrikePrice\x12\x1e\n" +
	"\n" +
	"strikeTime\x18\x05 \x01(\tR\n" +
	"strikeTime\x12(\n" +
	"\x0fstrikeTimestamp\x18\x06 \x01(\x01R\x0fstrikeTimestamp\x12\x1a\n" +
	"\bleftDays\x18\a \x01(\x05R\bleftDays\x12 \n" +
	"\voptionPrice\x18\b \x01(\x01R\voptionPrice\x12\x1e\n" +
	"\n" +
	"stockPrice\x18\t \x01(\x01R\n" +
	"stockPrice\x12\x18\n" +
	"\apremium\x18\n" +
	" \x01(\x01R\apremium\x12\x1c\n" +
	"\totmDegree\x18\v \x01(\x01R\totmDegree\x12\x0e\n" +
	"\x02iv\x18\f \x01(\x01R\x02iv\x12&\n" +
	"\x0eintervalReturn\x18\r \x01(\x01R\x0eintervalReturn\x12*\n" +
	"\x10annualizedReturn\x18\x0e \x01(\x01R\x10annualizedReturn\x12&\n" +
	"\x0eitmProbability\x18\x0f \x01(\x01R\x0eitmProbability\x124\n" +
	"\x15strikedIntervalReturn\x18\x10 \x01(\x01R\x15strikedIntervalReturn\x128\n" +
	"\x17strikedAnnualizedReturn\x18\x11 \x01(\x01R\x17strikedAnnualizedReturn\x12*\n" +
	"\x05owner\x18\x12 \x01(\v2\x14.Qot_Common.SecurityR\x05owner\"\xbe\x01\n" +
	"\x03C2S\x12\"\n" +
	"\foptionMarket\x18\x01 \x02(\x05R\foptionMarket\x12\x1e\n" +
	"\n" +
	"sellerType\x18\x02 \x02(\x05R\n" +
	"sellerType\x12\x1a\n" +
	"\bsortType\x18\x03 \x01(\x05R\bsortType\x12\x14\n" +
	"\x05isAsc\x18\x04 \x01(\bR\x05isAsc\x12A\n" +
	"\n" +
	"filterList\x18\x05 \x03(\v2!.Qot_OptionCommon.SellerIndicatorR\n" +
	"filterList\"J\n" +
	"\x03S2C\x12C\n" +
	"\bitemList\x18\x01 \x03(\v2'.Qot_GetOptionSellerScreener.SellerItemR\bitemList\"=\n" +
	"\aRequest\x122\n" +
	"\x03c2s\x18\x01 \x02(\v2 .Qot_GetOptionSellerScreener.C2SR\x03c2s\"\x90\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x122\n" +
	"\x03s2c\x18\x04 \x01(\v2 .Qot_GetOptionSellerScreener.S2CR\x03s2cBX\n" +
	"\x13com.futu.openapi.pbZAgithub.com/shing1211/futuapi4go/pkg/pb/qotgetoptionsellerscreener"

var (
	file_Qot_GetOptionSellerScreener_proto_rawDescOnce sync.Once
	file_Qot_GetOptionSellerScreener_proto_rawDescData []byte
)

func file_Qot_GetOptionSellerScreener_proto_rawDescGZIP() []byte {
	file_Qot_GetOptionSellerScreener_proto_rawDescOnce.Do(func() {
		file_Qot_GetOptionSellerScreener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetOptionSellerScreener_proto_rawDesc), len(file_Qot_GetOptionSellerScreener_proto_rawDesc)))
	})
	return file_Qot_GetOptionSellerScreener_proto_rawDescData
}

var file_Qot_GetOptionSellerScreener_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetOptionSellerScreener_proto_goTypes = []any{
	(*SellerItem)(nil),                      // 0: Qot_GetOptionSellerScreener.SellerItem
	(*C2S)(nil),                             // 1: Qot_GetOptionSellerScreener.C2S
	(*S2C)(nil),                             // 2: Qot_GetOptionSellerScreener.S2C
	(*Request)(nil),                         // 3: Qot_GetOptionSellerScreener.Request
	(*Response)(nil),                        // 4: Qot_GetOptionSellerScreener.Response
	(*qotcommon.Security)(nil),              // 5: Qot_Common.Security
	(*qotoptioncommon.SellerIndicator)(nil), // 6: Qot_OptionCommon.SellerIndicator
}
var file_Qot_GetOptionSellerScreener_proto_depIdxs = []int32{
	5, // 0: Qot_GetOptionSellerScreener.SellerItem.option:type_name -> Qot_Common.Security
	5, // 1: Qot_GetOptionSellerScreener.SellerItem.owner:type_name -> Qot_Common.Security
	6, // 2: Qot_GetOptionSellerScreener.C2S.filterList:type_name -> Qot_OptionCommon.SellerIndicator
	0, // 3: Qot_GetOptionSellerScreener.S2C.itemList:type_name -> Qot_GetOptionSellerScreener.SellerItem
	1, // 4: Qot_GetOptionSellerScreener.Request.c2s:type_name -> Qot_GetOptionSellerScreener.C2S
	2, // 5: Qot_GetOptionSellerScreener.Response.s2c:type_name -> Qot_GetOptionSellerScreener.S2C
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_Qot_GetOptionSellerScreener_proto_init() }
func file_Qot_GetOptionSellerScreener_proto_init() {
	if File_Qot_GetOptionSellerScreener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetOptionSellerScreener_proto_rawDesc), len(file_Qot_GetOptionSellerScreener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetOptionSellerScreener_proto_goTypes,
		DependencyIndexes: file_Qot_GetOptionSellerScreener_proto_depIdxs,
		MessageInfos:      file_Qot_GetOptionSellerScreener_proto_msgTypes,
	}.Build()
	File_Qot_GetOptionSellerScreener_proto = out.File
	file_Qot_GetOptionSellerScreener_proto_goTypes = nil
	file_Qot_GetOptionSellerScreener_proto_depIdxs = nil
}
