// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: Qot_GetEarningsCalendar.proto

package qotgetearningscalendar

import (
	_ "github.com/shing1211/futuapi4go/pkg/pb/common"
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	qotoptioncommon "github.com/shing1211/futuapi4go/pkg/pb/qotoptioncommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 财报日历排序类型
type EarningsCalendarSortType int32

const (
	EarningsCalendarSortType_EarningsCalendarSortType_Unknown      EarningsCalendarSortType = 0 //未知
	EarningsCalendarSortType_EarningsCalendarSortType_Hot          EarningsCalendarSortType = 1 //热门(默认)
	EarningsCalendarSortType_EarningsCalendarSortType_MarketCap    EarningsCalendarSortType = 2 //历史市值
	EarningsCalendarSortType_EarningsCalendarSortType_OptionVolume EarningsCalendarSortType = 3 //期权成交量(仅港美股)
	EarningsCalendarSortType_EarningsCalendarSortType_IV           EarningsCalendarSortType = 4 //隐含波动率(仅港美股)
	EarningsCalendarSortType_EarningsCalendarSortType_IVRank       EarningsCalendarSortType = 5 //IV等级(仅港美股)
	EarningsCalendarSortType_EarningsCalendarSortType_IVPercentile EarningsCalendarSortType = 6 //IV百分位数(仅港美股)
	EarningsCalendarSortType_EarningsCalendarSortType_RtMarketCap  EarningsCalendarSortType = 7 //实时市值
)

// Enum value maps for EarningsCalendarSortType.
var (
	EarningsCalendarSortType_name = map[int32]string{
		0: "EarningsCalendarSortType_Unknown",
		1: "EarningsCalendarSortType_Hot",
		2: "EarningsCalendarSortType_MarketCap",
		3: "EarningsCalendarSortType_OptionVolume",
		4: "EarningsCalendarSortType_IV",
		5: "EarningsCalendarSortType_IVRank",
		6: "EarningsCalendarSortType_IVPercentile",
		7: "EarningsCalendarSortType_RtMarketCap",
	}
	EarningsCalendarSortType_value = map[string]int32{
		"EarningsCalendarSortType_Unknown":      0,
		"EarningsCalendarSortType_Hot":          1,
		"EarningsCalendarSortType_MarketCap":    2,
		"EarningsCalendarSortType_OptionVolume": 3,
		"EarningsCalendarSortType_IV":           4,
		"EarningsCalendarSortType_IVRank":       5,
		"EarningsCalendarSortType_IVPercentile": 6,
		"EarningsCalendarSortType_RtMarketCap":  7,
	}
)

func (x EarningsCalendarSortType) Enum() *EarningsCalendarSortType {
	p := new(EarningsCalendarSortType)
	*p = x
	return p
}

func (x EarningsCalendarSortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EarningsCalendarSortType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetEarningsCalendar_proto_enumTypes[0].Descriptor()
}

func (EarningsCalendarSortType) Type() protoreflect.EnumType {
	return &file_Qot_GetEarningsCalendar_proto_enumTypes[0]
}

func (x EarningsCalendarSortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EarningsCalendarSortType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EarningsCalendarSortType(num)
	return nil
}

// Deprecated: Use EarningsCalendarSortType.Descriptor instead.
func (EarningsCalendarSortType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{0}
}

// 财报日历发布类型
type EarningsCalendarPubType int32

const (
	EarningsCalendarPubType_EarningsCalendarPubType_Unknown EarningsCalendarPubType = -1 //未知
	EarningsCalendarPubType_EarningsCalendarPubType_Regular EarningsCalendarPubType = 0  //盘中(未识别出时段)
	EarningsCalendarPubType_EarningsCalendarPubType_Before  EarningsCalendarPubType = 1  //盘前
	EarningsCalendarPubType_EarningsCalendarPubType_After   EarningsCalendarPubType = 2  //盘后
)

// Enum value maps for EarningsCalendarPubType.
var (
	EarningsCalendarPubType_name = map[int32]string{
		-1: "EarningsCalendarPubType_Unknown",
		0:  "EarningsCalendarPubType_Regular",
		1:  "EarningsCalendarPubType_Before",
		2:  "EarningsCalendarPubType_After",
	}
	EarningsCalendarPubType_value = map[string]int32{
		"EarningsCalendarPubType_Unknown": -1,
		"EarningsCalendarPubType_Regular": 0,
		"EarningsCalendarPubType_Before":  1,
		"EarningsCalendarPubType_After":   2,
	}
)

func (x EarningsCalendarPubType) Enum() *EarningsCalendarPubType {
	p := new(EarningsCalendarPubType)
	*p = x
	return p
}

func (x EarningsCalendarPubType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EarningsCalendarPubType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetEarningsCalendar_proto_enumTypes[1].Descriptor()
}

func (EarningsCalendarPubType) Type() protoreflect.EnumType {
	return &file_Qot_GetEarningsCalendar_proto_enumTypes[1]
}

func (x EarningsCalendarPubType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EarningsCalendarPubType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EarningsCalendarPubType(num)
	return nil
}

// Deprecated: Use EarningsCalendarPubType.Descriptor instead.
func (EarningsCalendarPubType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{1}
}

// 财报指标类型
type EarningsCalendarEstimateType int32

const (
	EarningsCalendarEstimateType_EarningsCalendarEstimateType_Unknown EarningsCalendarEstimateType = 0 //未知
	EarningsCalendarEstimateType_EarningsCalendarEstimateType_EPS     EarningsCalendarEstimateType = 1 //每股收益(EPS GAAP)
	EarningsCalendarEstimateType_EarningsCalendarEstimateType_Revenue EarningsCalendarEstimateType = 2 //总收入
	EarningsCalendarEstimateType_EarningsCalendarEstimateType_EBIT    EarningsCalendarEstimateType = 3 //息税前利润
)

// Enum value maps for EarningsCalendarEstimateType.
var (
	EarningsCalendarEstimateType_name = map[int32]string{
		0: "EarningsCalendarEstimateType_Unknown",
		1: "EarningsCalendarEstimateType_EPS",
		2: "EarningsCalendarEstimateType_Revenue",
		3: "EarningsCalendarEstimateType_EBIT",
	}
	EarningsCalendarEstimateType_value = map[string]int32{
		"EarningsCalendarEstimateType_Unknown": 0,
		"EarningsCalendarEstimateType_EPS":     1,
		"EarningsCalendarEstimateType_Revenue": 2,
		"EarningsCalendarEstimateType_EBIT":    3,
	}
)

func (x EarningsCalendarEstimateType) Enum() *EarningsCalendarEstimateType {
	p := new(EarningsCalendarEstimateType)
	*p = x
	return p
}

func (x EarningsCalendarEstimateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EarningsCalendarEstimateType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetEarningsCalendar_proto_enumTypes[2].Descriptor()
}

func (EarningsCalendarEstimateType) Type() protoreflect.EnumType {
	return &file_Qot_GetEarningsCalendar_proto_enumTypes[2]
}

func (x EarningsCalendarEstimateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EarningsCalendarEstimateType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EarningsCalendarEstimateType(num)
	return nil
}

// Deprecated: Use EarningsCalendarEstimateType.Descriptor instead.
func (EarningsCalendarEstimateType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{2}
}

// 财报周期类型
type EarningsCalendarPeriodType int32

const (
	EarningsCalendarPeriodType_EarningsCalendarPeriodType_Unknown    EarningsCalendarPeriodType = 0 //未知
	EarningsCalendarPeriodType_EarningsCalendarPeriodType_Quarterly  EarningsCalendarPeriodType = 1 //季度
	EarningsCalendarPeriodType_EarningsCalendarPeriodType_SemiAnnual EarningsCalendarPeriodType = 2 //半年度
	EarningsCalendarPeriodType_EarningsCalendarPeriodType_Annual     EarningsCalendarPeriodType = 3 //年度
)

// Enum value maps for EarningsCalendarPeriodType.
var (
	EarningsCalendarPeriodType_name = map[int32]string{
		0: "EarningsCalendarPeriodType_Unknown",
		1: "EarningsCalendarPeriodType_Quarterly",
		2: "EarningsCalendarPeriodType_SemiAnnual",
		3: "EarningsCalendarPeriodType_Annual",
	}
	EarningsCalendarPeriodType_value = map[string]int32{
		"EarningsCalendarPeriodType_Unknown":    0,
		"EarningsCalendarPeriodType_Quarterly":  1,
		"EarningsCalendarPeriodType_SemiAnnual": 2,
		"EarningsCalendarPeriodType_Annual":     3,
	}
)

func (x EarningsCalendarPeriodType) Enum() *EarningsCalendarPeriodType {
	p := new(EarningsCalendarPeriodType)
	*p = x
	return p
}

func (x EarningsCalendarPeriodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EarningsCalendarPeriodType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetEarningsCalendar_proto_enumTypes[3].Descriptor()
}

func (EarningsCalendarPeriodType) Type() protoreflect.EnumType {
	return &file_Qot_GetEarningsCalendar_proto_enumTypes[3]
}

func (x EarningsCalendarPeriodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EarningsCalendarPeriodType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EarningsCalendarPeriodType(num)
	return nil
}

// Deprecated: Use EarningsCalendarPeriodType.Descriptor instead.
func (EarningsCalendarPeriodType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{3}
}

// 股票列表类型
type EarningsCalendarStockListType int32

const (
	EarningsCalendarStockListType_EarningsCalendarStockListType_Unknown   EarningsCalendarStockListType = 0 //未知
	EarningsCalendarStockListType_EarningsCalendarStockListType_Watchlist EarningsCalendarStockListType = 1 //自选股
	EarningsCalendarStockListType_EarningsCalendarStockListType_Position  EarningsCalendarStockListType = 2 //持仓
	EarningsCalendarStockListType_EarningsCalendarStockListType_Special   EarningsCalendarStockListType = 3 //特别关注
)

// Enum value maps for EarningsCalendarStockListType.
var (
	EarningsCalendarStockListType_name = map[int32]string{
		0: "EarningsCalendarStockListType_Unknown",
		1: "EarningsCalendarStockListType_Watchlist",
		2: "EarningsCalendarStockListType_Position",
		3: "EarningsCalendarStockListType_Special",
	}
	EarningsCalendarStockListType_value = map[string]int32{
		"EarningsCalendarStockListType_Unknown":   0,
		"EarningsCalendarStockListType_Watchlist": 1,
		"EarningsCalendarStockListType_Position":  2,
		"EarningsCalendarStockListType_Special":   3,
	}
)

func (x EarningsCalendarStockListType) Enum() *EarningsCalendarStockListType {
	p := new(EarningsCalendarStockListType)
	*p = x
	return p
}

func (x EarningsCalendarStockListType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EarningsCalendarStockListType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetEarningsCalendar_proto_enumTypes[4].Descriptor()
}

func (EarningsCalendarStockListType) Type() protoreflect.EnumType {
	return &file_Qot_GetEarningsCalendar_proto_enumTypes[4]
}

func (x EarningsCalendarStockListType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EarningsCalendarStockListType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EarningsCalendarStockListType(num)
	return nil
}

// Deprecated: Use EarningsCalendarStockListType.Descriptor instead.
func (EarningsCalendarStockListType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{4}
}

// 财报日历筛选因子类型
type EarningsCalendarIndicatorType int32

const (
	EarningsCalendarIndicatorType_EarningsCalendarIndicatorType_Unknown       EarningsCalendarIndicatorType = 0
	EarningsCalendarIndicatorType_EarningsCalendarIndicatorType_PubType       EarningsCalendarIndicatorType = 1 //【确切值】发布类型(valueList, EarningsCalendarPubType)
	EarningsCalendarIndicatorType_EarningsCalendarIndicatorType_EstimateType  EarningsCalendarIndicatorType = 2 //【确切值】指标类型(valueList, EarningsCalendarEstimateType)
	EarningsCalendarIndicatorType_EarningsCalendarIndicatorType_MarketCap     EarningsCalendarIndicatorType = 3 //【范围】市值
	EarningsCalendarIndicatorType_EarningsCalendarIndicatorType_StockListType EarningsCalendarIndicatorType = 4 //【确切值】股票列表类型(valueList, EarningsCalendarStockListType)
	EarningsCalendarIndicatorType_EarningsCalendarIndicatorType_OptionVolume  EarningsCalendarIndicatorType = 5 //【范围】期权成交量(仅港美股)
	EarningsCalendarIndicatorType_EarningsCalendarIndicatorType_IV            EarningsCalendarIndicatorType = 6 //【范围】隐含波动率(%)(仅港美股)
	EarningsCalendarIndicatorType_EarningsCalendarIndicatorType_IVRank        EarningsCalendarIndicatorType = 7 //【范围】IV等级(%)(仅港美股)
	EarningsCalendarIndicatorType_EarningsCalendarIndicatorType_IVPercentile  EarningsCalendarIndicatorType = 8 //【范围】IV百分位数(%)(仅港美股)
	EarningsCalendarIndicatorType_EarningsCalendarIndicatorType_RtMarketCap   EarningsCalendarIndicatorType = 9 //【范围】实时市值
)

// Enum value maps for EarningsCalendarIndicatorType.
var (
	EarningsCalendarIndicatorType_name = map[int32]string{
		0: "EarningsCalendarIndicatorType_Unknown",
		1: "EarningsCalendarIndicatorType_PubType",
		2: "EarningsCalendarIndicatorType_EstimateType",
		3: "EarningsCalendarIndicatorType_MarketCap",
		4: "EarningsCalendarIndicatorType_StockListType",
		5: "EarningsCalendarIndicatorType_OptionVolume",
		6: "EarningsCalendarIndicatorType_IV",
		7: "EarningsCalendarIndicatorType_IVRank",
		8: "EarningsCalendarIndicatorType_IVPercentile",
		9: "EarningsCalendarIndicatorType_RtMarketCap",
	}
	EarningsCalendarIndicatorType_value = map[string]int32{
		"EarningsCalendarIndicatorType_Unknown":       0,
		"EarningsCalendarIndicatorType_PubType":       1,
		"EarningsCalendarIndicatorType_EstimateType":  2,
		"EarningsCalendarIndicatorType_MarketCap":     3,
		"EarningsCalendarIndicatorType_StockListType": 4,
		"EarningsCalendarIndicatorType_OptionVolume":  5,
		"EarningsCalendarIndicatorType_IV":            6,
		"EarningsCalendarIndicatorType_IVRank":        7,
		"EarningsCalendarIndicatorType_IVPercentile":  8,
		"EarningsCalendarIndicatorType_RtMarketCap":   9,
	}
)

func (x EarningsCalendarIndicatorType) Enum() *EarningsCalendarIndicatorType {
	p := new(EarningsCalendarIndicatorType)
	*p = x
	return p
}

func (x EarningsCalendarIndicatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EarningsCalendarIndicatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetEarningsCalendar_proto_enumTypes[5].Descriptor()
}

func (EarningsCalendarIndicatorType) Type() protoreflect.EnumType {
	return &file_Qot_GetEarningsCalendar_proto_enumTypes[5]
}

func (x EarningsCalendarIndicatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EarningsCalendarIndicatorType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EarningsCalendarIndicatorType(num)
	return nil
}

// Deprecated: Use EarningsCalendarIndicatorType.Descriptor instead.
func (EarningsCalendarIndicatorType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{5}
}

// 财报日历筛选条件
type EarningsCalendarIndicator struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	IndicatorType  *int32                          `protobuf:"varint,1,req,name=indicatorType" json:"indicatorType,omitempty"`  // EarningsCalendarIndicatorType
	IndicatorValue *qotoptioncommon.IndicatorValue `protobuf:"bytes,2,opt,name=indicatorValue" json:"indicatorValue,omitempty"` // 筛选条件
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EarningsCalendarIndicator) Reset() {
	*x = EarningsCalendarIndicator{}
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarningsCalendarIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarningsCalendarIndicator) ProtoMessage() {}

func (x *EarningsCalendarIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarningsCalendarIndicator.ProtoReflect.Descriptor instead.
func (*EarningsCalendarIndicator) Descriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{0}
}

func (x *EarningsCalendarIndicator) GetIndicatorType() int32 {
	if x != nil && x.IndicatorType != nil {
		return *x.IndicatorType
	}
	return 0
}

func (x *EarningsCalendarIndicator) GetIndicatorValue() *qotoptioncommon.IndicatorValue {
	if x != nil {
		return x.IndicatorValue
	}
	return nil
}

// 财报预测数据
type EstimateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EstimateType  *int32                 `protobuf:"varint,1,opt,name=estimateType" json:"estimateType,omitempty"`  // EarningsCalendarEstimateType
	ActualValue   *float64               `protobuf:"fixed64,2,opt,name=actualValue" json:"actualValue,omitempty"`   // 实际值(已发布时有值)
	PredictValue  *float64               `protobuf:"fixed64,3,opt,name=predictValue" json:"predictValue,omitempty"` // 预测值
	Currency      *string                `protobuf:"bytes,4,opt,name=currency" json:"currency,omitempty"`           // 货币单位(ISO 4217)
	PeriodType    *int32                 `protobuf:"varint,5,opt,name=periodType" json:"periodType,omitempty"`      // EarningsCalendarPeriodType
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateData) Reset() {
	*x = EstimateData{}
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateData) ProtoMessage() {}

func (x *EstimateData) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateData.ProtoReflect.Descriptor instead.
func (*EstimateData) Descriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{1}
}

func (x *EstimateData) GetEstimateType() int32 {
	if x != nil && x.EstimateType != nil {
		return *x.EstimateType
	}
	return 0
}

func (x *EstimateData) GetActualValue() float64 {
	if x != nil && x.ActualValue != nil {
		return *x.ActualValue
	}
	return 0
}

func (x *EstimateData) GetPredictValue() float64 {
	if x != nil && x.PredictValue != nil {
		return *x.PredictValue
	}
	return 0
}

func (x *EstimateData) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

func (x *EstimateData) GetPeriodType() int32 {
	if x != nil && x.PeriodType != nil {
		return *x.PeriodType
	}
	return 0
}

// 财报日历项
type EarningsCalendarItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Security          *qotcommon.Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`                     // 股票
	Name              *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`                             // 股票名称
	EarningsDate      *string                `protobuf:"bytes,3,opt,name=earningsDate" json:"earningsDate,omitempty"`             // 财报日期("yyyy-MM-dd")
	EarningsTimestamp *float64               `protobuf:"fixed64,4,opt,name=earningsTimestamp" json:"earningsTimestamp,omitempty"` // 财报发布时间戳(秒)
	PubType           *int32                 `protobuf:"varint,5,opt,name=pubType" json:"pubType,omitempty"`                      // EarningsCalendarPubType
	PeriodText        *string                `protobuf:"bytes,7,opt,name=periodText" json:"periodText,omitempty"`                 // 财年周期(如"2025Q1")
	EstimateList      []*EstimateData        `protobuf:"bytes,8,rep,name=estimateList" json:"estimateList,omitempty"`             // 预测数据列表
	// 期权字段(仅港美股)
	OptionVolume *int64   `protobuf:"varint,10,opt,name=optionVolume" json:"optionVolume,omitempty"`  // 期权成交量
	Iv           *float64 `protobuf:"fixed64,11,opt,name=iv" json:"iv,omitempty"`                     // 隐含波动率(%)
	IvRank       *float64 `protobuf:"fixed64,12,opt,name=ivRank" json:"ivRank,omitempty"`             // IV等级(%)
	IvPercentile *float64 `protobuf:"fixed64,13,opt,name=ivPercentile" json:"ivPercentile,omitempty"` // IV百分位数(%)
	// 行情字段
	MarketCap     *float64 `protobuf:"fixed64,20,opt,name=marketCap" json:"marketCap,omitempty"` // 实时市值
	Price         *float64 `protobuf:"fixed64,21,opt,name=price" json:"price,omitempty"`         // 最新价
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EarningsCalendarItem) Reset() {
	*x = EarningsCalendarItem{}
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarningsCalendarItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarningsCalendarItem) ProtoMessage() {}

func (x *EarningsCalendarItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarningsCalendarItem.ProtoReflect.Descriptor instead.
func (*EarningsCalendarItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{2}
}

func (x *EarningsCalendarItem) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *EarningsCalendarItem) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EarningsCalendarItem) GetEarningsDate() string {
	if x != nil && x.EarningsDate != nil {
		return *x.EarningsDate
	}
	return ""
}

func (x *EarningsCalendarItem) GetEarningsTimestamp() float64 {
	if x != nil && x.EarningsTimestamp != nil {
		return *x.EarningsTimestamp
	}
	return 0
}

func (x *EarningsCalendarItem) GetPubType() int32 {
	if x != nil && x.PubType != nil {
		return *x.PubType
	}
	return 0
}

func (x *EarningsCalendarItem) GetPeriodText() string {
	if x != nil && x.PeriodText != nil {
		return *x.PeriodText
	}
	return ""
}

func (x *EarningsCalendarItem) GetEstimateList() []*EstimateData {
	if x != nil {
		return x.EstimateList
	}
	return nil
}

func (x *EarningsCalendarItem) GetOptionVolume() int64 {
	if x != nil && x.OptionVolume != nil {
		return *x.OptionVolume
	}
	return 0
}

func (x *EarningsCalendarItem) GetIv() float64 {
	if x != nil && x.Iv != nil {
		return *x.Iv
	}
	return 0
}

func (x *EarningsCalendarItem) GetIvRank() float64 {
	if x != nil && x.IvRank != nil {
		return *x.IvRank
	}
	return 0
}

func (x *EarningsCalendarItem) GetIvPercentile() float64 {
	if x != nil && x.IvPercentile != nil {
		return *x.IvPercentile
	}
	return 0
}

func (x *EarningsCalendarItem) GetMarketCap() float64 {
	if x != nil && x.MarketCap != nil {
		return *x.MarketCap
	}
	return 0
}

func (x *EarningsCalendarItem) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

type C2S struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Market        *int32                       `protobuf:"varint,1,req,name=market" json:"market,omitempty"`        // Qot_Common.QotMarket (支持HK/US/CNSH/CNSZ/SG/JP/AU/CA)
	SortType      *int32                       `protobuf:"varint,2,opt,name=sortType" json:"sortType,omitempty"`    // EarningsCalendarSortType (默认 Hot)
	BeginDate     *string                      `protobuf:"bytes,3,opt,name=beginDate" json:"beginDate,omitempty"`   // 开始日期，格式"yyyy-MM-dd"，不传默认今天(仅拉取当天)
	EndDate       *string                      `protobuf:"bytes,4,opt,name=endDate" json:"endDate,omitempty"`       // 结束日期，格式"yyyy-MM-dd"，不传则仅拉取beginDate当天；与beginDate间隔不超过7天
	FilterList    []*EarningsCalendarIndicator `protobuf:"bytes,5,rep,name=filterList" json:"filterList,omitempty"` // 筛选条件(AND关系)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{3}
}

func (x *C2S) GetMarket() int32 {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return 0
}

func (x *C2S) GetSortType() int32 {
	if x != nil && x.SortType != nil {
		return *x.SortType
	}
	return 0
}

func (x *C2S) GetBeginDate() string {
	if x != nil && x.BeginDate != nil {
		return *x.BeginDate
	}
	return ""
}

func (x *C2S) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *C2S) GetFilterList() []*EarningsCalendarIndicator {
	if x != nil {
		return x.FilterList
	}
	return nil
}

type S2C struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ItemList      []*EarningsCalendarItem `protobuf:"bytes,1,rep,name=itemList" json:"itemList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{4}
}

func (x *S2C) GetItemList() []*EarningsCalendarItem {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType，返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetEarningsCalendar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetEarningsCalendar_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetEarningsCalendar_proto protoreflect.FileDescriptor

const file_Qot_GetEarningsCalendar_proto_rawDesc = "" +
	"\n" +
	"\x1dQot_GetEarningsCalendar.proto\x12\x17Qot_GetEarningsCalendar\x1a\fCommon.proto\x1a\x10Qot_Common.proto\x1a\x16Qot_OptionCommon.proto\"\x8b\x01\n" +
	"\x19EarningsCalendarIndicator\x12$\n" +
	"\rindicatorType\x18\x01 \x02(\x05R\rindicatorType\x12H\n" +
	"\x0eindicatorValue\x18\x02 \x01(\v2 .Qot_OptionCommon.IndicatorValueR\x0eindicatorValue\"\xb4\x01\n" +
	"\fEstimateData\x12\"\n" +
	"\festimateType\x18\x01 \x01(\x05R\festimateType\x12 \n" +
	"\vactualValue\x18\x02 \x01(\x01R\vactualValue\x12\"\n" +
	"\fpredictValue\x18\x03 \x01(\x01R\fpredictValue\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1e\n" +
	"\n" +
	"periodType\x18\x05 \x01(\x05R\n" +
	"periodType\"\xd7\x03\n" +
	"\x14EarningsCalendarItem\x120\n" +
	"\bsecurity\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fearningsDate\x18\x03 \x01(\tR\fearningsDate\x12,\n" +
	"\x11earningsTimestamp\x18\x04 \x01(\x01R\x11earningsTimestamp\x12\x18\n" +
	"\apubType\x18\x05 \x01(\x05R\apubType\x12\x1e\n" +
	"\n" +
	"periodText\x18\a \x01(\tR\n" +
	"periodText\x12I\n" +
	"\festimateList\x18\b \x03(\v2%.Qot_GetEarningsCalendar.EstimateDataR\festimateList\x12\"\n" +
	"\foptionVolume\x18\n" +
	" \x01(\x03R\foptionVolume\x12\x0e\n" +
	"\x02iv\x18\v \x01(\x01R\x02iv\x12\x16\n" +
	"\x06ivRank\x18\f \x01(\x01R\x06ivRank\x12\"\n" +
	"\fivPercentile\x18\r \x01(\x01R\fivPercentile\x12\x1c\n" +
	"\tmarketCap\x18\x14 \x01(\x01R\tmarketCap\x12\x14\n" +
	"\x05price\x18\x15 \x01(\x01R\x05price\"\xc5\x01\n" +
	"\x03C2S\x12\x16\n" +
	"\x06market\x18\x01 \x02(\x05R\x06market\x12\x1a\n" +
	"\bsortType\x18\x02 \x01(\x05R\bsortType\x12\x1c\n" +
	"\tbeginDate\x18\x03 \x01(\tR\tbeginDate\x12\x18\n" +
	"\aendDate\x18\x04 \x01(\tR\aendDate\x12R\n" +
	"\n" +
	"filterList\x18\x05 \x03(\v22.Qot_GetEarningsCalendar.EarningsCalendarIndicatorR\n" +
	"filterList\"P\n" +
	"\x03S2C\x12I\n" +
	"\bitemList\x18\x01 \x03(\v2-.Qot_GetEarningsCalendar.EarningsCalendarItemR\bitemList\"9\n" +
	"\aRequest\x12.\n" +
	"\x03c2s\x18\x01 \x02(\v2\x1c.Qot_GetEarningsCalendar.C2SR\x03c2s\"\x8c\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12.\n" +
	"\x03s2c\x18\x04 \x01(\v2\x1c.Qot_GetEarningsCalendar.S2CR\x03s2c*\xd0\x02\n" +
	"\x18EarningsCalendarSortType\x12$\n" +
	" EarningsCalendarSortType_Unknown\x10\x00\x12 \n" +
	"\x1cEarningsCalendarSortType_Hot\x10\x01\x12&\n" +
	"\"EarningsCalendarSortType_MarketCap\x10\x02\x12)\n" +
	"%EarningsCalendarSortType_OptionVolume\x10\x03\x12\x1f\n" +
	"\x1bEarningsCalendarSortType_IV\x10\x04\x12#\n" +
	"\x1fEarningsCalendarSortType_IVRank\x10\x05\x12)\n" +
	"%EarningsCalendarSortType_IVPercentile\x10\x06\x12(\n" +
	"$EarningsCalendarSortType_RtMarketCap\x10\a*\xb3\x01\n" +
	"\x17EarningsCalendarPubType\x12,\n" +
	"\x1fEarningsCalendarPubType_Unknown\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12#\n" +
	"\x1fEarningsCalendarPubType_Regular\x10\x00\x12\"\n" +
	"\x1eEarningsCalendarPubType_Before\x10\x01\x12!\n" +
	"\x1dEarningsCalendarPubType_After\x10\x02*\xbf\x01\n" +
	"\x1cEarningsCalendarEstimateType\x12(\n" +
	"$EarningsCalendarEstimateType_Unknown\x10\x00\x12$\n" +
	" EarningsCalendarEstimateType_EPS\x10\x01\x12(\n" +
	"$EarningsCalendarEstimateType_Revenue\x10\x02\x12%\n" +
	"!EarningsCalendarEstimateType_EBIT\x10\x03*\xc0\x01\n" +
	"\x1aEarningsCalendarPeriodType\x12&\n" +
	"\"EarningsCalendarPeriodType_Unknown\x10\x00\x12(\n" +
	"$EarningsCalendarPeriodType_Quarterly\x10\x01\x12)\n" +
	"%EarningsCalendarPeriodType_SemiAnnual\x10\x02\x12%\n" +
	"!EarningsCalendarPeriodType_Annual\x10\x03*\xce\x01\n" +
	"\x1dEarningsCalendarStockListType\x12)\n" +
	"%EarningsCalendarStockListType_Unknown\x10\x00\x12+\n" +
	"'EarningsCalendarStockListType_Watchlist\x10\x01\x12*\n" +
	"&EarningsCalendarStockListType_Position\x10\x02\x12)\n" +
	"%EarningsCalendarStockListType_Special\x10\x03*\xe2\x03\n" +
	"\x1dEarningsCalendarIndicatorType\x12)\n" +
	"%EarningsCalendarIndicatorType_Unknown\x10\x00\x12)\n" +
	"%EarningsCalendarIndicatorType_PubType\x10\x01\x12.\n" +
	"*EarningsCalendarIndicatorType_EstimateType\x10\x02\x12+\n" +
	"'EarningsCalendarIndicatorType_MarketCap\x10\x03\x12/\n" +
	"+EarningsCalendarIndicatorType_StockListType\x10\x04\x12.\n" +
	"*EarningsCalendarIndicatorType_OptionVolume\x10\x05\x12$\n" +
	" EarningsCalendarIndicatorType_IV\x10\x06\x12(\n" +
	"$EarningsCalendarIndicatorType_IVRank\x10\a\x12.\n" +
	"*EarningsCalendarIndicatorType_IVPercentile\x10\b\x12-\n" +
	")EarningsCalendarIndicatorType_RtMarketCap\x10\tBT\n" +
	"\x13com.futu.openapi.pbZ=github.com/shing1211/futuapi4go/pkg/pb/qotgetearningscalendar"

var (
	file_Qot_GetEarningsCalendar_proto_rawDescOnce sync.Once
	file_Qot_GetEarningsCalendar_proto_rawDescData []byte
)

func file_Qot_GetEarningsCalendar_proto_rawDescGZIP() []byte {
	file_Qot_GetEarningsCalendar_proto_rawDescOnce.Do(func() {
		file_Qot_GetEarningsCalendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetEarningsCalendar_proto_rawDesc), len(file_Qot_GetEarningsCalendar_proto_rawDesc)))
	})
	return file_Qot_GetEarningsCalendar_proto_rawDescData
}

var file_Qot_GetEarningsCalendar_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_Qot_GetEarningsCalendar_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_Qot_GetEarningsCalendar_proto_goTypes = []any{
	(EarningsCalendarSortType)(0),          // 0: Qot_GetEarningsCalendar.EarningsCalendarSortType
	(EarningsCalendarPubType)(0),           // 1: Qot_GetEarningsCalendar.EarningsCalendarPubType
	(EarningsCalendarEstimateType)(0),      // 2: Qot_GetEarningsCalendar.EarningsCalendarEstimateType
	(EarningsCalendarPeriodType)(0),        // 3: Qot_GetEarningsCalendar.EarningsCalendarPeriodType
	(EarningsCalendarStockListType)(0),     // 4: Qot_GetEarningsCalendar.EarningsCalendarStockListType
	(EarningsCalendarIndicatorType)(0),     // 5: Qot_GetEarningsCalendar.EarningsCalendarIndicatorType
	(*EarningsCalendarIndicator)(nil),      // 6: Qot_GetEarningsCalendar.EarningsCalendarIndicator
	(*EstimateData)(nil),                   // 7: Qot_GetEarningsCalendar.EstimateData
	(*EarningsCalendarItem)(nil),           // 8: Qot_GetEarningsCalendar.EarningsCalendarItem
	(*C2S)(nil),                            // 9: Qot_GetEarningsCalendar.C2S
	(*S2C)(nil),                            // 10: Qot_GetEarningsCalendar.S2C
	(*Request)(nil),                        // 11: Qot_GetEarningsCalendar.Request
	(*Response)(nil),                       // 12: Qot_GetEarningsCalendar.Response
	(*qotoptioncommon.IndicatorValue)(nil), // 13: Qot_OptionCommon.IndicatorValue
	(*qotcommon.Security)(nil),             // 14: Qot_Common.Security
}
var file_Qot_GetEarningsCalendar_proto_depIdxs = []int32{
	13, // 0: Qot_GetEarningsCalendar.EarningsCalendarIndicator.indicatorValue:type_name -> Qot_OptionCommon.IndicatorValue
	14, // 1: Qot_GetEarningsCalendar.EarningsCalendarItem.security:type_name -> Qot_Common.Security
	7,  // 2: Qot_GetEarningsCalendar.EarningsCalendarItem.estimateList:type_name -> Qot_GetEarningsCalendar.EstimateData
	6,  // 3: Qot_GetEarningsCalendar.C2S.filterList:type_name -> Qot_GetEarningsCalendar.EarningsCalendarIndicator
	8,  // 4: Qot_GetEarningsCalendar.S2C.itemList:type_name -> Qot_GetEarningsCalendar.EarningsCalendarItem
	9,  // 5: Qot_GetEarningsCalendar.Request.c2s:type_name -> Qot_GetEarningsCalendar.C2S
	10, // 6: Qot_GetEarningsCalendar.Response.s2c:type_name -> Qot_GetEarningsCalendar.S2C
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_Qot_GetEarningsCalendar_proto_init() }
func file_Qot_GetEarningsCalendar_proto_init() {
	if File_Qot_GetEarningsCalendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetEarningsCalendar_proto_rawDesc), len(file_Qot_GetEarningsCalendar_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetEarningsCalendar_proto_goTypes,
		DependencyIndexes: file_Qot_GetEarningsCalendar_proto_depIdxs,
		EnumInfos:         file_Qot_GetEarningsCalendar_proto_enumTypes,
		MessageInfos:      file_Qot_GetEarningsCalendar_proto_msgTypes,
	}.Build()
	File_Qot_GetEarningsCalendar_proto = out.File
	file_Qot_GetEarningsCalendar_proto_goTypes = nil
	file_Qot_GetEarningsCalendar_proto_depIdxs = nil
}
