// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: Qot_GetOptionChain.proto

package qotgetoptionchain

import (
	_ "github.com/shing1211/futuapi4go/pkg/pb/common"
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptionCondType int32

const (
	OptionCondType_OptionCondType_Unknow  OptionCondType = 0
	OptionCondType_OptionCondType_WithIn  OptionCondType = 1 //价内
	OptionCondType_OptionCondType_Outside OptionCondType = 2 //价外
)

// Enum value maps for OptionCondType.
var (
	OptionCondType_name = map[int32]string{
		0: "OptionCondType_Unknow",
		1: "OptionCondType_WithIn",
		2: "OptionCondType_Outside",
	}
	OptionCondType_value = map[string]int32{
		"OptionCondType_Unknow":  0,
		"OptionCondType_WithIn":  1,
		"OptionCondType_Outside": 2,
	}
)

func (x OptionCondType) Enum() *OptionCondType {
	p := new(OptionCondType)
	*p = x
	return p
}

func (x OptionCondType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptionCondType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetOptionChain_proto_enumTypes[0].Descriptor()
}

func (OptionCondType) Type() protoreflect.EnumType {
	return &file_Qot_GetOptionChain_proto_enumTypes[0]
}

func (x OptionCondType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OptionCondType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OptionCondType(num)
	return nil
}

// Deprecated: Use OptionCondType.Descriptor instead.
func (OptionCondType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetOptionChain_proto_rawDescGZIP(), []int{0}
}

// 以下为数据字段筛选，可选字段，不填表示不过滤
type DataFilter struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ImpliedVolatilityMin *float64               `protobuf:"fixed64,1,opt,name=impliedVolatilityMin" json:"impliedVolatilityMin,omitempty"` //隐含波动率过滤起点（精确到小数点后 0 位，超出部分会被舍弃）
	ImpliedVolatilityMax *float64               `protobuf:"fixed64,2,opt,name=impliedVolatilityMax" json:"impliedVolatilityMax,omitempty"` //隐含波动率过滤终点（精确到小数点后 0 位，超出部分会被舍弃）
	DeltaMin             *float64               `protobuf:"fixed64,3,opt,name=deltaMin" json:"deltaMin,omitempty"`                         //希腊值 Delta过滤起点（精确到小数点后 3 位，超出部分会被舍弃）
	DeltaMax             *float64               `protobuf:"fixed64,4,opt,name=deltaMax" json:"deltaMax,omitempty"`                         //希腊值 Delta过滤终点（精确到小数点后 3 位，超出部分会被舍弃）
	GammaMin             *float64               `protobuf:"fixed64,5,opt,name=gammaMin" json:"gammaMin,omitempty"`                         //希腊值 Gamma过滤起点（精确到小数点后 3 位，超出部分会被舍弃）
	GammaMax             *float64               `protobuf:"fixed64,6,opt,name=gammaMax" json:"gammaMax,omitempty"`                         //希腊值 Gamma过滤终点（精确到小数点后 3 位，超出部分会被舍弃）
	VegaMin              *float64               `protobuf:"fixed64,7,opt,name=vegaMin" json:"vegaMin,omitempty"`                           //希腊值 Vega过滤起点（精确到小数点后 3 位，超出部分会被舍弃）
	VegaMax              *float64               `protobuf:"fixed64,8,opt,name=vegaMax" json:"vegaMax,omitempty"`                           //希腊值 Vega过滤终点（精确到小数点后 3 位，超出部分会被舍弃）
	ThetaMin             *float64               `protobuf:"fixed64,9,opt,name=thetaMin" json:"thetaMin,omitempty"`                         //希腊值 Theta过滤起点（精确到小数点后 3 位，超出部分会被舍弃）
	ThetaMax             *float64               `protobuf:"fixed64,10,opt,name=thetaMax" json:"thetaMax,omitempty"`                        //希腊值 Theta过滤终点（精确到小数点后 3 位，超出部分会被舍弃）
	RhoMin               *float64               `protobuf:"fixed64,11,opt,name=rhoMin" json:"rhoMin,omitempty"`                            //希腊值 Rho过滤起点（精确到小数点后 3 位，超出部分会被舍弃）
	RhoMax               *float64               `protobuf:"fixed64,12,opt,name=rhoMax" json:"rhoMax,omitempty"`                            //希腊值 Rho过滤终点（精确到小数点后 3 位，超出部分会被舍弃）
	NetOpenInterestMin   *float64               `protobuf:"fixed64,13,opt,name=netOpenInterestMin" json:"netOpenInterestMin,omitempty"`    //净未平仓合约数过滤起点（精确到小数点后 0 位，超出部分会被舍弃）
	NetOpenInterestMax   *float64               `protobuf:"fixed64,14,opt,name=netOpenInterestMax" json:"netOpenInterestMax,omitempty"`    //净未平仓合约数过滤终点（精确到小数点后 0 位，超出部分会被舍弃）
	OpenInterestMin      *float64               `protobuf:"fixed64,15,opt,name=openInterestMin" json:"openInterestMin,omitempty"`          //未平仓合约数过滤起点（精确到小数点后 0 位，超出部分会被舍弃）
	OpenInterestMax      *float64               `protobuf:"fixed64,16,opt,name=openInterestMax" json:"openInterestMax,omitempty"`          //未平仓合约数过滤终点（精确到小数点后 0 位，超出部分会被舍弃）
	VolMin               *float64               `protobuf:"fixed64,17,opt,name=volMin" json:"volMin,omitempty"`                            //成交量过滤起点（精确到小数点后 0 位，超出部分会被舍弃）
	VolMax               *float64               `protobuf:"fixed64,18,opt,name=volMax" json:"volMax,omitempty"`                            //成交量过滤终点（精确到小数点后 0 位，超出部分会被舍弃）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DataFilter) Reset() {
	*x = DataFilter{}
	mi := &file_Qot_GetOptionChain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFilter) ProtoMessage() {}

func (x *DataFilter) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionChain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFilter.ProtoReflect.Descriptor instead.
func (*DataFilter) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionChain_proto_rawDescGZIP(), []int{0}
}

func (x *DataFilter) GetImpliedVolatilityMin() float64 {
	if x != nil && x.ImpliedVolatilityMin != nil {
		return *x.ImpliedVolatilityMin
	}
	return 0
}

func (x *DataFilter) GetImpliedVolatilityMax() float64 {
	if x != nil && x.ImpliedVolatilityMax != nil {
		return *x.ImpliedVolatilityMax
	}
	return 0
}

func (x *DataFilter) GetDeltaMin() float64 {
	if x != nil && x.DeltaMin != nil {
		return *x.DeltaMin
	}
	return 0
}

func (x *DataFilter) GetDeltaMax() float64 {
	if x != nil && x.DeltaMax != nil {
		return *x.DeltaMax
	}
	return 0
}

func (x *DataFilter) GetGammaMin() float64 {
	if x != nil && x.GammaMin != nil {
		return *x.GammaMin
	}
	return 0
}

func (x *DataFilter) GetGammaMax() float64 {
	if x != nil && x.GammaMax != nil {
		return *x.GammaMax
	}
	return 0
}

func (x *DataFilter) GetVegaMin() float64 {
	if x != nil && x.VegaMin != nil {
		return *x.VegaMin
	}
	return 0
}

func (x *DataFilter) GetVegaMax() float64 {
	if x != nil && x.VegaMax != nil {
		return *x.VegaMax
	}
	return 0
}

func (x *DataFilter) GetThetaMin() float64 {
	if x != nil && x.ThetaMin != nil {
		return *x.ThetaMin
	}
	return 0
}

func (x *DataFilter) GetThetaMax() float64 {
	if x != nil && x.ThetaMax != nil {
		return *x.ThetaMax
	}
	return 0
}

func (x *DataFilter) GetRhoMin() float64 {
	if x != nil && x.RhoMin != nil {
		return *x.RhoMin
	}
	return 0
}

func (x *DataFilter) GetRhoMax() float64 {
	if x != nil && x.RhoMax != nil {
		return *x.RhoMax
	}
	return 0
}

func (x *DataFilter) GetNetOpenInterestMin() float64 {
	if x != nil && x.NetOpenInterestMin != nil {
		return *x.NetOpenInterestMin
	}
	return 0
}

func (x *DataFilter) GetNetOpenInterestMax() float64 {
	if x != nil && x.NetOpenInterestMax != nil {
		return *x.NetOpenInterestMax
	}
	return 0
}

func (x *DataFilter) GetOpenInterestMin() float64 {
	if x != nil && x.OpenInterestMin != nil {
		return *x.OpenInterestMin
	}
	return 0
}

func (x *DataFilter) GetOpenInterestMax() float64 {
	if x != nil && x.OpenInterestMax != nil {
		return *x.OpenInterestMax
	}
	return 0
}

func (x *DataFilter) GetVolMin() float64 {
	if x != nil && x.VolMin != nil {
		return *x.VolMin
	}
	return 0
}

func (x *DataFilter) GetVolMax() float64 {
	if x != nil && x.VolMax != nil {
		return *x.VolMax
	}
	return 0
}

type C2S struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Owner           *qotcommon.Security    `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`                      //期权标的股，目前仅支持传入港美正股以及恒指国指
	IndexOptionType *int32                 `protobuf:"varint,6,opt,name=indexOptionType" json:"indexOptionType,omitempty"` //Qot_Common.IndexOptionType，指数期权的类型，仅用于恒指国指
	Type            *int32                 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`                       //Qot_Common.OptionType，期权类型，可选字段，不指定则表示都返回
	Condition       *int32                 `protobuf:"varint,3,opt,name=condition" json:"condition,omitempty"`             //OptionCondType，价内价外，可选字段，不指定则表示都返回
	BeginTime       *string                `protobuf:"bytes,4,req,name=beginTime" json:"beginTime,omitempty"`              //期权到期日开始时间
	EndTime         *string                `protobuf:"bytes,5,req,name=endTime" json:"endTime,omitempty"`                  //期权到期日结束时间，时间跨度最多一个月
	DataFilter      *DataFilter            `protobuf:"bytes,7,opt,name=dataFilter" json:"dataFilter,omitempty"`            //数据字段筛选
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetOptionChain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionChain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionChain_proto_rawDescGZIP(), []int{1}
}

func (x *C2S) GetOwner() *qotcommon.Security {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *C2S) GetIndexOptionType() int32 {
	if x != nil && x.IndexOptionType != nil {
		return *x.IndexOptionType
	}
	return 0
}

func (x *C2S) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *C2S) GetCondition() int32 {
	if x != nil && x.Condition != nil {
		return *x.Condition
	}
	return 0
}

func (x *C2S) GetBeginTime() string {
	if x != nil && x.BeginTime != nil {
		return *x.BeginTime
	}
	return ""
}

func (x *C2S) GetEndTime() string {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return ""
}

func (x *C2S) GetDataFilter() *DataFilter {
	if x != nil {
		return x.DataFilter
	}
	return nil
}

type OptionItem struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Call          *qotcommon.SecurityStaticInfo `protobuf:"bytes,1,opt,name=call" json:"call,omitempty"` //看涨期权，不一定有该字段，由请求条件决定
	Put           *qotcommon.SecurityStaticInfo `protobuf:"bytes,2,opt,name=put" json:"put,omitempty"`   //看跌期权，不一定有该字段，由请求条件决定
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionItem) Reset() {
	*x = OptionItem{}
	mi := &file_Qot_GetOptionChain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionItem) ProtoMessage() {}

func (x *OptionItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionChain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionItem.ProtoReflect.Descriptor instead.
func (*OptionItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionChain_proto_rawDescGZIP(), []int{2}
}

func (x *OptionItem) GetCall() *qotcommon.SecurityStaticInfo {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *OptionItem) GetPut() *qotcommon.SecurityStaticInfo {
	if x != nil {
		return x.Put
	}
	return nil
}

type OptionChain struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StrikeTime      *string                `protobuf:"bytes,1,req,name=strikeTime" json:"strikeTime,omitempty"`             //行权日
	Option          []*OptionItem          `protobuf:"bytes,2,rep,name=option" json:"option,omitempty"`                     //期权信息
	StrikeTimestamp *float64               `protobuf:"fixed64,3,opt,name=strikeTimestamp" json:"strikeTimestamp,omitempty"` //行权日时间戳
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OptionChain) Reset() {
	*x = OptionChain{}
	mi := &file_Qot_GetOptionChain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionChain) ProtoMessage() {}

func (x *OptionChain) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionChain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionChain.ProtoReflect.Descriptor instead.
func (*OptionChain) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionChain_proto_rawDescGZIP(), []int{3}
}

func (x *OptionChain) GetStrikeTime() string {
	if x != nil && x.StrikeTime != nil {
		return *x.StrikeTime
	}
	return ""
}

func (x *OptionChain) GetOption() []*OptionItem {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *OptionChain) GetStrikeTimestamp() float64 {
	if x != nil && x.StrikeTimestamp != nil {
		return *x.StrikeTimestamp
	}
	return 0
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionChain   []*OptionChain         `protobuf:"bytes,1,rep,name=optionChain" json:"optionChain,omitempty"` //期权链
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetOptionChain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionChain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionChain_proto_rawDescGZIP(), []int{4}
}

func (x *S2C) GetOptionChain() []*OptionChain {
	if x != nil {
		return x.OptionChain
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetOptionChain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionChain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionChain_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType，返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetOptionChain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetOptionChain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetOptionChain_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetOptionChain_proto protoreflect.FileDescriptor

const file_Qot_GetOptionChain_proto_rawDesc = "" +
	"\n" +
	"\x18Qot_GetOptionChain.proto\x12\x12Qot_GetOptionChain\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"\xe4\x04\n" +
	"\n" +
	"DataFilter\x122\n" +
	"\x14impliedVolatilityMin\x18\x01 \x01(\x01R\x14impliedVolatilityMin\x122\n" +
	"\x14impliedVolatilityMax\x18\x02 \x01(\x01R\x14impliedVolatilityMax\x12\x1a\n" +
	"\bdeltaMin\x18\x03 \x01(\x01R\bdeltaMin\x12\x1a\n" +
	"\bdeltaMax\x18\x04 \x01(\x01R\bdeltaMax\x12\x1a\n" +
	"\bgammaMin\x18\x05 \x01(\x01R\bgammaMin\x12\x1a\n" +
	"\bgammaMax\x18\x06 \x01(\x01R\bgammaMax\x12\x18\n" +
	"\avegaMin\x18\a \x01(\x01R\avegaMin\x12\x18\n" +
	"\avegaMax\x18\b \x01(\x01R\avegaMax\x12\x1a\n" +
	"\bthetaMin\x18\t \x01(\x01R\bthetaMin\x12\x1a\n" +
	"\bthetaMax\x18\n" +
	" \x01(\x01R\bthetaMax\x12\x16\n" +
	"\x06rhoMin\x18\v \x01(\x01R\x06rhoMin\x12\x16\n" +
	"\x06rhoMax\x18\f \x01(\x01R\x06rhoMax\x12.\n" +
	"\x12netOpenInterestMin\x18\r \x01(\x01R\x12netOpenInterestMin\x12.\n" +
	"\x12netOpenInterestMax\x18\x0e \x01(\x01R\x12netOpenInterestMax\x12(\n" +
	"\x0fopenInterestMin\x18\x0f \x01(\x01R\x0fopenInterestMin\x12(\n" +
	"\x0fopenInterestMax\x18\x10 \x01(\x01R\x0fopenInterestMax\x12\x16\n" +
	"\x06volMin\x18\x11 \x01(\x01R\x06volMin\x12\x16\n" +
	"\x06volMax\x18\x12 \x01(\x01R\x06volMax\"\x85\x02\n" +
	"\x03C2S\x12*\n" +
	"\x05owner\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\x05owner\x12(\n" +
	"\x0findexOptionType\x18\x06 \x01(\x05R\x0findexOptionType\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x1c\n" +
	"\tcondition\x18\x03 \x01(\x05R\tcondition\x12\x1c\n" +
	"\tbeginTime\x18\x04 \x02(\tR\tbeginTime\x12\x18\n" +
	"\aendTime\x18\x05 \x02(\tR\aendTime\x12>\n" +
	"\n" +
	"dataFilter\x18\a \x01(\v2\x1e.Qot_GetOptionChain.DataFilterR\n" +
	"dataFilter\"r\n" +
	"\n" +
	"OptionItem\x122\n" +
	"\x04call\x18\x01 \x01(\v2\x1e.Qot_Common.SecurityStaticInfoR\x04call\x120\n" +
	"\x03put\x18\x02 \x01(\v2\x1e.Qot_Common.SecurityStaticInfoR\x03put\"\x8f\x01\n" +
	"\vOptionChain\x12\x1e\n" +
	"\n" +
	"strikeTime\x18\x01 \x02(\tR\n" +
	"strikeTime\x126\n" +
	"\x06option\x18\x02 \x03(\v2\x1e.Qot_GetOptionChain.OptionItemR\x06option\x12(\n" +
	"\x0fstrikeTimestamp\x18\x03 \x01(\x01R\x0fstrikeTimestamp\"H\n" +
	"\x03S2C\x12A\n" +
	"\voptionChain\x18\x01 \x03(\v2\x1f.Qot_GetOptionChain.OptionChainR\voptionChain\"4\n" +
	"\aRequest\x12)\n" +
	"\x03c2s\x18\x01 \x02(\v2\x17.Qot_GetOptionChain.C2SR\x03c2s\"\x87\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12)\n" +
	"\x03s2c\x18\x04 \x01(\v2\x17.Qot_GetOptionChain.S2CR\x03s2c*b\n" +
	"\x0eOptionCondType\x12\x19\n" +
	"\x15OptionCondType_Unknow\x10\x00\x12\x19\n" +
	"\x15OptionCondType_WithIn\x10\x01\x12\x1a\n" +
	"\x16OptionCondType_Outside\x10\x02BN\n" +
	"\x13com.futu.openapi.pbZ7github.com/shing1211/futuapi4go/pkg/pb/qotgetoptionchain"

var (
	file_Qot_GetOptionChain_proto_rawDescOnce sync.Once
	file_Qot_GetOptionChain_proto_rawDescData []byte
)

func file_Qot_GetOptionChain_proto_rawDescGZIP() []byte {
	file_Qot_GetOptionChain_proto_rawDescOnce.Do(func() {
		file_Qot_GetOptionChain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetOptionChain_proto_rawDesc), len(file_Qot_GetOptionChain_proto_rawDesc)))
	})
	return file_Qot_GetOptionChain_proto_rawDescData
}

var file_Qot_GetOptionChain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Qot_GetOptionChain_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_Qot_GetOptionChain_proto_goTypes = []any{
	(OptionCondType)(0),                  // 0: Qot_GetOptionChain.OptionCondType
	(*DataFilter)(nil),                   // 1: Qot_GetOptionChain.DataFilter
	(*C2S)(nil),                          // 2: Qot_GetOptionChain.C2S
	(*OptionItem)(nil),                   // 3: Qot_GetOptionChain.OptionItem
	(*OptionChain)(nil),                  // 4: Qot_GetOptionChain.OptionChain
	(*S2C)(nil),                          // 5: Qot_GetOptionChain.S2C
	(*Request)(nil),                      // 6: Qot_GetOptionChain.Request
	(*Response)(nil),                     // 7: Qot_GetOptionChain.Response
	(*qotcommon.Security)(nil),           // 8: Qot_Common.Security
	(*qotcommon.SecurityStaticInfo)(nil), // 9: Qot_Common.SecurityStaticInfo
}
var file_Qot_GetOptionChain_proto_depIdxs = []int32{
	8, // 0: Qot_GetOptionChain.C2S.owner:type_name -> Qot_Common.Security
	1, // 1: Qot_GetOptionChain.C2S.dataFilter:type_name -> Qot_GetOptionChain.DataFilter
	9, // 2: Qot_GetOptionChain.OptionItem.call:type_name -> Qot_Common.SecurityStaticInfo
	9, // 3: Qot_GetOptionChain.OptionItem.put:type_name -> Qot_Common.SecurityStaticInfo
	3, // 4: Qot_GetOptionChain.OptionChain.option:type_name -> Qot_GetOptionChain.OptionItem
	4, // 5: Qot_GetOptionChain.S2C.optionChain:type_name -> Qot_GetOptionChain.OptionChain
	2, // 6: Qot_GetOptionChain.Request.c2s:type_name -> Qot_GetOptionChain.C2S
	5, // 7: Qot_GetOptionChain.Response.s2c:type_name -> Qot_GetOptionChain.S2C
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_Qot_GetOptionChain_proto_init() }
func file_Qot_GetOptionChain_proto_init() {
	if File_Qot_GetOptionChain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetOptionChain_proto_rawDesc), len(file_Qot_GetOptionChain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetOptionChain_proto_goTypes,
		DependencyIndexes: file_Qot_GetOptionChain_proto_depIdxs,
		EnumInfos:         file_Qot_GetOptionChain_proto_enumTypes,
		MessageInfos:      file_Qot_GetOptionChain_proto_msgTypes,
	}.Build()
	File_Qot_GetOptionChain_proto = out.File
	file_Qot_GetOptionChain_proto_goTypes = nil
	file_Qot_GetOptionChain_proto_depIdxs = nil
}
