// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: Trd_GetOrderFillList.proto

package trdgetorderfilllist

import (
	_ "gitee.com/shing1211/futuapi4go/pkg/pb/common"
	trdcommon "gitee.com/shing1211/futuapi4go/pkg/pb/trdcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2S struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	Header           *trdcommon.TrdHeader           `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`                     //交易公共参数头
	FilterConditions *trdcommon.TrdFilterConditions `protobuf:"bytes,2,opt,name=filterConditions" json:"filterConditions,omitempty"` //过滤条件
	RefreshCache     *bool                          `protobuf:"varint,3,opt,name=refreshCache" json:"refreshCache,omitempty"`        //立即刷新OpenD缓存的此数据，默认不填。true向服务器获取最新数据更新缓存并返回；flase或没填则返回OpenD缓存的数据，不会向服务器请求。
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Trd_GetOrderFillList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetOrderFillList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Trd_GetOrderFillList_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetHeader() *trdcommon.TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *C2S) GetFilterConditions() *trdcommon.TrdFilterConditions {
	if x != nil {
		return x.FilterConditions
	}
	return nil
}

func (x *C2S) GetRefreshCache() bool {
	if x != nil && x.RefreshCache != nil {
		return *x.RefreshCache
	}
	return false
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *trdcommon.TrdHeader   `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`               //交易公共参数头
	OrderFillList []*trdcommon.OrderFill `protobuf:"bytes,2,rep,name=orderFillList" json:"orderFillList,omitempty"` //成交列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Trd_GetOrderFillList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetOrderFillList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Trd_GetOrderFillList_proto_rawDescGZIP(), []int{1}
}

func (x *S2C) GetHeader() *trdcommon.TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *S2C) GetOrderFillList() []*trdcommon.OrderFill {
	if x != nil {
		return x.OrderFillList
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Trd_GetOrderFillList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetOrderFillList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Trd_GetOrderFillList_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType       *int32  `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg        *string `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32  `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C    `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Trd_GetOrderFillList_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_GetOrderFillList_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Trd_GetOrderFillList_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Trd_GetOrderFillList_proto protoreflect.FileDescriptor

const file_Trd_GetOrderFillList_proto_rawDesc = "" +
	"\n" +
	"\x1aTrd_GetOrderFillList.proto\x12\x14Trd_GetOrderFillList\x1a\fCommon.proto\x1a\x10Trd_Common.proto\"\xa5\x01\n" +
	"\x03C2S\x12-\n" +
	"\x06header\x18\x01 \x02(\v2\x15.Trd_Common.TrdHeaderR\x06header\x12K\n" +
	"\x10filterConditions\x18\x02 \x01(\v2\x1f.Trd_Common.TrdFilterConditionsR\x10filterConditions\x12\"\n" +
	"\frefreshCache\x18\x03 \x01(\bR\frefreshCache\"q\n" +
	"\x03S2C\x12-\n" +
	"\x06header\x18\x01 \x02(\v2\x15.Trd_Common.TrdHeaderR\x06header\x12;\n" +
	"\rorderFillList\x18\x02 \x03(\v2\x15.Trd_Common.OrderFillR\rorderFillList\"6\n" +
	"\aRequest\x12+\n" +
	"\x03c2s\x18\x01 \x02(\v2\x19.Trd_GetOrderFillList.C2SR\x03c2s\"\x89\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12+\n" +
	"\x03s2c\x18\x04 \x01(\v2\x19.Trd_GetOrderFillList.S2CR\x03s2cBP\n" +
	"\x13com.futu.openapi.pbZ9gitee.com/shing1211/futuapi4go/pkg/pb/trdgetorderfilllist"

var (
	file_Trd_GetOrderFillList_proto_rawDescOnce sync.Once
	file_Trd_GetOrderFillList_proto_rawDescData []byte
)

func file_Trd_GetOrderFillList_proto_rawDescGZIP() []byte {
	file_Trd_GetOrderFillList_proto_rawDescOnce.Do(func() {
		file_Trd_GetOrderFillList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Trd_GetOrderFillList_proto_rawDesc), len(file_Trd_GetOrderFillList_proto_rawDesc)))
	})
	return file_Trd_GetOrderFillList_proto_rawDescData
}

var file_Trd_GetOrderFillList_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Trd_GetOrderFillList_proto_goTypes = []any{
	(*C2S)(nil),                           // 0: Trd_GetOrderFillList.C2S
	(*S2C)(nil),                           // 1: Trd_GetOrderFillList.S2C
	(*Request)(nil),                       // 2: Trd_GetOrderFillList.Request
	(*Response)(nil),                      // 3: Trd_GetOrderFillList.Response
	(*trdcommon.TrdHeader)(nil),           // 4: Trd_Common.TrdHeader
	(*trdcommon.TrdFilterConditions)(nil), // 5: Trd_Common.TrdFilterConditions
	(*trdcommon.OrderFill)(nil),           // 6: Trd_Common.OrderFill
}
var file_Trd_GetOrderFillList_proto_depIdxs = []int32{
	4, // 0: Trd_GetOrderFillList.C2S.header:type_name -> Trd_Common.TrdHeader
	5, // 1: Trd_GetOrderFillList.C2S.filterConditions:type_name -> Trd_Common.TrdFilterConditions
	4, // 2: Trd_GetOrderFillList.S2C.header:type_name -> Trd_Common.TrdHeader
	6, // 3: Trd_GetOrderFillList.S2C.orderFillList:type_name -> Trd_Common.OrderFill
	0, // 4: Trd_GetOrderFillList.Request.c2s:type_name -> Trd_GetOrderFillList.C2S
	1, // 5: Trd_GetOrderFillList.Response.s2c:type_name -> Trd_GetOrderFillList.S2C
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_Trd_GetOrderFillList_proto_init() }
func file_Trd_GetOrderFillList_proto_init() {
	if File_Trd_GetOrderFillList_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Trd_GetOrderFillList_proto_rawDesc), len(file_Trd_GetOrderFillList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Trd_GetOrderFillList_proto_goTypes,
		DependencyIndexes: file_Trd_GetOrderFillList_proto_depIdxs,
		MessageInfos:      file_Trd_GetOrderFillList_proto_msgTypes,
	}.Build()
	File_Trd_GetOrderFillList_proto = out.File
	file_Trd_GetOrderFillList_proto_goTypes = nil
	file_Trd_GetOrderFillList_proto_depIdxs = nil
}
