// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: Qot_UpdateKL.proto

package qotupdatekl

import (
	_ "github.com/shing1211/futuapi4go/pkg/pb/common"
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RehabType     *int32                 `protobuf:"varint,1,req,name=rehabType" json:"rehabType,omitempty"` //Qot_Common.RehabType,复权类型
	KlType        *int32                 `protobuf:"varint,2,req,name=klType" json:"klType,omitempty"`       //Qot_Common.KLType,K线类型
	Security      *qotcommon.Security    `protobuf:"bytes,3,req,name=security" json:"security,omitempty"`    //股票
	Name          *string                `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`            // 股票名称
	KlList        []*qotcommon.KLine     `protobuf:"bytes,4,rep,name=klList" json:"klList,omitempty"`        //推送的k线点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_UpdateKL_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_UpdateKL_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_UpdateKL_proto_rawDescGZIP(), []int{0}
}

func (x *S2C) GetRehabType() int32 {
	if x != nil && x.RehabType != nil {
		return *x.RehabType
	}
	return 0
}

func (x *S2C) GetKlType() int32 {
	if x != nil && x.KlType != nil {
		return *x.KlType
	}
	return 0
}

func (x *S2C) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *S2C) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *S2C) GetKlList() []*qotcommon.KLine {
	if x != nil {
		return x.KlList
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_UpdateKL_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_UpdateKL_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_UpdateKL_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_UpdateKL_proto protoreflect.FileDescriptor

const file_Qot_UpdateKL_proto_rawDesc = "" +
	"\n" +
	"\x12Qot_UpdateKL.proto\x12\fQot_UpdateKL\x1a\fCommon.proto\x1a\x10Qot_Common.proto\"\xac\x01\n" +
	"\x03S2C\x12\x1c\n" +
	"\trehabType\x18\x01 \x02(\x05R\trehabType\x12\x16\n" +
	"\x06klType\x18\x02 \x02(\x05R\x06klType\x120\n" +
	"\bsecurity\x18\x03 \x02(\v2\x14.Qot_Common.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12)\n" +
	"\x06klList\x18\x04 \x03(\v2\x11.Qot_Common.KLineR\x06klList\"\x81\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12#\n" +
	"\x03s2c\x18\x04 \x01(\v2\x11.Qot_UpdateKL.S2CR\x03s2cBI\n" +
	"\x13com.futu.openapi.pbZ2github.com/shing1211/futuapi4go/pkg/pb/qotupdatekl"

var (
	file_Qot_UpdateKL_proto_rawDescOnce sync.Once
	file_Qot_UpdateKL_proto_rawDescData []byte
)

func file_Qot_UpdateKL_proto_rawDescGZIP() []byte {
	file_Qot_UpdateKL_proto_rawDescOnce.Do(func() {
		file_Qot_UpdateKL_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_UpdateKL_proto_rawDesc), len(file_Qot_UpdateKL_proto_rawDesc)))
	})
	return file_Qot_UpdateKL_proto_rawDescData
}

var file_Qot_UpdateKL_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Qot_UpdateKL_proto_goTypes = []any{
	(*S2C)(nil),                // 0: Qot_UpdateKL.S2C
	(*Response)(nil),           // 1: Qot_UpdateKL.Response
	(*qotcommon.Security)(nil), // 2: Qot_Common.Security
	(*qotcommon.KLine)(nil),    // 3: Qot_Common.KLine
}
var file_Qot_UpdateKL_proto_depIdxs = []int32{
	2, // 0: Qot_UpdateKL.S2C.security:type_name -> Qot_Common.Security
	3, // 1: Qot_UpdateKL.S2C.klList:type_name -> Qot_Common.KLine
	0, // 2: Qot_UpdateKL.Response.s2c:type_name -> Qot_UpdateKL.S2C
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Qot_UpdateKL_proto_init() }
func file_Qot_UpdateKL_proto_init() {
	if File_Qot_UpdateKL_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_UpdateKL_proto_rawDesc), len(file_Qot_UpdateKL_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_UpdateKL_proto_goTypes,
		DependencyIndexes: file_Qot_UpdateKL_proto_depIdxs,
		MessageInfos:      file_Qot_UpdateKL_proto_msgTypes,
	}.Build()
	File_Qot_UpdateKL_proto = out.File
	file_Qot_UpdateKL_proto_goTypes = nil
	file_Qot_UpdateKL_proto_depIdxs = nil
}
