// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: Qot_GetResearchMorningstarReport.proto

package qotgetresearchmorningstarrpt

import (
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 带更新时间的文本内容
type StringWithUpdateTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *string                `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`             // 文本内容
	UpdateTime    *int64                 `protobuf:"varint,2,opt,name=updateTime" json:"updateTime,omitempty"`      // 更新时间戳（秒）
	UpdateTimeStr *string                `protobuf:"bytes,3,opt,name=updateTimeStr" json:"updateTimeStr,omitempty"` // 更新时间字符串，格式 YYYY-MM-DD，对应市场时区
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringWithUpdateTime) Reset() {
	*x = StringWithUpdateTime{}
	mi := &file_Qot_GetResearchMorningstarReport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringWithUpdateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringWithUpdateTime) ProtoMessage() {}

func (x *StringWithUpdateTime) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetResearchMorningstarReport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringWithUpdateTime.ProtoReflect.Descriptor instead.
func (*StringWithUpdateTime) Descriptor() ([]byte, []int) {
	return file_Qot_GetResearchMorningstarReport_proto_rawDescGZIP(), []int{0}
}

func (x *StringWithUpdateTime) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

func (x *StringWithUpdateTime) GetUpdateTime() int64 {
	if x != nil && x.UpdateTime != nil {
		return *x.UpdateTime
	}
	return 0
}

func (x *StringWithUpdateTime) GetUpdateTimeStr() string {
	if x != nil && x.UpdateTimeStr != nil {
		return *x.UpdateTimeStr
	}
	return ""
}

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *qotcommon.Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"` // 股票
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetResearchMorningstarReport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetResearchMorningstarReport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetResearchMorningstarReport_proto_rawDescGZIP(), []int{1}
}

func (x *C2S) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

type S2C struct {
	state                      protoimpl.MessageState           `protogen:"open.v1"`
	RatingType                 *qotcommon.MorningstarRatingType `protobuf:"varint,1,opt,name=ratingType,enum=Qot_Common.MorningstarRatingType" json:"ratingType,omitempty"` // 评级类型（详见 Qot_Common.MorningstarRatingType 定义）
	StarRating                 *int32                           `protobuf:"varint,2,opt,name=starRating" json:"starRating,omitempty"`                                       // 晨星星级评分，取值 1-5 星
	StarUpdateTime             *int64                           `protobuf:"varint,3,opt,name=starUpdateTime" json:"starUpdateTime,omitempty"`                               // 星级更新时间戳（秒）
	StarUpdateTimeStr          *string                          `protobuf:"bytes,4,opt,name=starUpdateTimeStr" json:"starUpdateTimeStr,omitempty"`                          // 星级更新时间字符串，格式 YYYY-MM-DD，对应市场时区
	FairValue                  *float64                         `protobuf:"fixed64,5,opt,name=fairValue" json:"fairValue,omitempty"`                                        // 公允价值
	FairValueContent           *StringWithUpdateTime            `protobuf:"bytes,6,opt,name=fairValueContent" json:"fairValueContent,omitempty"`                            // 公允价值分析文本及更新时间
	EconomicMoatLabel          *string                          `protobuf:"bytes,7,opt,name=economicMoatLabel" json:"economicMoatLabel,omitempty"`                          // 护城河评级，如 Wide、Narrow、None
	EconomicMoatContent        *StringWithUpdateTime            `protobuf:"bytes,8,opt,name=economicMoatContent" json:"economicMoatContent,omitempty"`                      // 护城河分析文本及更新时间
	UncertaintyLabel           *string                          `protobuf:"bytes,9,opt,name=uncertaintyLabel" json:"uncertaintyLabel,omitempty"`                            // 不确定性评级，如 Low、Medium、High、Very High、Extreme
	UncertaintyContent         *StringWithUpdateTime            `protobuf:"bytes,10,opt,name=uncertaintyContent" json:"uncertaintyContent,omitempty"`                       // 不确定性分析文本及更新时间
	FinancialHealthLabel       *string                          `protobuf:"bytes,11,opt,name=financialHealthLabel" json:"financialHealthLabel,omitempty"`                   // 财务健康评级
	FinancialHealthContent     *StringWithUpdateTime            `protobuf:"bytes,12,opt,name=financialHealthContent" json:"financialHealthContent,omitempty"`               // 财务健康分析文本及更新时间
	AnalystReportByLine        []string                         `protobuf:"bytes,13,rep,name=analystReportByLine" json:"analystReportByLine,omitempty"`                     // 分析师署名列表，如 ["William Kerwin, CFA"]
	AnalystReportUpdateTime    *int64                           `protobuf:"varint,14,opt,name=analystReportUpdateTime" json:"analystReportUpdateTime,omitempty"`            // 分析师报告更新时间戳（秒）
	AnalystReportUpdateTimeStr *string                          `protobuf:"bytes,15,opt,name=analystReportUpdateTimeStr" json:"analystReportUpdateTimeStr,omitempty"`       // 分析师报告更新时间字符串，格式 YYYY-MM-DD，对应市场时区
	BullSay                    []*StringWithUpdateTime          `protobuf:"bytes,16,rep,name=bullSay" json:"bullSay,omitempty"`                                             // 多方观点列表
	BearSay                    []*StringWithUpdateTime          `protobuf:"bytes,17,rep,name=bearSay" json:"bearSay,omitempty"`                                             // 空方观点列表
	CapitalAllocationLabel     *string                          `protobuf:"bytes,18,opt,name=capitalAllocationLabel" json:"capitalAllocationLabel,omitempty"`               // 资本配置评级
	CapitalAllocationContent   *StringWithUpdateTime            `protobuf:"bytes,19,opt,name=capitalAllocationContent" json:"capitalAllocationContent,omitempty"`           // 资本配置分析文本及更新时间
	AnalystNoteTitle           *StringWithUpdateTime            `protobuf:"bytes,20,opt,name=analystNoteTitle" json:"analystNoteTitle,omitempty"`                           // 分析师观点标题及更新时间
	AnalystNoteContent         *StringWithUpdateTime            `protobuf:"bytes,21,opt,name=analystNoteContent" json:"analystNoteContent,omitempty"`                       // 分析师观点内容文本及更新时间
	InvestmentThesisContent    *StringWithUpdateTime            `protobuf:"bytes,22,opt,name=investmentThesisContent" json:"investmentThesisContent,omitempty"`             // 投资论点文本及更新时间
	FundamentalsContent        *StringWithUpdateTime            `protobuf:"bytes,23,opt,name=fundamentalsContent" json:"fundamentalsContent,omitempty"`                     // 基本面报告文本及更新时间
	ValuationContent           *StringWithUpdateTime            `protobuf:"bytes,24,opt,name=valuationContent" json:"valuationContent,omitempty"`                           // 估值报告文本及更新时间
	PdfUrl                     *string                          `protobuf:"bytes,25,opt,name=pdfUrl" json:"pdfUrl,omitempty"`                                               // PDF 报告下载链接
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetResearchMorningstarReport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetResearchMorningstarReport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetResearchMorningstarReport_proto_rawDescGZIP(), []int{2}
}

func (x *S2C) GetRatingType() qotcommon.MorningstarRatingType {
	if x != nil && x.RatingType != nil {
		return *x.RatingType
	}
	return qotcommon.MorningstarRatingType(0)
}

func (x *S2C) GetStarRating() int32 {
	if x != nil && x.StarRating != nil {
		return *x.StarRating
	}
	return 0
}

func (x *S2C) GetStarUpdateTime() int64 {
	if x != nil && x.StarUpdateTime != nil {
		return *x.StarUpdateTime
	}
	return 0
}

func (x *S2C) GetStarUpdateTimeStr() string {
	if x != nil && x.StarUpdateTimeStr != nil {
		return *x.StarUpdateTimeStr
	}
	return ""
}

func (x *S2C) GetFairValue() float64 {
	if x != nil && x.FairValue != nil {
		return *x.FairValue
	}
	return 0
}

func (x *S2C) GetFairValueContent() *StringWithUpdateTime {
	if x != nil {
		return x.FairValueContent
	}
	return nil
}

func (x *S2C) GetEconomicMoatLabel() string {
	if x != nil && x.EconomicMoatLabel != nil {
		return *x.EconomicMoatLabel
	}
	return ""
}

func (x *S2C) GetEconomicMoatContent() *StringWithUpdateTime {
	if x != nil {
		return x.EconomicMoatContent
	}
	return nil
}

func (x *S2C) GetUncertaintyLabel() string {
	if x != nil && x.UncertaintyLabel != nil {
		return *x.UncertaintyLabel
	}
	return ""
}

func (x *S2C) GetUncertaintyContent() *StringWithUpdateTime {
	if x != nil {
		return x.UncertaintyContent
	}
	return nil
}

func (x *S2C) GetFinancialHealthLabel() string {
	if x != nil && x.FinancialHealthLabel != nil {
		return *x.FinancialHealthLabel
	}
	return ""
}

func (x *S2C) GetFinancialHealthContent() *StringWithUpdateTime {
	if x != nil {
		return x.FinancialHealthContent
	}
	return nil
}

func (x *S2C) GetAnalystReportByLine() []string {
	if x != nil {
		return x.AnalystReportByLine
	}
	return nil
}

func (x *S2C) GetAnalystReportUpdateTime() int64 {
	if x != nil && x.AnalystReportUpdateTime != nil {
		return *x.AnalystReportUpdateTime
	}
	return 0
}

func (x *S2C) GetAnalystReportUpdateTimeStr() string {
	if x != nil && x.AnalystReportUpdateTimeStr != nil {
		return *x.AnalystReportUpdateTimeStr
	}
	return ""
}

func (x *S2C) GetBullSay() []*StringWithUpdateTime {
	if x != nil {
		return x.BullSay
	}
	return nil
}

func (x *S2C) GetBearSay() []*StringWithUpdateTime {
	if x != nil {
		return x.BearSay
	}
	return nil
}

func (x *S2C) GetCapitalAllocationLabel() string {
	if x != nil && x.CapitalAllocationLabel != nil {
		return *x.CapitalAllocationLabel
	}
	return ""
}

func (x *S2C) GetCapitalAllocationContent() *StringWithUpdateTime {
	if x != nil {
		return x.CapitalAllocationContent
	}
	return nil
}

func (x *S2C) GetAnalystNoteTitle() *StringWithUpdateTime {
	if x != nil {
		return x.AnalystNoteTitle
	}
	return nil
}

func (x *S2C) GetAnalystNoteContent() *StringWithUpdateTime {
	if x != nil {
		return x.AnalystNoteContent
	}
	return nil
}

func (x *S2C) GetInvestmentThesisContent() *StringWithUpdateTime {
	if x != nil {
		return x.InvestmentThesisContent
	}
	return nil
}

func (x *S2C) GetFundamentalsContent() *StringWithUpdateTime {
	if x != nil {
		return x.FundamentalsContent
	}
	return nil
}

func (x *S2C) GetValuationContent() *StringWithUpdateTime {
	if x != nil {
		return x.ValuationContent
	}
	return nil
}

func (x *S2C) GetPdfUrl() string {
	if x != nil && x.PdfUrl != nil {
		return *x.PdfUrl
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetResearchMorningstarReport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetResearchMorningstarReport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetResearchMorningstarReport_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` // RetType,返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetResearchMorningstarReport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetResearchMorningstarReport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetResearchMorningstarReport_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetResearchMorningstarReport_proto protoreflect.FileDescriptor

const file_Qot_GetResearchMorningstarReport_proto_rawDesc = "" +
	"\n" +
	"&Qot_GetResearchMorningstarReport.proto\x12 Qot_GetResearchMorningstarReport\x1a\x10Qot_Common.proto\"v\n" +
	"\x14StringWithUpdateTime\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x02 \x01(\x03R\n" +
	"updateTime\x12$\n" +
	"\rupdateTimeStr\x18\x03 \x01(\tR\rupdateTimeStr\"7\n" +
	"\x03C2S\x120\n" +
	"\bsecurity\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\bsecurity\"\xb0\x0e\n" +
	"\x03S2C\x12A\n" +
	"\n" +
	"ratingType\x18\x01 \x01(\x0e2!.Qot_Common.MorningstarRatingTypeR\n" +
	"ratingType\x12\x1e\n" +
	"\n" +
	"starRating\x18\x02 \x01(\x05R\n" +
	"starRating\x12&\n" +
	"\x0estarUpdateTime\x18\x03 \x01(\x03R\x0estarUpdateTime\x12,\n" +
	"\x11starUpdateTimeStr\x18\x04 \x01(\tR\x11starUpdateTimeStr\x12\x1c\n" +
	"\tfairValue\x18\x05 \x01(\x01R\tfairValue\x12b\n" +
	"\x10fairValueContent\x18\x06 \x01(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\x10fairValueContent\x12,\n" +
	"\x11economicMoatLabel\x18\a \x01(\tR\x11economicMoatLabel\x12h\n" +
	"\x13economicMoatContent\x18\b \x01(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\x13economicMoatContent\x12*\n" +
	"\x10uncertaintyLabel\x18\t \x01(\tR\x10uncertaintyLabel\x12f\n" +
	"\x12uncertaintyContent\x18\n" +
	" \x01(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\x12uncertaintyContent\x122\n" +
	"\x14financialHealthLabel\x18\v \x01(\tR\x14financialHealthLabel\x12n\n" +
	"\x16financialHealthContent\x18\f \x01(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\x16financialHealthContent\x120\n" +
	"\x13analystReportByLine\x18\r \x03(\tR\x13analystReportByLine\x128\n" +
	"\x17analystReportUpdateTime\x18\x0e \x01(\x03R\x17analystReportUpdateTime\x12>\n" +
	"\x1aanalystReportUpdateTimeStr\x18\x0f \x01(\tR\x1aanalystReportUpdateTimeStr\x12P\n" +
	"\abullSay\x18\x10 \x03(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\abullSay\x12P\n" +
	"\abearSay\x18\x11 \x03(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\abearSay\x126\n" +
	"\x16capitalAllocationLabel\x18\x12 \x01(\tR\x16capitalAllocationLabel\x12r\n" +
	"\x18capitalAllocationContent\x18\x13 \x01(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\x18capitalAllocationContent\x12b\n" +
	"\x10analystNoteTitle\x18\x14 \x01(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\x10analystNoteTitle\x12f\n" +
	"\x12analystNoteContent\x18\x15 \x01(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\x12analystNoteContent\x12p\n" +
	"\x17investmentThesisContent\x18\x16 \x01(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\x17investmentThesisContent\x12h\n" +
	"\x13fundamentalsContent\x18\x17 \x01(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\x13fundamentalsContent\x12b\n" +
	"\x10valuationContent\x18\x18 \x01(\v26.Qot_GetResearchMorningstarReport.StringWithUpdateTimeR\x10valuationContent\x12\x16\n" +
	"\x06pdfUrl\x18\x19 \x01(\tR\x06pdfUrl\"B\n" +
	"\aRequest\x127\n" +
	"\x03c2s\x18\x01 \x02(\v2%.Qot_GetResearchMorningstarReport.C2SR\x03c2s\"\x95\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x127\n" +
	"\x03s2c\x18\x04 \x01(\v2%.Qot_GetResearchMorningstarReport.S2CR\x03s2cBZ\n" +
	"\x13com.futu.openapi.pbZCgithub.com/shing1211/futuapi4go/pkg/pb/qotgetresearchmorningstarrpt"

var (
	file_Qot_GetResearchMorningstarReport_proto_rawDescOnce sync.Once
	file_Qot_GetResearchMorningstarReport_proto_rawDescData []byte
)

func file_Qot_GetResearchMorningstarReport_proto_rawDescGZIP() []byte {
	file_Qot_GetResearchMorningstarReport_proto_rawDescOnce.Do(func() {
		file_Qot_GetResearchMorningstarReport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetResearchMorningstarReport_proto_rawDesc), len(file_Qot_GetResearchMorningstarReport_proto_rawDesc)))
	})
	return file_Qot_GetResearchMorningstarReport_proto_rawDescData
}

var file_Qot_GetResearchMorningstarReport_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetResearchMorningstarReport_proto_goTypes = []any{
	(*StringWithUpdateTime)(nil),         // 0: Qot_GetResearchMorningstarReport.StringWithUpdateTime
	(*C2S)(nil),                          // 1: Qot_GetResearchMorningstarReport.C2S
	(*S2C)(nil),                          // 2: Qot_GetResearchMorningstarReport.S2C
	(*Request)(nil),                      // 3: Qot_GetResearchMorningstarReport.Request
	(*Response)(nil),                     // 4: Qot_GetResearchMorningstarReport.Response
	(*qotcommon.Security)(nil),           // 5: Qot_Common.Security
	(qotcommon.MorningstarRatingType)(0), // 6: Qot_Common.MorningstarRatingType
}
var file_Qot_GetResearchMorningstarReport_proto_depIdxs = []int32{
	5,  // 0: Qot_GetResearchMorningstarReport.C2S.security:type_name -> Qot_Common.Security
	6,  // 1: Qot_GetResearchMorningstarReport.S2C.ratingType:type_name -> Qot_Common.MorningstarRatingType
	0,  // 2: Qot_GetResearchMorningstarReport.S2C.fairValueContent:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 3: Qot_GetResearchMorningstarReport.S2C.economicMoatContent:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 4: Qot_GetResearchMorningstarReport.S2C.uncertaintyContent:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 5: Qot_GetResearchMorningstarReport.S2C.financialHealthContent:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 6: Qot_GetResearchMorningstarReport.S2C.bullSay:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 7: Qot_GetResearchMorningstarReport.S2C.bearSay:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 8: Qot_GetResearchMorningstarReport.S2C.capitalAllocationContent:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 9: Qot_GetResearchMorningstarReport.S2C.analystNoteTitle:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 10: Qot_GetResearchMorningstarReport.S2C.analystNoteContent:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 11: Qot_GetResearchMorningstarReport.S2C.investmentThesisContent:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 12: Qot_GetResearchMorningstarReport.S2C.fundamentalsContent:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	0,  // 13: Qot_GetResearchMorningstarReport.S2C.valuationContent:type_name -> Qot_GetResearchMorningstarReport.StringWithUpdateTime
	1,  // 14: Qot_GetResearchMorningstarReport.Request.c2s:type_name -> Qot_GetResearchMorningstarReport.C2S
	2,  // 15: Qot_GetResearchMorningstarReport.Response.s2c:type_name -> Qot_GetResearchMorningstarReport.S2C
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_Qot_GetResearchMorningstarReport_proto_init() }
func file_Qot_GetResearchMorningstarReport_proto_init() {
	if File_Qot_GetResearchMorningstarReport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetResearchMorningstarReport_proto_rawDesc), len(file_Qot_GetResearchMorningstarReport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetResearchMorningstarReport_proto_goTypes,
		DependencyIndexes: file_Qot_GetResearchMorningstarReport_proto_depIdxs,
		MessageInfos:      file_Qot_GetResearchMorningstarReport_proto_msgTypes,
	}.Build()
	File_Qot_GetResearchMorningstarReport_proto = out.File
	file_Qot_GetResearchMorningstarReport_proto_goTypes = nil
	file_Qot_GetResearchMorningstarReport_proto_depIdxs = nil
}
