// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: Qot_GetDividendCalendar.proto

package qotgetdividendcalendar

import (
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *int32                 `protobuf:"varint,1,req,name=market" json:"market,omitempty"`     // Qot_Common.QotMarket (支持 HK=1, US=11, MY=61, SG=31, JP=41)
	Date          *string                `protobuf:"bytes,2,req,name=date" json:"date,omitempty"`          // 查询日期, 格式"YYYY-MM-DD"
	DataFrom      *int32                 `protobuf:"varint,3,opt,name=dataFrom" json:"dataFrom,omitempty"` // 分页偏移量, 默认0
	Count         *int32                 `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`       // 返回数量, 默认不限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetDividendCalendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendCalendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendCalendar_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetMarket() int32 {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return 0
}

func (x *C2S) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

func (x *C2S) GetDataFrom() int32 {
	if x != nil && x.DataFrom != nil {
		return *x.DataFrom
	}
	return 0
}

func (x *C2S) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

// 派息日历单条记录
type DividendCalendarItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Security            *qotcommon.Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`                       // 股票
	Name                *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`                               // 股票名称
	Statement           *string                `protobuf:"bytes,3,opt,name=statement" json:"statement,omitempty"`                     // 方案说明
	RecordDate          *string                `protobuf:"bytes,4,opt,name=recordDate" json:"recordDate,omitempty"`                   // 股权登记日 ("YYYY-MM-DD")
	ExDate              *string                `protobuf:"bytes,5,opt,name=exDate" json:"exDate,omitempty"`                           // 除净日 ("YYYY-MM-DD")
	DividendPayableDate *string                `protobuf:"bytes,6,opt,name=dividendPayableDate" json:"dividendPayableDate,omitempty"` // 派息日 ("YYYY-MM-DD")
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DividendCalendarItem) Reset() {
	*x = DividendCalendarItem{}
	mi := &file_Qot_GetDividendCalendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DividendCalendarItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DividendCalendarItem) ProtoMessage() {}

func (x *DividendCalendarItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendCalendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DividendCalendarItem.ProtoReflect.Descriptor instead.
func (*DividendCalendarItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendCalendar_proto_rawDescGZIP(), []int{1}
}

func (x *DividendCalendarItem) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *DividendCalendarItem) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DividendCalendarItem) GetStatement() string {
	if x != nil && x.Statement != nil {
		return *x.Statement
	}
	return ""
}

func (x *DividendCalendarItem) GetRecordDate() string {
	if x != nil && x.RecordDate != nil {
		return *x.RecordDate
	}
	return ""
}

func (x *DividendCalendarItem) GetExDate() string {
	if x != nil && x.ExDate != nil {
		return *x.ExDate
	}
	return ""
}

func (x *DividendCalendarItem) GetDividendPayableDate() string {
	if x != nil && x.DividendPayableDate != nil {
		return *x.DividendPayableDate
	}
	return ""
}

type S2C struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ItemList      []*DividendCalendarItem `protobuf:"bytes,1,rep,name=itemList" json:"itemList,omitempty"`  // 派息列表
	AllCount      *int32                  `protobuf:"varint,2,opt,name=allCount" json:"allCount,omitempty"` // 该日期下的总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetDividendCalendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendCalendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendCalendar_proto_rawDescGZIP(), []int{2}
}

func (x *S2C) GetItemList() []*DividendCalendarItem {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *S2C) GetAllCount() int32 {
	if x != nil && x.AllCount != nil {
		return *x.AllCount
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetDividendCalendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendCalendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendCalendar_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` // RetType, 返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetDividendCalendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendCalendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendCalendar_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetDividendCalendar_proto protoreflect.FileDescriptor

const file_Qot_GetDividendCalendar_proto_rawDesc = "" +
	"\n" +
	"\x1dQot_GetDividendCalendar.proto\x12\x17Qot_GetDividendCalendar\x1a\x10Qot_Common.proto\"c\n" +
	"\x03C2S\x12\x16\n" +
	"\x06market\x18\x01 \x02(\x05R\x06market\x12\x12\n" +
	"\x04date\x18\x02 \x02(\tR\x04date\x12\x1a\n" +
	"\bdataFrom\x18\x03 \x01(\x05R\bdataFrom\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"\xe4\x01\n" +
	"\x14DividendCalendarItem\x120\n" +
	"\bsecurity\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tstatement\x18\x03 \x01(\tR\tstatement\x12\x1e\n" +
	"\n" +
	"recordDate\x18\x04 \x01(\tR\n" +
	"recordDate\x12\x16\n" +
	"\x06exDate\x18\x05 \x01(\tR\x06exDate\x120\n" +
	"\x13dividendPayableDate\x18\x06 \x01(\tR\x13dividendPayableDate\"l\n" +
	"\x03S2C\x12I\n" +
	"\bitemList\x18\x01 \x03(\v2-.Qot_GetDividendCalendar.DividendCalendarItemR\bitemList\x12\x1a\n" +
	"\ballCount\x18\x02 \x01(\x05R\ballCount\"9\n" +
	"\aRequest\x12.\n" +
	"\x03c2s\x18\x01 \x02(\v2\x1c.Qot_GetDividendCalendar.C2SR\x03c2s\"\x8c\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12.\n" +
	"\x03s2c\x18\x04 \x01(\v2\x1c.Qot_GetDividendCalendar.S2CR\x03s2cBT\n" +
	"\x13com.futu.openapi.pbZ=github.com/shing1211/futuapi4go/pkg/pb/qotgetdividendcalendar"

var (
	file_Qot_GetDividendCalendar_proto_rawDescOnce sync.Once
	file_Qot_GetDividendCalendar_proto_rawDescData []byte
)

func file_Qot_GetDividendCalendar_proto_rawDescGZIP() []byte {
	file_Qot_GetDividendCalendar_proto_rawDescOnce.Do(func() {
		file_Qot_GetDividendCalendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetDividendCalendar_proto_rawDesc), len(file_Qot_GetDividendCalendar_proto_rawDesc)))
	})
	return file_Qot_GetDividendCalendar_proto_rawDescData
}

var file_Qot_GetDividendCalendar_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetDividendCalendar_proto_goTypes = []any{
	(*C2S)(nil),                  // 0: Qot_GetDividendCalendar.C2S
	(*DividendCalendarItem)(nil), // 1: Qot_GetDividendCalendar.DividendCalendarItem
	(*S2C)(nil),                  // 2: Qot_GetDividendCalendar.S2C
	(*Request)(nil),              // 3: Qot_GetDividendCalendar.Request
	(*Response)(nil),             // 4: Qot_GetDividendCalendar.Response
	(*qotcommon.Security)(nil),   // 5: Qot_Common.Security
}
var file_Qot_GetDividendCalendar_proto_depIdxs = []int32{
	5, // 0: Qot_GetDividendCalendar.DividendCalendarItem.security:type_name -> Qot_Common.Security
	1, // 1: Qot_GetDividendCalendar.S2C.itemList:type_name -> Qot_GetDividendCalendar.DividendCalendarItem
	0, // 2: Qot_GetDividendCalendar.Request.c2s:type_name -> Qot_GetDividendCalendar.C2S
	2, // 3: Qot_GetDividendCalendar.Response.s2c:type_name -> Qot_GetDividendCalendar.S2C
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Qot_GetDividendCalendar_proto_init() }
func file_Qot_GetDividendCalendar_proto_init() {
	if File_Qot_GetDividendCalendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetDividendCalendar_proto_rawDesc), len(file_Qot_GetDividendCalendar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetDividendCalendar_proto_goTypes,
		DependencyIndexes: file_Qot_GetDividendCalendar_proto_depIdxs,
		MessageInfos:      file_Qot_GetDividendCalendar_proto_msgTypes,
	}.Build()
	File_Qot_GetDividendCalendar_proto = out.File
	file_Qot_GetDividendCalendar_proto_goTypes = nil
	file_Qot_GetDividendCalendar_proto_depIdxs = nil
}
