// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: Qot_GetIndustrialPlateStock.proto

package qotgetindustrialplatestock

import (
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 排序字段
type SortField int32

const (
	SortField_SortField_Code       SortField = 0 //代码(默认)
	SortField_SortField_ChangeRate SortField = 1 //涨跌幅
	SortField_SortField_Turnover   SortField = 2 //成交额
	SortField_SortField_Volume     SortField = 3 //成交量
	SortField_SortField_MarketVal  SortField = 4 //市值
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0: "SortField_Code",
		1: "SortField_ChangeRate",
		2: "SortField_Turnover",
		3: "SortField_Volume",
		4: "SortField_MarketVal",
	}
	SortField_value = map[string]int32{
		"SortField_Code":       0,
		"SortField_ChangeRate": 1,
		"SortField_Turnover":   2,
		"SortField_Volume":     3,
		"SortField_MarketVal":  4,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetIndustrialPlateStock_proto_enumTypes[0].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_Qot_GetIndustrialPlateStock_proto_enumTypes[0]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SortField) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SortField(num)
	return nil
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetIndustrialPlateStock_proto_rawDescGZIP(), []int{0}
}

type StockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *qotcommon.Security    `protobuf:"bytes,1,opt,name=security" json:"security,omitempty"` //股票
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`         //股票名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfo) Reset() {
	*x = StockInfo{}
	mi := &file_Qot_GetIndustrialPlateStock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfo) ProtoMessage() {}

func (x *StockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetIndustrialPlateStock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfo.ProtoReflect.Descriptor instead.
func (*StockInfo) Descriptor() ([]byte, []int) {
	return file_Qot_GetIndustrialPlateStock_proto_rawDescGZIP(), []int{0}
}

func (x *StockInfo) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *StockInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       *int64                 `protobuf:"varint,1,opt,name=chainId" json:"chainId,omitempty"`       //产业链ID (与plateId二选一，plateId优先)
	PlateId       *int64                 `protobuf:"varint,2,opt,name=plateId" json:"plateId,omitempty"`       //产业板块ID (优先使用)
	MarketList    []int32                `protobuf:"varint,3,rep,name=marketList" json:"marketList,omitempty"` //Qot_Common.QotMarket 市场筛选(支持HK/US/CN/JP/SG/MY，不传默认全部)
	SortField     *int32                 `protobuf:"varint,4,opt,name=sortField" json:"sortField,omitempty"`   //SortField，排序字段，默认MarketVal(市值)
	Ascend        *bool                  `protobuf:"varint,5,opt,name=ascend" json:"ascend,omitempty"`         //升序true/降序false，默认false(降序)
	Count         *int32                 `protobuf:"varint,6,opt,name=count" json:"count,omitempty"`           //每页数量 [1,200], 默认50
	Page          *string                `protobuf:"bytes,7,opt,name=page" json:"page,omitempty"`              //翻页标记，首次不传，后续带上S2C返回的page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetIndustrialPlateStock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetIndustrialPlateStock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetIndustrialPlateStock_proto_rawDescGZIP(), []int{1}
}

func (x *C2S) GetChainId() int64 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *C2S) GetPlateId() int64 {
	if x != nil && x.PlateId != nil {
		return *x.PlateId
	}
	return 0
}

func (x *C2S) GetMarketList() []int32 {
	if x != nil {
		return x.MarketList
	}
	return nil
}

func (x *C2S) GetSortField() int32 {
	if x != nil && x.SortField != nil {
		return *x.SortField
	}
	return 0
}

func (x *C2S) GetAscend() bool {
	if x != nil && x.Ascend != nil {
		return *x.Ascend
	}
	return false
}

func (x *C2S) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *C2S) GetPage() string {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return ""
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockList     []*StockInfo           `protobuf:"bytes,1,rep,name=stockList" json:"stockList,omitempty"` //成分股列表
	Page          *string                `protobuf:"bytes,2,opt,name=page" json:"page,omitempty"`           //翻页标记，有更多数据时返回
	AllCount      *int32                 `protobuf:"varint,3,opt,name=allCount" json:"allCount,omitempty"`  //总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetIndustrialPlateStock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetIndustrialPlateStock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetIndustrialPlateStock_proto_rawDescGZIP(), []int{2}
}

func (x *S2C) GetStockList() []*StockInfo {
	if x != nil {
		return x.StockList
	}
	return nil
}

func (x *S2C) GetPage() string {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return ""
}

func (x *S2C) GetAllCount() int32 {
	if x != nil && x.AllCount != nil {
		return *x.AllCount
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetIndustrialPlateStock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetIndustrialPlateStock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetIndustrialPlateStock_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetIndustrialPlateStock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetIndustrialPlateStock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetIndustrialPlateStock_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetIndustrialPlateStock_proto protoreflect.FileDescriptor

const file_Qot_GetIndustrialPlateStock_proto_rawDesc = "" +
	"\n" +
	"!Qot_GetIndustrialPlateStock.proto\x12\x1bQot_GetIndustrialPlateStock\x1a\x10Qot_Common.proto\"Q\n" +
	"\tStockInfo\x120\n" +
	"\bsecurity\x18\x01 \x01(\v2\x14.Qot_Common.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb9\x01\n" +
	"\x03C2S\x12\x18\n" +
	"\achainId\x18\x01 \x01(\x03R\achainId\x12\x18\n" +
	"\aplateId\x18\x02 \x01(\x03R\aplateId\x12\x1e\n" +
	"\n" +
	"marketList\x18\x03 \x03(\x05R\n" +
	"marketList\x12\x1c\n" +
	"\tsortField\x18\x04 \x01(\x05R\tsortField\x12\x16\n" +
	"\x06ascend\x18\x05 \x01(\bR\x06ascend\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x12\x12\n" +
	"\x04page\x18\a \x01(\tR\x04page\"{\n" +
	"\x03S2C\x12D\n" +
	"\tstockList\x18\x01 \x03(\v2&.Qot_GetIndustrialPlateStock.StockInfoR\tstockList\x12\x12\n" +
	"\x04page\x18\x02 \x01(\tR\x04page\x12\x1a\n" +
	"\ballCount\x18\x03 \x01(\x05R\ballCount\"=\n" +
	"\aRequest\x122\n" +
	"\x03c2s\x18\x01 \x02(\v2 .Qot_GetIndustrialPlateStock.C2SR\x03c2s\"\x90\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x122\n" +
	"\x03s2c\x18\x04 \x01(\v2 .Qot_GetIndustrialPlateStock.S2CR\x03s2c*\x80\x01\n" +
	"\tSortField\x12\x12\n" +
	"\x0eSortField_Code\x10\x00\x12\x18\n" +
	"\x14SortField_ChangeRate\x10\x01\x12\x16\n" +
	"\x12SortField_Turnover\x10\x02\x12\x14\n" +
	"\x10SortField_Volume\x10\x03\x12\x17\n" +
	"\x13SortField_MarketVal\x10\x04BX\n" +
	"\x13com.futu.openapi.pbZAgithub.com/shing1211/futuapi4go/pkg/pb/qotgetindustrialplatestock"

var (
	file_Qot_GetIndustrialPlateStock_proto_rawDescOnce sync.Once
	file_Qot_GetIndustrialPlateStock_proto_rawDescData []byte
)

func file_Qot_GetIndustrialPlateStock_proto_rawDescGZIP() []byte {
	file_Qot_GetIndustrialPlateStock_proto_rawDescOnce.Do(func() {
		file_Qot_GetIndustrialPlateStock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetIndustrialPlateStock_proto_rawDesc), len(file_Qot_GetIndustrialPlateStock_proto_rawDesc)))
	})
	return file_Qot_GetIndustrialPlateStock_proto_rawDescData
}

var file_Qot_GetIndustrialPlateStock_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Qot_GetIndustrialPlateStock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Qot_GetIndustrialPlateStock_proto_goTypes = []any{
	(SortField)(0),             // 0: Qot_GetIndustrialPlateStock.SortField
	(*StockInfo)(nil),          // 1: Qot_GetIndustrialPlateStock.StockInfo
	(*C2S)(nil),                // 2: Qot_GetIndustrialPlateStock.C2S
	(*S2C)(nil),                // 3: Qot_GetIndustrialPlateStock.S2C
	(*Request)(nil),            // 4: Qot_GetIndustrialPlateStock.Request
	(*Response)(nil),           // 5: Qot_GetIndustrialPlateStock.Response
	(*qotcommon.Security)(nil), // 6: Qot_Common.Security
}
var file_Qot_GetIndustrialPlateStock_proto_depIdxs = []int32{
	6, // 0: Qot_GetIndustrialPlateStock.StockInfo.security:type_name -> Qot_Common.Security
	1, // 1: Qot_GetIndustrialPlateStock.S2C.stockList:type_name -> Qot_GetIndustrialPlateStock.StockInfo
	2, // 2: Qot_GetIndustrialPlateStock.Request.c2s:type_name -> Qot_GetIndustrialPlateStock.C2S
	3, // 3: Qot_GetIndustrialPlateStock.Response.s2c:type_name -> Qot_GetIndustrialPlateStock.S2C
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Qot_GetIndustrialPlateStock_proto_init() }
func file_Qot_GetIndustrialPlateStock_proto_init() {
	if File_Qot_GetIndustrialPlateStock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetIndustrialPlateStock_proto_rawDesc), len(file_Qot_GetIndustrialPlateStock_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetIndustrialPlateStock_proto_goTypes,
		DependencyIndexes: file_Qot_GetIndustrialPlateStock_proto_depIdxs,
		EnumInfos:         file_Qot_GetIndustrialPlateStock_proto_enumTypes,
		MessageInfos:      file_Qot_GetIndustrialPlateStock_proto_msgTypes,
	}.Build()
	File_Qot_GetIndustrialPlateStock_proto = out.File
	file_Qot_GetIndustrialPlateStock_proto_goTypes = nil
	file_Qot_GetIndustrialPlateStock_proto_depIdxs = nil
}
