// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: Qot_GetFinancialsEarningsPriceMove.proto

package qotgetfinancialsearnpricemove

import (
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Security      *qotcommon.Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`        // 股票
	PeriodCount   *int32                 `protobuf:"varint,2,opt,name=periodCount" json:"periodCount,omitempty"` // 财报周期数量，默认 10，取值范围 [1, 50]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *C2S) GetPeriodCount() int32 {
	if x != nil && x.PeriodCount != nil {
		return *x.PeriodCount
	}
	return 0
}

// 单个交易日的股价行情数据
type PricePerformanceRow struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TradingDay     *int64                 `protobuf:"varint,1,opt,name=tradingDay" json:"tradingDay,omitempty"`          // 交易日时间戳（秒）
	TradingDayStr  *string                `protobuf:"bytes,2,opt,name=tradingDayStr" json:"tradingDayStr,omitempty"`     // 交易日字符串，格式 YYYY-MM-DD，对应市场时区
	ClosePrice     *float64               `protobuf:"fixed64,3,opt,name=closePrice" json:"closePrice,omitempty"`         // 收盘价
	OpenPrice      *float64               `protobuf:"fixed64,4,opt,name=openPrice" json:"openPrice,omitempty"`           // 开盘价
	HighestPrice   *float64               `protobuf:"fixed64,5,opt,name=highestPrice" json:"highestPrice,omitempty"`     // 最高价
	LowestPrice    *float64               `protobuf:"fixed64,6,opt,name=lowestPrice" json:"lowestPrice,omitempty"`       // 最低价
	LastClosePrice *float64               `protobuf:"fixed64,7,opt,name=lastClosePrice" json:"lastClosePrice,omitempty"` // 昨收价
	OptionIV       *float64               `protobuf:"fixed64,8,opt,name=optionIV" json:"optionIV,omitempty"`             // 期权隐含波动率（百分号前的值，如 12.34 表示 12.34%）
	OptionHV       *float64               `protobuf:"fixed64,9,opt,name=optionHV" json:"optionHV,omitempty"`             // 期权历史波动率（百分号前的值，如 12.34 表示 12.34%）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PricePerformanceRow) Reset() {
	*x = PricePerformanceRow{}
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricePerformanceRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricePerformanceRow) ProtoMessage() {}

func (x *PricePerformanceRow) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricePerformanceRow.ProtoReflect.Descriptor instead.
func (*PricePerformanceRow) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescGZIP(), []int{1}
}

func (x *PricePerformanceRow) GetTradingDay() int64 {
	if x != nil && x.TradingDay != nil {
		return *x.TradingDay
	}
	return 0
}

func (x *PricePerformanceRow) GetTradingDayStr() string {
	if x != nil && x.TradingDayStr != nil {
		return *x.TradingDayStr
	}
	return ""
}

func (x *PricePerformanceRow) GetClosePrice() float64 {
	if x != nil && x.ClosePrice != nil {
		return *x.ClosePrice
	}
	return 0
}

func (x *PricePerformanceRow) GetOpenPrice() float64 {
	if x != nil && x.OpenPrice != nil {
		return *x.OpenPrice
	}
	return 0
}

func (x *PricePerformanceRow) GetHighestPrice() float64 {
	if x != nil && x.HighestPrice != nil {
		return *x.HighestPrice
	}
	return 0
}

func (x *PricePerformanceRow) GetLowestPrice() float64 {
	if x != nil && x.LowestPrice != nil {
		return *x.LowestPrice
	}
	return 0
}

func (x *PricePerformanceRow) GetLastClosePrice() float64 {
	if x != nil && x.LastClosePrice != nil {
		return *x.LastClosePrice
	}
	return 0
}

func (x *PricePerformanceRow) GetOptionIV() float64 {
	if x != nil && x.OptionIV != nil {
		return *x.OptionIV
	}
	return 0
}

func (x *PricePerformanceRow) GetOptionHV() float64 {
	if x != nil && x.OptionHV != nil {
		return *x.OptionHV
	}
	return 0
}

// 单期财报周期的行情数据，包含财报元信息及财报日前后若干交易日的价格序列
type ReportCycleQuote struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	FiscalYear       *int32                         `protobuf:"varint,1,opt,name=fiscalYear" json:"fiscalYear,omitempty"`                               // 财务年度，如 2024
	FinancialType    *int32                         `protobuf:"varint,2,opt,name=financialType" json:"financialType,omitempty"`                         // 财报类型，详见 Qot_Common.F10Type 定义
	PeriodText       *string                        `protobuf:"bytes,3,opt,name=periodText" json:"periodText,omitempty"`                                // 财报周期，如 "2024/Q3"、"2024/FY"
	PubTradingDay    *int64                         `protobuf:"varint,4,opt,name=pubTradingDay" json:"pubTradingDay,omitempty"`                         // 财报发布对应的交易日时间戳（秒）
	PubTradingDayStr *string                        `protobuf:"bytes,5,opt,name=pubTradingDayStr" json:"pubTradingDayStr,omitempty"`                    // 财报发布交易日字符串，格式 YYYY-MM-DD，对应市场时区
	PubType          *qotcommon.EarningsPubTimeType `protobuf:"varint,6,opt,name=pubType,enum=Qot_Common.EarningsPubTimeType" json:"pubType,omitempty"` // 财报发布时间类型，详见 Qot_Common.EarningsPubTimeType 定义
	PriceInfoIndex   *int32                         `protobuf:"varint,7,opt,name=priceInfoIndex" json:"priceInfoIndex,omitempty"`                       // itemList 中财报发布当日所在的下标（0-based）；-1 表示无数据
	ItemList         []*PricePerformanceRow         `protobuf:"bytes,8,rep,name=itemList" json:"itemList,omitempty"`                                    // 财报日前后的交易日行情列表，按时间升序排列
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportCycleQuote) Reset() {
	*x = ReportCycleQuote{}
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCycleQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCycleQuote) ProtoMessage() {}

func (x *ReportCycleQuote) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCycleQuote.ProtoReflect.Descriptor instead.
func (*ReportCycleQuote) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescGZIP(), []int{2}
}

func (x *ReportCycleQuote) GetFiscalYear() int32 {
	if x != nil && x.FiscalYear != nil {
		return *x.FiscalYear
	}
	return 0
}

func (x *ReportCycleQuote) GetFinancialType() int32 {
	if x != nil && x.FinancialType != nil {
		return *x.FinancialType
	}
	return 0
}

func (x *ReportCycleQuote) GetPeriodText() string {
	if x != nil && x.PeriodText != nil {
		return *x.PeriodText
	}
	return ""
}

func (x *ReportCycleQuote) GetPubTradingDay() int64 {
	if x != nil && x.PubTradingDay != nil {
		return *x.PubTradingDay
	}
	return 0
}

func (x *ReportCycleQuote) GetPubTradingDayStr() string {
	if x != nil && x.PubTradingDayStr != nil {
		return *x.PubTradingDayStr
	}
	return ""
}

func (x *ReportCycleQuote) GetPubType() qotcommon.EarningsPubTimeType {
	if x != nil && x.PubType != nil {
		return *x.PubType
	}
	return qotcommon.EarningsPubTimeType(0)
}

func (x *ReportCycleQuote) GetPriceInfoIndex() int32 {
	if x != nil && x.PriceInfoIndex != nil {
		return *x.PriceInfoIndex
	}
	return 0
}

func (x *ReportCycleQuote) GetItemList() []*PricePerformanceRow {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetailList    []*ReportCycleQuote    `protobuf:"bytes,1,rep,name=detailList" json:"detailList,omitempty"` // 各财报周期的详细行情数据列表，按财报发布日降序排列
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescGZIP(), []int{3}
}

func (x *S2C) GetDetailList() []*ReportCycleQuote {
	if x != nil {
		return x.DetailList
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` // 返回结果类型，参见 Common.RetType，0=成功，负数=失败
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`             // 返回结果描述
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`          // 错误码，失败时有效
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`                   // 响应数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetFinancialsEarningsPriceMove_proto protoreflect.FileDescriptor

const file_Qot_GetFinancialsEarningsPriceMove_proto_rawDesc = "" +
	"\n" +
	"(Qot_GetFinancialsEarningsPriceMove.proto\x12\"Qot_GetFinancialsEarningsPriceMove\x1a\x10Qot_Common.proto\"Y\n" +
	"\x03C2S\x120\n" +
	"\bsecurity\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\bsecurity\x12 \n" +
	"\vperiodCount\x18\x02 \x01(\x05R\vperiodCount\"\xbf\x02\n" +
	"\x13PricePerformanceRow\x12\x1e\n" +
	"\n" +
	"tradingDay\x18\x01 \x01(\x03R\n" +
	"tradingDay\x12$\n" +
	"\rtradingDayStr\x18\x02 \x01(\tR\rtradingDayStr\x12\x1e\n" +
	"\n" +
	"closePrice\x18\x03 \x01(\x01R\n" +
	"closePrice\x12\x1c\n" +
	"\topenPrice\x18\x04 \x01(\x01R\topenPrice\x12\"\n" +
	"\fhighestPrice\x18\x05 \x01(\x01R\fhighestPrice\x12 \n" +
	"\vlowestPrice\x18\x06 \x01(\x01R\vlowestPrice\x12&\n" +
	"\x0elastClosePrice\x18\a \x01(\x01R\x0elastClosePrice\x12\x1a\n" +
	"\boptionIV\x18\b \x01(\x01R\boptionIV\x12\x1a\n" +
	"\boptionHV\x18\t \x01(\x01R\boptionHV\"\x82\x03\n" +
	"\x10ReportCycleQuote\x12\x1e\n" +
	"\n" +
	"fiscalYear\x18\x01 \x01(\x05R\n" +
	"fiscalYear\x12$\n" +
	"\rfinancialType\x18\x02 \x01(\x05R\rfinancialType\x12\x1e\n" +
	"\n" +
	"periodText\x18\x03 \x01(\tR\n" +
	"periodText\x12$\n" +
	"\rpubTradingDay\x18\x04 \x01(\x03R\rpubTradingDay\x12*\n" +
	"\x10pubTradingDayStr\x18\x05 \x01(\tR\x10pubTradingDayStr\x129\n" +
	"\apubType\x18\x06 \x01(\x0e2\x1f.Qot_Common.EarningsPubTimeTypeR\apubType\x12&\n" +
	"\x0epriceInfoIndex\x18\a \x01(\x05R\x0epriceInfoIndex\x12S\n" +
	"\bitemList\x18\b \x03(\v27.Qot_GetFinancialsEarningsPriceMove.PricePerformanceRowR\bitemList\"[\n" +
	"\x03S2C\x12T\n" +
	"\n" +
	"detailList\x18\x01 \x03(\v24.Qot_GetFinancialsEarningsPriceMove.ReportCycleQuoteR\n" +
	"detailList\"D\n" +
	"\aRequest\x129\n" +
	"\x03c2s\x18\x01 \x02(\v2'.Qot_GetFinancialsEarningsPriceMove.C2SR\x03c2s\"\x97\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x129\n" +
	"\x03s2c\x18\x04 \x01(\v2'.Qot_GetFinancialsEarningsPriceMove.S2CR\x03s2cB[\n" +
	"\x13com.futu.openapi.pbZDgithub.com/shing1211/futuapi4go/pkg/pb/qotgetfinancialsearnpricemove"

var (
	file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescOnce sync.Once
	file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescData []byte
)

func file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescGZIP() []byte {
	file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescOnce.Do(func() {
		file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetFinancialsEarningsPriceMove_proto_rawDesc), len(file_Qot_GetFinancialsEarningsPriceMove_proto_rawDesc)))
	})
	return file_Qot_GetFinancialsEarningsPriceMove_proto_rawDescData
}

var file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Qot_GetFinancialsEarningsPriceMove_proto_goTypes = []any{
	(*C2S)(nil),                        // 0: Qot_GetFinancialsEarningsPriceMove.C2S
	(*PricePerformanceRow)(nil),        // 1: Qot_GetFinancialsEarningsPriceMove.PricePerformanceRow
	(*ReportCycleQuote)(nil),           // 2: Qot_GetFinancialsEarningsPriceMove.ReportCycleQuote
	(*S2C)(nil),                        // 3: Qot_GetFinancialsEarningsPriceMove.S2C
	(*Request)(nil),                    // 4: Qot_GetFinancialsEarningsPriceMove.Request
	(*Response)(nil),                   // 5: Qot_GetFinancialsEarningsPriceMove.Response
	(*qotcommon.Security)(nil),         // 6: Qot_Common.Security
	(qotcommon.EarningsPubTimeType)(0), // 7: Qot_Common.EarningsPubTimeType
}
var file_Qot_GetFinancialsEarningsPriceMove_proto_depIdxs = []int32{
	6, // 0: Qot_GetFinancialsEarningsPriceMove.C2S.security:type_name -> Qot_Common.Security
	7, // 1: Qot_GetFinancialsEarningsPriceMove.ReportCycleQuote.pubType:type_name -> Qot_Common.EarningsPubTimeType
	1, // 2: Qot_GetFinancialsEarningsPriceMove.ReportCycleQuote.itemList:type_name -> Qot_GetFinancialsEarningsPriceMove.PricePerformanceRow
	2, // 3: Qot_GetFinancialsEarningsPriceMove.S2C.detailList:type_name -> Qot_GetFinancialsEarningsPriceMove.ReportCycleQuote
	0, // 4: Qot_GetFinancialsEarningsPriceMove.Request.c2s:type_name -> Qot_GetFinancialsEarningsPriceMove.C2S
	3, // 5: Qot_GetFinancialsEarningsPriceMove.Response.s2c:type_name -> Qot_GetFinancialsEarningsPriceMove.S2C
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_Qot_GetFinancialsEarningsPriceMove_proto_init() }
func file_Qot_GetFinancialsEarningsPriceMove_proto_init() {
	if File_Qot_GetFinancialsEarningsPriceMove_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetFinancialsEarningsPriceMove_proto_rawDesc), len(file_Qot_GetFinancialsEarningsPriceMove_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetFinancialsEarningsPriceMove_proto_goTypes,
		DependencyIndexes: file_Qot_GetFinancialsEarningsPriceMove_proto_depIdxs,
		MessageInfos:      file_Qot_GetFinancialsEarningsPriceMove_proto_msgTypes,
	}.Build()
	File_Qot_GetFinancialsEarningsPriceMove_proto = out.File
	file_Qot_GetFinancialsEarningsPriceMove_proto_goTypes = nil
	file_Qot_GetFinancialsEarningsPriceMove_proto_depIdxs = nil
}
