// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: Trd_PlaceComboOrder.proto

package trdplacecomboorder

import (
	common "github.com/shing1211/futuapi4go/pkg/pb/common"
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	trdcommon "github.com/shing1211/futuapi4go/pkg/pb/trdcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketID      *common.PacketID       `protobuf:"bytes,1,req,name=packetID" json:"packetID,omitempty"`        //交易写操作防重放攻击
	Header        *trdcommon.TrdHeader   `protobuf:"bytes,2,req,name=header" json:"header,omitempty"`            //交易公共参数头
	ComboLegs     []*qotcommon.ComboLeg  `protobuf:"bytes,3,rep,name=comboLegs" json:"comboLegs,omitempty"`      //组合的腿信息
	Qty           *float64               `protobuf:"fixed64,4,req,name=qty" json:"qty,omitempty"`                //数量，实际数量为 qty * 腿的 qty_ratio
	Price         *float64               `protobuf:"fixed64,5,opt,name=price" json:"price,omitempty"`            //价格
	OrderType     *int32                 `protobuf:"varint,6,req,name=orderType" json:"orderType,omitempty"`     //订单类型, 参见Trd_Common.OrderType的枚举定义
	TimeInForce   *int32                 `protobuf:"varint,7,opt,name=timeInForce" json:"timeInForce,omitempty"` //订单有效期限，参见TrdCommon_TimeInForce的枚举定义
	ExpireTime    *string                `protobuf:"bytes,8,opt,name=expireTime" json:"expireTime,omitempty"`    //订单过期时间，timeInForce 为 GTD 时有效
	Remark        *string                `protobuf:"bytes,9,opt,name=remark" json:"remark,omitempty"`            //用户备注字符串，最多只能传64字节。可用于标识订单唯一信息等，下单填上，订单结构就会带上。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Trd_PlaceComboOrder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_PlaceComboOrder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Trd_PlaceComboOrder_proto_rawDescGZIP(), []int{0}
}

func (x *C2S) GetPacketID() *common.PacketID {
	if x != nil {
		return x.PacketID
	}
	return nil
}

func (x *C2S) GetHeader() *trdcommon.TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *C2S) GetComboLegs() []*qotcommon.ComboLeg {
	if x != nil {
		return x.ComboLegs
	}
	return nil
}

func (x *C2S) GetQty() float64 {
	if x != nil && x.Qty != nil {
		return *x.Qty
	}
	return 0
}

func (x *C2S) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *C2S) GetOrderType() int32 {
	if x != nil && x.OrderType != nil {
		return *x.OrderType
	}
	return 0
}

func (x *C2S) GetTimeInForce() int32 {
	if x != nil && x.TimeInForce != nil {
		return *x.TimeInForce
	}
	return 0
}

func (x *C2S) GetExpireTime() string {
	if x != nil && x.ExpireTime != nil {
		return *x.ExpireTime
	}
	return ""
}

func (x *C2S) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *trdcommon.TrdHeader   `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`       //交易公共参数头
	OrderIDEx     *string                `protobuf:"bytes,2,opt,name=orderIDEx" json:"orderIDEx,omitempty"` //表示服务器订单id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Trd_PlaceComboOrder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_PlaceComboOrder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Trd_PlaceComboOrder_proto_rawDescGZIP(), []int{1}
}

func (x *S2C) GetHeader() *trdcommon.TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *S2C) GetOrderIDEx() string {
	if x != nil && x.OrderIDEx != nil {
		return *x.OrderIDEx
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Trd_PlaceComboOrder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_PlaceComboOrder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Trd_PlaceComboOrder_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType       *int32  `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg        *string `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32  `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C    `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Trd_PlaceComboOrder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Trd_PlaceComboOrder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Trd_PlaceComboOrder_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Trd_PlaceComboOrder_proto protoreflect.FileDescriptor

const file_Trd_PlaceComboOrder_proto_rawDesc = "" +
	"\n" +
	"\x19Trd_PlaceComboOrder.proto\x12\x13Trd_PlaceComboOrder\x1a\fCommon.proto\x1a\x10Trd_Common.proto\x1a\x10Qot_Common.proto\"\xb6\x02\n" +
	"\x03C2S\x12,\n" +
	"\bpacketID\x18\x01 \x02(\v2\x10.Common.PacketIDR\bpacketID\x12-\n" +
	"\x06header\x18\x02 \x02(\v2\x15.Trd_Common.TrdHeaderR\x06header\x122\n" +
	"\tcomboLegs\x18\x03 \x03(\v2\x14.Qot_Common.ComboLegR\tcomboLegs\x12\x10\n" +
	"\x03qty\x18\x04 \x02(\x01R\x03qty\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1c\n" +
	"\torderType\x18\x06 \x02(\x05R\torderType\x12 \n" +
	"\vtimeInForce\x18\a \x01(\x05R\vtimeInForce\x12\x1e\n" +
	"\n" +
	"expireTime\x18\b \x01(\tR\n" +
	"expireTime\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\"R\n" +
	"\x03S2C\x12-\n" +
	"\x06header\x18\x01 \x02(\v2\x15.Trd_Common.TrdHeaderR\x06header\x12\x1c\n" +
	"\torderIDEx\x18\x02 \x01(\tR\torderIDEx\"5\n" +
	"\aRequest\x12*\n" +
	"\x03c2s\x18\x01 \x02(\v2\x18.Trd_PlaceComboOrder.C2SR\x03c2s\"\x88\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12*\n" +
	"\x03s2c\x18\x04 \x01(\v2\x18.Trd_PlaceComboOrder.S2CR\x03s2cBP\n" +
	"\x13com.futu.openapi.pbZ9github.com/shing1211/futuapi4go/pkg/pb/trdplacecomboorder"

var (
	file_Trd_PlaceComboOrder_proto_rawDescOnce sync.Once
	file_Trd_PlaceComboOrder_proto_rawDescData []byte
)

func file_Trd_PlaceComboOrder_proto_rawDescGZIP() []byte {
	file_Trd_PlaceComboOrder_proto_rawDescOnce.Do(func() {
		file_Trd_PlaceComboOrder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Trd_PlaceComboOrder_proto_rawDesc), len(file_Trd_PlaceComboOrder_proto_rawDesc)))
	})
	return file_Trd_PlaceComboOrder_proto_rawDescData
}

var file_Trd_PlaceComboOrder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Trd_PlaceComboOrder_proto_goTypes = []any{
	(*C2S)(nil),                 // 0: Trd_PlaceComboOrder.C2S
	(*S2C)(nil),                 // 1: Trd_PlaceComboOrder.S2C
	(*Request)(nil),             // 2: Trd_PlaceComboOrder.Request
	(*Response)(nil),            // 3: Trd_PlaceComboOrder.Response
	(*common.PacketID)(nil),     // 4: Common.PacketID
	(*trdcommon.TrdHeader)(nil), // 5: Trd_Common.TrdHeader
	(*qotcommon.ComboLeg)(nil),  // 6: Qot_Common.ComboLeg
}
var file_Trd_PlaceComboOrder_proto_depIdxs = []int32{
	4, // 0: Trd_PlaceComboOrder.C2S.packetID:type_name -> Common.PacketID
	5, // 1: Trd_PlaceComboOrder.C2S.header:type_name -> Trd_Common.TrdHeader
	6, // 2: Trd_PlaceComboOrder.C2S.comboLegs:type_name -> Qot_Common.ComboLeg
	5, // 3: Trd_PlaceComboOrder.S2C.header:type_name -> Trd_Common.TrdHeader
	0, // 4: Trd_PlaceComboOrder.Request.c2s:type_name -> Trd_PlaceComboOrder.C2S
	1, // 5: Trd_PlaceComboOrder.Response.s2c:type_name -> Trd_PlaceComboOrder.S2C
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_Trd_PlaceComboOrder_proto_init() }
func file_Trd_PlaceComboOrder_proto_init() {
	if File_Trd_PlaceComboOrder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Trd_PlaceComboOrder_proto_rawDesc), len(file_Trd_PlaceComboOrder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Trd_PlaceComboOrder_proto_goTypes,
		DependencyIndexes: file_Trd_PlaceComboOrder_proto_depIdxs,
		MessageInfos:      file_Trd_PlaceComboOrder_proto_msgTypes,
	}.Build()
	File_Trd_PlaceComboOrder_proto = out.File
	file_Trd_PlaceComboOrder_proto_goTypes = nil
	file_Trd_PlaceComboOrder_proto_depIdxs = nil
}
