// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: Qot_GetDividendRank.proto

package qotgetdividendrank

import (
	qotcommon "github.com/shing1211/futuapi4go/pkg/pb/qotcommon"
	qotoptioncommon "github.com/shing1211/futuapi4go/pkg/pb/qotoptioncommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 股息排行类型
type DividendRankType int32

const (
	DividendRankType_DividendRankType_Unknown        DividendRankType = 0
	DividendRankType_DividendRankType_HighYield      DividendRankType = 1 // 高股息率
	DividendRankType_DividendRankType_DividendGrowth DividendRankType = 2 // 股息保持增长
)

// Enum value maps for DividendRankType.
var (
	DividendRankType_name = map[int32]string{
		0: "DividendRankType_Unknown",
		1: "DividendRankType_HighYield",
		2: "DividendRankType_DividendGrowth",
	}
	DividendRankType_value = map[string]int32{
		"DividendRankType_Unknown":        0,
		"DividendRankType_HighYield":      1,
		"DividendRankType_DividendGrowth": 2,
	}
)

func (x DividendRankType) Enum() *DividendRankType {
	p := new(DividendRankType)
	*p = x
	return p
}

func (x DividendRankType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DividendRankType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetDividendRank_proto_enumTypes[0].Descriptor()
}

func (DividendRankType) Type() protoreflect.EnumType {
	return &file_Qot_GetDividendRank_proto_enumTypes[0]
}

func (x DividendRankType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DividendRankType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DividendRankType(num)
	return nil
}

// Deprecated: Use DividendRankType.Descriptor instead.
func (DividendRankType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetDividendRank_proto_rawDescGZIP(), []int{0}
}

// 筛选条件类型
type IndicatorType int32

const (
	IndicatorType_IndicatorType_Unknown               IndicatorType = 0
	IndicatorType_IndicatorType_DividendYieldTTM      IndicatorType = 1 //【范围】股息率TTM (%)
	IndicatorType_IndicatorType_AvgDividendYield5Y    IndicatorType = 2 //【范围】5年平均股息率 (%)
	IndicatorType_IndicatorType_DistributionFrequency IndicatorType = 3 //【枚举】派息频率 (1:年派, 2:半年派, 3:季派, 4:月派)
	IndicatorType_IndicatorType_DividendGrowYear      IndicatorType = 4 //【范围】股息连续增长年数
	IndicatorType_IndicatorType_DividendsTTM          IndicatorType = 5 //【范围】股息TTM (金额)
	IndicatorType_IndicatorType_PayoutRatioLFY        IndicatorType = 6 //【范围】股息支付率LFY (%)
	IndicatorType_IndicatorType_NextPayableDate       IndicatorType = 7 //【范围】下次派息日 (相对天数)
	IndicatorType_IndicatorType_Price                 IndicatorType = 8 //【范围】最新价
	IndicatorType_IndicatorType_MarketCap             IndicatorType = 9 //【范围】市值
)

// Enum value maps for IndicatorType.
var (
	IndicatorType_name = map[int32]string{
		0: "IndicatorType_Unknown",
		1: "IndicatorType_DividendYieldTTM",
		2: "IndicatorType_AvgDividendYield5Y",
		3: "IndicatorType_DistributionFrequency",
		4: "IndicatorType_DividendGrowYear",
		5: "IndicatorType_DividendsTTM",
		6: "IndicatorType_PayoutRatioLFY",
		7: "IndicatorType_NextPayableDate",
		8: "IndicatorType_Price",
		9: "IndicatorType_MarketCap",
	}
	IndicatorType_value = map[string]int32{
		"IndicatorType_Unknown":               0,
		"IndicatorType_DividendYieldTTM":      1,
		"IndicatorType_AvgDividendYield5Y":    2,
		"IndicatorType_DistributionFrequency": 3,
		"IndicatorType_DividendGrowYear":      4,
		"IndicatorType_DividendsTTM":          5,
		"IndicatorType_PayoutRatioLFY":        6,
		"IndicatorType_NextPayableDate":       7,
		"IndicatorType_Price":                 8,
		"IndicatorType_MarketCap":             9,
	}
)

func (x IndicatorType) Enum() *IndicatorType {
	p := new(IndicatorType)
	*p = x
	return p
}

func (x IndicatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndicatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetDividendRank_proto_enumTypes[1].Descriptor()
}

func (IndicatorType) Type() protoreflect.EnumType {
	return &file_Qot_GetDividendRank_proto_enumTypes[1]
}

func (x IndicatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IndicatorType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IndicatorType(num)
	return nil
}

// Deprecated: Use IndicatorType.Descriptor instead.
func (IndicatorType) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetDividendRank_proto_rawDescGZIP(), []int{1}
}

// 排序字段 (固定降序)
type SortField int32

const (
	SortField_SortField_Unknown               SortField = 0  // 默认: HighYield→股息率TTM, DividendGrowth→连续增长年数
	SortField_SortField_DividendYieldTTM      SortField = 1  // 股息率TTM
	SortField_SortField_AvgDividendYield5Y    SortField = 2  // 5年平均股息率
	SortField_SortField_DistributionFrequency SortField = 3  // 派息频率
	SortField_SortField_DividendGrowYear      SortField = 4  // 股息连续增长年数
	SortField_SortField_DividendsTTM          SortField = 5  // 股息TTM
	SortField_SortField_PayoutRatioLFY        SortField = 6  // 股息支付率LFY
	SortField_SortField_Price                 SortField = 7  // 价格
	SortField_SortField_MarketCap             SortField = 8  // 市值
	SortField_SortField_ChangeRate            SortField = 9  // 今日涨跌幅
	SortField_SortField_ChangeAmount          SortField = 10 // 今日涨跌额
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0:  "SortField_Unknown",
		1:  "SortField_DividendYieldTTM",
		2:  "SortField_AvgDividendYield5Y",
		3:  "SortField_DistributionFrequency",
		4:  "SortField_DividendGrowYear",
		5:  "SortField_DividendsTTM",
		6:  "SortField_PayoutRatioLFY",
		7:  "SortField_Price",
		8:  "SortField_MarketCap",
		9:  "SortField_ChangeRate",
		10: "SortField_ChangeAmount",
	}
	SortField_value = map[string]int32{
		"SortField_Unknown":               0,
		"SortField_DividendYieldTTM":      1,
		"SortField_AvgDividendYield5Y":    2,
		"SortField_DistributionFrequency": 3,
		"SortField_DividendGrowYear":      4,
		"SortField_DividendsTTM":          5,
		"SortField_PayoutRatioLFY":        6,
		"SortField_Price":                 7,
		"SortField_MarketCap":             8,
		"SortField_ChangeRate":            9,
		"SortField_ChangeAmount":          10,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_Qot_GetDividendRank_proto_enumTypes[2].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_Qot_GetDividendRank_proto_enumTypes[2]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SortField) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SortField(num)
	return nil
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_Qot_GetDividendRank_proto_rawDescGZIP(), []int{2}
}

// 筛选条件
type Indicator struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	IndicatorType  *int32                          `protobuf:"varint,1,req,name=indicatorType" json:"indicatorType,omitempty"`  // IndicatorType
	IndicatorValue *qotoptioncommon.IndicatorValue `protobuf:"bytes,2,opt,name=indicatorValue" json:"indicatorValue,omitempty"` // 筛选值(枚举型用valueList, 范围型用valueInterval)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Indicator) Reset() {
	*x = Indicator{}
	mi := &file_Qot_GetDividendRank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Indicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indicator) ProtoMessage() {}

func (x *Indicator) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendRank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Indicator.ProtoReflect.Descriptor instead.
func (*Indicator) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendRank_proto_rawDescGZIP(), []int{0}
}

func (x *Indicator) GetIndicatorType() int32 {
	if x != nil && x.IndicatorType != nil {
		return *x.IndicatorType
	}
	return 0
}

func (x *Indicator) GetIndicatorValue() *qotoptioncommon.IndicatorValue {
	if x != nil {
		return x.IndicatorValue
	}
	return nil
}

type C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *int32                 `protobuf:"varint,1,req,name=market" json:"market,omitempty"`        // Qot_Common.QotMarket (仅支持 HK=1, US=11, MY=61, SG=31, JP=41)
	RankType      *int32                 `protobuf:"varint,2,req,name=rankType" json:"rankType,omitempty"`    // DividendRankType
	Count         *int32                 `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`          // 返回数量 [1,300], 默认10
	FilterList    []*Indicator           `protobuf:"bytes,4,rep,name=filterList" json:"filterList,omitempty"` // 可选筛选条件(AND关系)
	SortField     *int32                 `protobuf:"varint,5,opt,name=sortField" json:"sortField,omitempty"`  // SortField, 排序字段(固定降序), 默认由rankType决定
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S) Reset() {
	*x = C2S{}
	mi := &file_Qot_GetDividendRank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S) ProtoMessage() {}

func (x *C2S) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendRank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S.ProtoReflect.Descriptor instead.
func (*C2S) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendRank_proto_rawDescGZIP(), []int{1}
}

func (x *C2S) GetMarket() int32 {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return 0
}

func (x *C2S) GetRankType() int32 {
	if x != nil && x.RankType != nil {
		return *x.RankType
	}
	return 0
}

func (x *C2S) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *C2S) GetFilterList() []*Indicator {
	if x != nil {
		return x.FilterList
	}
	return nil
}

func (x *C2S) GetSortField() int32 {
	if x != nil && x.SortField != nil {
		return *x.SortField
	}
	return 0
}

// 股息排行数据项
type DividendRankItem struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Security *qotcommon.Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"` // 股票
	Name     *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`         // 名称
	Industry *string                `protobuf:"bytes,3,opt,name=industry" json:"industry,omitempty"` // 行业
	// 行情
	CurPrice     *float64 `protobuf:"fixed64,10,opt,name=curPrice" json:"curPrice,omitempty"`         // 最新价
	ChangeRate   *float64 `protobuf:"fixed64,11,opt,name=changeRate" json:"changeRate,omitempty"`     // 今日涨跌幅 (%)
	ChangeAmount *float64 `protobuf:"fixed64,12,opt,name=changeAmount" json:"changeAmount,omitempty"` // 今日涨跌额
	MarketCap    *float64 `protobuf:"fixed64,13,opt,name=marketCap" json:"marketCap,omitempty"`       // 市值
	// 股息
	DividendYieldTTM      *float64 `protobuf:"fixed64,20,opt,name=dividendYieldTTM" json:"dividendYieldTTM,omitempty"`          // 股息率TTM (%)
	AvgDividendYield5Y    *float64 `protobuf:"fixed64,21,opt,name=avgDividendYield5Y" json:"avgDividendYield5Y,omitempty"`      // 5年平均股息率 (%)
	DistributionFrequency *int32   `protobuf:"varint,22,opt,name=distributionFrequency" json:"distributionFrequency,omitempty"` // 派息频率 (1:年派, 2:半年派, 3:季派, 4:月派)，不支持HK市场
	DividendGrowYear      *int32   `protobuf:"varint,23,opt,name=dividendGrowYear" json:"dividendGrowYear,omitempty"`           // 股息连续增长年数
	DividendsTTM          *float64 `protobuf:"fixed64,24,opt,name=dividendsTTM" json:"dividendsTTM,omitempty"`                  // 股息TTM (金额)
	PayoutRatioLFY        *float64 `protobuf:"fixed64,25,opt,name=payoutRatioLFY" json:"payoutRatioLFY,omitempty"`              // 股息支付率LFY (%)
	NextPayableDate       *string  `protobuf:"bytes,26,opt,name=nextPayableDate" json:"nextPayableDate,omitempty"`              // 下次派息日 ("YYYY-MM-DD")
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DividendRankItem) Reset() {
	*x = DividendRankItem{}
	mi := &file_Qot_GetDividendRank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DividendRankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DividendRankItem) ProtoMessage() {}

func (x *DividendRankItem) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendRank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DividendRankItem.ProtoReflect.Descriptor instead.
func (*DividendRankItem) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendRank_proto_rawDescGZIP(), []int{2}
}

func (x *DividendRankItem) GetSecurity() *qotcommon.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *DividendRankItem) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DividendRankItem) GetIndustry() string {
	if x != nil && x.Industry != nil {
		return *x.Industry
	}
	return ""
}

func (x *DividendRankItem) GetCurPrice() float64 {
	if x != nil && x.CurPrice != nil {
		return *x.CurPrice
	}
	return 0
}

func (x *DividendRankItem) GetChangeRate() float64 {
	if x != nil && x.ChangeRate != nil {
		return *x.ChangeRate
	}
	return 0
}

func (x *DividendRankItem) GetChangeAmount() float64 {
	if x != nil && x.ChangeAmount != nil {
		return *x.ChangeAmount
	}
	return 0
}

func (x *DividendRankItem) GetMarketCap() float64 {
	if x != nil && x.MarketCap != nil {
		return *x.MarketCap
	}
	return 0
}

func (x *DividendRankItem) GetDividendYieldTTM() float64 {
	if x != nil && x.DividendYieldTTM != nil {
		return *x.DividendYieldTTM
	}
	return 0
}

func (x *DividendRankItem) GetAvgDividendYield5Y() float64 {
	if x != nil && x.AvgDividendYield5Y != nil {
		return *x.AvgDividendYield5Y
	}
	return 0
}

func (x *DividendRankItem) GetDistributionFrequency() int32 {
	if x != nil && x.DistributionFrequency != nil {
		return *x.DistributionFrequency
	}
	return 0
}

func (x *DividendRankItem) GetDividendGrowYear() int32 {
	if x != nil && x.DividendGrowYear != nil {
		return *x.DividendGrowYear
	}
	return 0
}

func (x *DividendRankItem) GetDividendsTTM() float64 {
	if x != nil && x.DividendsTTM != nil {
		return *x.DividendsTTM
	}
	return 0
}

func (x *DividendRankItem) GetPayoutRatioLFY() float64 {
	if x != nil && x.PayoutRatioLFY != nil {
		return *x.PayoutRatioLFY
	}
	return 0
}

func (x *DividendRankItem) GetNextPayableDate() string {
	if x != nil && x.NextPayableDate != nil {
		return *x.NextPayableDate
	}
	return ""
}

type S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataList      []*DividendRankItem    `protobuf:"bytes,1,rep,name=dataList" json:"dataList,omitempty"` // 数据列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C) Reset() {
	*x = S2C{}
	mi := &file_Qot_GetDividendRank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C) ProtoMessage() {}

func (x *S2C) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendRank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C.ProtoReflect.Descriptor instead.
func (*S2C) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendRank_proto_rawDescGZIP(), []int{3}
}

func (x *S2C) GetDataList() []*DividendRankItem {
	if x != nil {
		return x.DataList
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *C2S                   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_Qot_GetDividendRank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendRank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendRank_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetC2S() *C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       *int32                 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"` // RetType, 返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C           *S2C                   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Response fields.
const (
	Default_Response_RetType = int32(-400)
)

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_Qot_GetDividendRank_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Qot_GetDividendRank_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Qot_GetDividendRank_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetRetType() int32 {
	if x != nil && x.RetType != nil {
		return *x.RetType
	}
	return Default_Response_RetType
}

func (x *Response) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Response) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Response) GetS2C() *S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

var File_Qot_GetDividendRank_proto protoreflect.FileDescriptor

const file_Qot_GetDividendRank_proto_rawDesc = "" +
	"\n" +
	"\x19Qot_GetDividendRank.proto\x12\x13Qot_GetDividendRank\x1a\x10Qot_Common.proto\x1a\x16Qot_OptionCommon.proto\"{\n" +
	"\tIndicator\x12$\n" +
	"\rindicatorType\x18\x01 \x02(\x05R\rindicatorType\x12H\n" +
	"\x0eindicatorValue\x18\x02 \x01(\v2 .Qot_OptionCommon.IndicatorValueR\x0eindicatorValue\"\xad\x01\n" +
	"\x03C2S\x12\x16\n" +
	"\x06market\x18\x01 \x02(\x05R\x06market\x12\x1a\n" +
	"\brankType\x18\x02 \x02(\x05R\brankType\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12>\n" +
	"\n" +
	"filterList\x18\x04 \x03(\v2\x1e.Qot_GetDividendRank.IndicatorR\n" +
	"filterList\x12\x1c\n" +
	"\tsortField\x18\x05 \x01(\x05R\tsortField\"\xa6\x04\n" +
	"\x10DividendRankItem\x120\n" +
	"\bsecurity\x18\x01 \x02(\v2\x14.Qot_Common.SecurityR\bsecurity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bindustry\x18\x03 \x01(\tR\bindustry\x12\x1a\n" +
	"\bcurPrice\x18\n" +
	" \x01(\x01R\bcurPrice\x12\x1e\n" +
	"\n" +
	"changeRate\x18\v \x01(\x01R\n" +
	"changeRate\x12\"\n" +
	"\fchangeAmount\x18\f \x01(\x01R\fchangeAmount\x12\x1c\n" +
	"\tmarketCap\x18\r \x01(\x01R\tmarketCap\x12*\n" +
	"\x10dividendYieldTTM\x18\x14 \x01(\x01R\x10dividendYieldTTM\x12.\n" +
	"\x12avgDividendYield5Y\x18\x15 \x01(\x01R\x12avgDividendYield5Y\x124\n" +
	"\x15distributionFrequency\x18\x16 \x01(\x05R\x15distributionFrequency\x12*\n" +
	"\x10dividendGrowYear\x18\x17 \x01(\x05R\x10dividendGrowYear\x12\"\n" +
	"\fdividendsTTM\x18\x18 \x01(\x01R\fdividendsTTM\x12&\n" +
	"\x0epayoutRatioLFY\x18\x19 \x01(\x01R\x0epayoutRatioLFY\x12(\n" +
	"\x0fnextPayableDate\x18\x1a \x01(\tR\x0fnextPayableDate\"H\n" +
	"\x03S2C\x12A\n" +
	"\bdataList\x18\x01 \x03(\v2%.Qot_GetDividendRank.DividendRankItemR\bdataList\"5\n" +
	"\aRequest\x12*\n" +
	"\x03c2s\x18\x01 \x02(\v2\x18.Qot_GetDividendRank.C2SR\x03c2s\"\x88\x01\n" +
	"\bResponse\x12\x1e\n" +
	"\aretType\x18\x01 \x02(\x05:\x04-400R\aretType\x12\x16\n" +
	"\x06retMsg\x18\x02 \x01(\tR\x06retMsg\x12\x18\n" +
	"\aerrCode\x18\x03 \x01(\x05R\aerrCode\x12*\n" +
	"\x03s2c\x18\x04 \x01(\v2\x18.Qot_GetDividendRank.S2CR\x03s2c*u\n" +
	"\x10DividendRankType\x12\x1c\n" +
	"\x18DividendRankType_Unknown\x10\x00\x12\x1e\n" +
	"\x1aDividendRankType_HighYield\x10\x01\x12#\n" +
	"\x1fDividendRankType_DividendGrowth\x10\x02*\xdc\x02\n" +
	"\rIndicatorType\x12\x19\n" +
	"\x15IndicatorType_Unknown\x10\x00\x12\"\n" +
	"\x1eIndicatorType_DividendYieldTTM\x10\x01\x12$\n" +
	" IndicatorType_AvgDividendYield5Y\x10\x02\x12'\n" +
	"#IndicatorType_DistributionFrequency\x10\x03\x12\"\n" +
	"\x1eIndicatorType_DividendGrowYear\x10\x04\x12\x1e\n" +
	"\x1aIndicatorType_DividendsTTM\x10\x05\x12 \n" +
	"\x1cIndicatorType_PayoutRatioLFY\x10\x06\x12!\n" +
	"\x1dIndicatorType_NextPayableDate\x10\a\x12\x17\n" +
	"\x13IndicatorType_Price\x10\b\x12\x1b\n" +
	"\x17IndicatorType_MarketCap\x10\t*\xc7\x02\n" +
	"\tSortField\x12\x15\n" +
	"\x11SortField_Unknown\x10\x00\x12\x1e\n" +
	"\x1aSortField_DividendYieldTTM\x10\x01\x12 \n" +
	"\x1cSortField_AvgDividendYield5Y\x10\x02\x12#\n" +
	"\x1fSortField_DistributionFrequency\x10\x03\x12\x1e\n" +
	"\x1aSortField_DividendGrowYear\x10\x04\x12\x1a\n" +
	"\x16SortField_DividendsTTM\x10\x05\x12\x1c\n" +
	"\x18SortField_PayoutRatioLFY\x10\x06\x12\x13\n" +
	"\x0fSortField_Price\x10\a\x12\x17\n" +
	"\x13SortField_MarketCap\x10\b\x12\x18\n" +
	"\x14SortField_ChangeRate\x10\t\x12\x1a\n" +
	"\x16SortField_ChangeAmount\x10\n" +
	"BP\n" +
	"\x13com.futu.openapi.pbZ9github.com/shing1211/futuapi4go/pkg/pb/qotgetdividendrank"

var (
	file_Qot_GetDividendRank_proto_rawDescOnce sync.Once
	file_Qot_GetDividendRank_proto_rawDescData []byte
)

func file_Qot_GetDividendRank_proto_rawDescGZIP() []byte {
	file_Qot_GetDividendRank_proto_rawDescOnce.Do(func() {
		file_Qot_GetDividendRank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Qot_GetDividendRank_proto_rawDesc), len(file_Qot_GetDividendRank_proto_rawDesc)))
	})
	return file_Qot_GetDividendRank_proto_rawDescData
}

var file_Qot_GetDividendRank_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Qot_GetDividendRank_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Qot_GetDividendRank_proto_goTypes = []any{
	(DividendRankType)(0),                  // 0: Qot_GetDividendRank.DividendRankType
	(IndicatorType)(0),                     // 1: Qot_GetDividendRank.IndicatorType
	(SortField)(0),                         // 2: Qot_GetDividendRank.SortField
	(*Indicator)(nil),                      // 3: Qot_GetDividendRank.Indicator
	(*C2S)(nil),                            // 4: Qot_GetDividendRank.C2S
	(*DividendRankItem)(nil),               // 5: Qot_GetDividendRank.DividendRankItem
	(*S2C)(nil),                            // 6: Qot_GetDividendRank.S2C
	(*Request)(nil),                        // 7: Qot_GetDividendRank.Request
	(*Response)(nil),                       // 8: Qot_GetDividendRank.Response
	(*qotoptioncommon.IndicatorValue)(nil), // 9: Qot_OptionCommon.IndicatorValue
	(*qotcommon.Security)(nil),             // 10: Qot_Common.Security
}
var file_Qot_GetDividendRank_proto_depIdxs = []int32{
	9,  // 0: Qot_GetDividendRank.Indicator.indicatorValue:type_name -> Qot_OptionCommon.IndicatorValue
	3,  // 1: Qot_GetDividendRank.C2S.filterList:type_name -> Qot_GetDividendRank.Indicator
	10, // 2: Qot_GetDividendRank.DividendRankItem.security:type_name -> Qot_Common.Security
	5,  // 3: Qot_GetDividendRank.S2C.dataList:type_name -> Qot_GetDividendRank.DividendRankItem
	4,  // 4: Qot_GetDividendRank.Request.c2s:type_name -> Qot_GetDividendRank.C2S
	6,  // 5: Qot_GetDividendRank.Response.s2c:type_name -> Qot_GetDividendRank.S2C
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_Qot_GetDividendRank_proto_init() }
func file_Qot_GetDividendRank_proto_init() {
	if File_Qot_GetDividendRank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Qot_GetDividendRank_proto_rawDesc), len(file_Qot_GetDividendRank_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Qot_GetDividendRank_proto_goTypes,
		DependencyIndexes: file_Qot_GetDividendRank_proto_depIdxs,
		EnumInfos:         file_Qot_GetDividendRank_proto_enumTypes,
		MessageInfos:      file_Qot_GetDividendRank_proto_msgTypes,
	}.Build()
	File_Qot_GetDividendRank_proto = out.File
	file_Qot_GetDividendRank_proto_goTypes = nil
	file_Qot_GetDividendRank_proto_depIdxs = nil
}
